#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
601 张新姿势的命名表（逐张看图人工填写）。

命名规则（与第一批 205 条保持一致）：
  name   = '<体位> · <动作细节>'      中文短名
  desc   = 一句中文说明，描述画面实际动作
  prompt = 英文描述，**这才是真正发给生图模型的内容**

⚠️ 两个铁律（第一批踩过）：
1. **idx 必须与 sheet_index_new.json 核对，不能凭记忆写**。
   上一批凭记忆写 add(45,...) 连续改错两次。这里 add() 内置断言：
   重复 idx 直接抛错，越界也抛错。
2. **不要批量套模板**。曾出现过 8 条中文名完全一样的「批量退化」，
   后来靠加唯一性断言才查出来。所有 add() 必须对应真实画面。

用法（在 09-pose-names-new.py 里写 add(...)）：
  add(0,'站立 · 双手叉腰','双脚分开站立，双手叉腰，肩部打开','standing with feet apart and both hands on the hips, shoulders open')
"""
import re

# idx -> (name, desc, prompt)
_NAMES = []


def add(idx, name, desc, prompt):
    if not (0 <= idx <= 600):
        raise ValueError(f'idx {idx} 越界（有效 0..600）')
    if any(e[0] == idx for e in _NAMES):
        raise ValueError(f'idx {idx} 重复添加')
    for f in (name, desc, prompt):
        if not f or not f.strip():
            raise ValueError(f'idx {idx} 有空字段：{name!r} {desc!r} {prompt!r}')
    if not re.search(r'[a-zA-Z]', prompt):
        raise ValueError(f'idx {idx} 的 prompt 不像英文：{prompt!r}')
    _NAMES.append((idx, name.strip(), desc.strip(), prompt.strip()))


def all_names():
    return sorted(_NAMES, key=lambda x: x[0])


def coverage(total=601):
    got = {e[0] for e in _NAMES}
    missing = [i for i in range(total) if i not in got]
    return len(got), missing


# ══════════════════════════════════════════════════════════════════
# 逐张看图填写（sheet 00~30，每张 20 格）
# 命名铁律见文件头：idx 必须与 sheet_index_new.json 核对，禁止批量套模板
# ══════════════════════════════════════════════════════════════════

# ---------- sheet 00: #000-#019 ----------
add(0,  '站立 · 双手叉腰', '双脚分开与肩同宽站立，双手叉腰，肩部打开', 'standing with feet apart, both hands on the hips, shoulders open')
add(1,  '站立 · 单手前伸掌心向上', '侧身站立，一手向前伸出掌心向上，另一手自然下垂', 'standing in profile, one arm extended forward with the palm facing up, the other arm relaxed')
add(2,  '深蹲 · 双手撑膝', '深蹲双脚分开，手掌撑在大腿上，上身略前倾', 'in a deep squat with feet wide apart, both palms resting on the thighs, torso leaning slightly forward')
add(3,  '弓步 · 双臂上举后仰', '弓步前腿弯后腿直，双臂高举过头，上身后仰', 'in a lunge with the front knee bent and the back leg straight, both arms raised overhead and the torso leaning back')
add(4,  '站立 · 侧身摆臂', '侧身站立，一腿微曲，双臂向身侧摆动', 'standing in profile with one leg slightly bent, both arms swinging out to the sides')
add(5,  '站立 · 单手比划', '正面站立，一手抬起做出比划的手势，另一手叉腰', 'standing facing front, one hand raised in a gesturing pose, the other hand on the hip')
add(6,  '站立 · 屈肘侧身', '侧身站立，双臂屈肘抬起，上身微微后仰', 'standing in profile with both arms bent and raised, torso leaning slightly back')
add(7,  '行走 · 迈步前行', '自然行走姿态，双腿一前一后，双臂自然摆动', 'mid-stride walking with one leg forward and both arms swinging naturally')
add(8,  '奔跑 · 摆臂冲刺', '奔跑姿势，身体前倾，双臂前后大幅摆动', 'running with the torso leaning forward and both arms pumping widely')
add(9,  '奔跑 · 前跨大步', '大步向前跨出，后腿蹬地，双臂屈肘摆动', 'striding far forward with the back leg pushing off and both arms bent while swinging')
add(10, '深蹲 · 低蹲双手垂膝', '极低蹲姿，双脚分开，膝盖几乎触地，双手垂在膝间', 'in a very deep squat with feet apart, knees nearly on the ground, both arms hanging between the knees')
add(11, '半跪 · 单拳上举', '单膝跪地，一拳向上举起，另一手撑地，头部微仰', 'kneeling on one knee with one fist raised overhead, the other hand on the ground, head tilted slightly up')
add(12, '半跪 · 俯身垂头', '单膝跪地，上身前俯，头部低垂，双手垂落', 'kneeling on one knee with the torso folded forward and the head lowered, both arms hanging down')
add(13, '弓步 · 双手触地', '弓步前腿弯曲，后腿伸直，双手撑地，头部朝前', 'in a lunge with the front knee bent and the back leg straight, both hands on the ground facing forward')
add(14, '站立 · 一手扶髋', '正面站立，一手叉腰，另一手自然垂在身侧', 'standing facing front with one hand on the hip and the other arm relaxed at the side')
add(15, '站立 · 单手扶头', '站立姿势，一手抬起扶住头顶，另一手叉腰', 'standing with one hand raised to the top of the head and the other hand on the hip')
add(16, '站立 · 双臂交叠胸前', '站立，双臂在胸前交叠抱起，肩部微微后收', 'standing with both arms crossed and folded across the chest, shoulders slightly drawn back')
add(17, '站立 · 手托下颌', '侧身站立，一手抬起托在下颌旁，姿态从容', 'standing in profile with one hand raised to the chin in a composed pose')
add(18, '深蹲 · 蹲姿侧看', '深蹲姿势，双脚分开略宽于肩，身体重心居中', 'in a squat with feet slightly wider than the shoulders, the weight centered')
add(19, '站立 · 双臂交抱', '正面站立，双臂在身前交抱，双脚平行分开', 'standing facing front with both arms folded in front of the body and feet parallel')

# ---------- sheet 01: #020-#039 ----------
add(20, '弓步 · 双手握拳前推', '弓步站定，一腿弯曲，另一腿伸直，双臂向前握拳推出', 'in a lunge with one leg bent and the other extended, both arms punching forward with fists closed')
add(21, '舞蹈 · 侧滑步伸臂', '身体侧倾，一手向上伸展，另一手向侧下方伸出，双腿交叉', 'leaning sideways with one arm reaching up and the other extended down, legs crossed in a dance step')
add(22, '平衡 · 单腿站立抬臂', '单腿站立，另一腿抬起，双手臂向前平举保持平衡', 'balancing on one leg with the other leg raised, both arms extended forward for balance')
add(23, '站立 · 双手交握上举', '站立，双臂在头顶交握，手臂伸直向上', 'standing with both arms raised and hands clasped together overhead, arms fully extended')
add(24, '站立 · 侧身扬手', '侧身站立，一手叉腰，另一手向外扬起', 'standing in profile with one hand on the hip and the other arm raised outward')
add(25, '站立 · 搭肩侧倾', '侧身站立，一臂横过胸前搭住对侧肩膀，身体侧倾', 'standing in profile with one arm across the chest resting on the opposite shoulder, body leaning sideways')
add(26, '站立 · 单臂高举', '正面站立，一只手高举过头，另一手自然下垂', 'standing facing front with one hand raised high overhead and the other arm relaxed')
add(27, '站立 · 叉腰侧分腿', '站立，双腿分开侧向，一手叉腰，另一手垂落', 'standing with the legs spread apart, one hand on the hip and the other arm hanging down')
add(28, '站立 · 双臂侧平举', '双脚平行分开站立，双臂向两侧水平伸展成T 形', 'standing with both arms extended horizontally to the sides in a T shape, feet parallel')
add(29, '站立 · 单手扶后脑', '站立，一手抬起扶住后脑，另一手自然下垂', 'standing with one hand raised behind the head and the other arm relaxed')
add(30, '站立 · 单臂上举侧倾', '站立，一只手高举过头，上身向另一侧倾斜', 'standing with one arm raised overhead and the torso leaning to the opposite side')
add(31, '瑜伽 · 单腿站立树上式', '单腿站立，另一腿弯曲脚掌贴于支撑腿内侧，双手在胸前合十', 'balancing on one leg in a tree pose with the other foot pressed to the inner thigh and palms together at the chest')
add(32, '蹲姿 · 抱膝坐立', '深蹲后抱住双膝收拢成团，头部微低', 'in a squat hugging both knees drawn up close to the chest, head slightly lowered')
add(33, '瑜伽 · 战士三式伸展', '单腿站立，另一腿向后抬起成一直线，一臂前伸一臂后展', 'balancing on one leg with the other extended straight back, one arm forward and the other arm extended behind')
add(34, '瑜伽 · 侧角式伸展', '双脚分开站立，一腿弯曲下蹲，另一腿伸直，双臂一上一下伸展成对角线', 'in a wide stance with one leg bent and the other extended straight, arms reaching up and down in opposite diagonals')
add(35, '瑜伽 · 眼镜蛇式', '俯卧，双腿贴地，上半身用手臂撑起高高抬起，胸口打开', 'lying prone with legs on the ground, the upper body lifted high by the arms and the chest opened')
add(36, '瑜伽 · 树式侧伸展', '单腿站立，另一腿弯曲，双手在头顶合十向一侧倾斜', 'balancing on one leg with the other bent, palms joined overhead and the body leaning to one side')
add(37, '瑜伽 · 鹰式展翅', '单腿站立，另一腿绕过支撑腿，双手在胸前交扣后向上展开', 'balancing on one leg with the other leg wrapped around it, arms crossed at the chest then extended upward')
add(38, '瑜伽 · 后弯战士式', '弓步下压后仰，一臂上举过头，一臂后伸，双臂成对角线展开', 'in a deep lunge leaning back, one arm overhead and the other extended behind, arms spread in opposite diagonals')
add(39, '站立 · 单手抚后颈', '站立，一手抬起抚住后颈，另一手叉腰，上身微侧', 'standing with one hand touching the back of the neck and the other on the hip, torso slightly turned')

# ---------- sheet 02-30：由子代理逐张看图产出，已合并校验 ----------
add(40, '站立 · 举拳屈臂叉腰', '正面站立，右臂屈肘举拳至头侧，左手叉腰', 'front view standing with the right arm bent up in a fist beside the head and the left hand on the hip')
add(41, '站立 · 单臂侧平扬掌', '侧身站立，右臂向侧后方平伸，掌心朝上，头微侧', 'standing in three-quarter view with one arm extended out to the side palm up and the head turned slightly')
add(42, '腾跃 · 单腿后踢探臂', '腾空跃起，左腿向后屈踢，双臂前上方探出', 'mid-air leaping with one leg kicked back bent and both arms reaching forward and up')
add(43, '前倾 · 交叉步掠臂', '上身前倾，双腿交叉成弓步，一臂向后方高处甩出', 'leaning the torso forward with the legs crossed in a lunge and one arm swung back and up')
add(44, '站立 · 双臂水平展开', '正面站立，双腿微微分开，双臂向两侧水平伸直', 'front view standing with legs slightly apart and both arms stretched straight out to the sides')
add(45, '低蹲 · 双臂外张屈肘', '深低蹲姿，膝盖弯曲，双臂向两侧张开、肘部弯曲', 'in a deep squat with the knees bent and both arms spread out to the sides with elbows bent')
add(46, '后弯 · 单臂上举挺胸', '身体向后挺出胸腔，一臂高举过头顶，双膝微屈', 'arching the torso backward with the chest open and one arm reaching overhead, knees slightly bent')
add(47, '跳跃 · 单臂高举屈膝', '腾空跳跃，一臂向上高举，另一臂侧平，双腿屈膝后收', 'jumping with one arm raised high, the other extended sideways and both knees bent back')
add(48, '平衡 · 单腿前抬双臂前伸', '单腿站立支撑，另一腿向前抬起，双臂前伸交叠', 'balancing on one leg with the other leg raised forward and both arms extended in front')
add(49, '仰卧 · 双臂上举双腿交举', '仰卧在地，双臂向上举直，一条腿伸直上抬、另一条屈膝', 'lying on the back with both arms raised straight up, one leg extended up and the other knee bent')
add(50, '俯卧 · 四肢抬起游泳姿', '俯卧伸直身体，双臂前伸，双腿屈膝向上翘起', 'lying prone with the body straight, arms reaching forward and both legs bent upward')
add(51, '深蹲 · 前伸双手探地', '半蹲成弓步，双臂向前下方伸出，指尖朝地', 'in a half squat lunge with both arms reaching forward and down toward the floor')
add(52, '低弓步 · 单手触地后蹬', '一腿屈膝下蹲、一腿向后蹬直，一手撑在地面', 'in a low lunge with one knee bent, the back leg extended straight and one hand touching the ground')
add(53, '平衡 · 单腿侧举一手扶足', '单腿站立，另一腿向侧上方大幅抬起，一手抓住抬起的脚', 'standing on one leg while lifting the other high out to the side and holding the raised foot with one hand')
add(54, '站立 · 双臂上举成环', '单脚站立，双臂在头顶弯成椭圆环，掌心相对', 'standing on one foot with both arms curved into an oval ring above the head, palms facing each other')
add(55, '站立 · 单臂绕弧上伸', '身体侧倾，一臂绕过头顶上方，另一臂向侧下方伸展', 'leaning sideways with one arm arcing over the head and the other reaching down and out')
add(56, '奔跑 · 大步跨开双臂展平', '大幅跨步奔跑，双腿前后分开，双臂向两侧展开', 'running with a long stride, legs split front and back and both arms spread wide')
add(57, '撑地 · 侧身单臂撑起', '侧身俯卧撑起，一只手撑住地面，另一臂向上举起', 'holding a side support on one hand with the body turned side-on and the other arm raised upward')
add(58, '平衡 · 俯身单腿后折', '单腿站立，上身俯向前方，另一腿向后上方折起', 'balancing on one leg with the torso folded forward and the other leg bent up behind')
add(59, '站立 · 双手贴身垂放', '正面自然站立，双臂垂放在身体两侧', 'standing neutrally front-on with both arms hanging relaxed at the sides')
add(60, '行走 · 抬手招呼', '正面行走，一手高举向外招呼，另一臂向侧下方摆动', 'walking forward with one hand raised high in a wave and the other arm swinging down and out')
add(61, '站立 · 绕臂上举叉腰', '一臂弯过头顶向上，另一手叉腰，双腿前后错开', 'standing with one arm curving up over the head, the other hand on the hip and the feet staggered')
add(62, '倒立 · 腾空分腿翻转', '身体倒立腾空，双腿向两侧分开成剪刀状', 'inverted in mid-air with the legs split wide apart in a scissor shape')
add(63, '弓步 · 单臂斜指前推', '单膝跪地成弓步，一臂向斜前上方指出去，另一臂收在体侧', 'in a kneeling lunge with one arm reaching diagonally forward and up while the other rests at the side')
add(64, '平衡 · 单腿后折一臂前伸', '单腿站立，另一腿向后屈起，一臂向前伸出', 'standing on one leg with the other leg bent up behind and one arm reaching forward')
add(65, '站立 · 绕臂侧倾交叉步', '双腿交叉站立，一臂绕过头顶，身体向侧方倾斜', 'standing with the legs crossed, one arm arcing over the head and the body tilted sideways')
add(66, '站立 · 双臂垂直上举', '正面站立，双臂伸直高举过头顶', 'standing front-on with both arms extended straight up above the head')
add(67, '站立 · 横臂斜指', '一臂横过胸前向斜上方指出，另一臂自然下垂', 'with one arm crossing the chest to point diagonally upward and the other arm relaxed at the side')
add(68, '深蹲 · 双臂前平伸', '双脚分开半蹲，双臂向正前方平直伸出', 'in a half squat with the feet apart and both arms extended straight forward')
add(69, '前屈 · 俯身双臂下探', '上身前倾，双臂向下伸出探向地面', 'bending the torso forward with both arms reaching down toward the ground')
add(70, '站立 · 屈臂上举托肘', '一臂屈肘举至头顶、掌心向上，另一手托住该侧髋部', 'standing with one arm bent and lifted palm up beside the head and the other hand resting on the hip')
add(71, '前屈 · 双手向前推出', '上身向前倾斜，双臂在身前斜向下方推出', 'leaning the torso forward with both arms reaching out and down in front of the body')
add(72, '站立 · 侧平指引', '一手叉腰，另一臂向侧方平伸、手掌外翻', 'standing with one hand on the hip and the other arm extended sideways with the palm turned out')
add(73, '交叉腿 · 双臂侧展平衡', '单腿支撑，另一腿膝部外展交叉，双臂向两侧展开', 'balancing on one leg with the other knee opened out to the side and both arms spread wide')
add(74, '跳跃 · 屈腿单臂上冲', '腾空跃起，一臂向上伸直，支撑腿屈膝后提', 'leaping into the air with one arm shooting straight up and the supporting leg bent and lifted')
add(75, '深蹲 · 前伸手掌外推', '半蹲身体前倾，双臂前伸、双掌朝外推开', 'in a forward-leaning half squat with both arms reaching ahead and the palms pressing outward')
add(76, '站立 · 叉腰重心后坐', '双手叉腰，膝盖弯曲、重心向后坐，躯干微后仰', 'standing with both hands on the hips, knees bent and the weight shifted back with the torso leaning slightly behind')
add(77, '平衡 · 单腿后折单臂高举', '单腿站立，另一腿向后折起，一臂高举过头', 'standing on one leg with the other folded back and one arm raised overhead')
add(78, '站立 · 双手扶后脑', '正面站立，双肘外展，双手扶在后脑勺上', 'standing front-on with both elbows flared out and the hands placed behind the head')
add(79, '俯身 · 双手扶膝前倾', '上身前倾，双手分别按在两侧膝盖上', 'leaning the torso forward with both hands pressing on the knees')
add(80, '站立 · 单臂屈举侧倾', '身体向侧面弯曲，一臂屈肘举到头侧，另一手叉腰', 'bending sideways with one arm flexed up beside the head and the other hand on the hip')
add(81, '行走 · 侧摆手臂', '行走中一臂向侧后方摆动，另一臂在身前屈起', 'walking with one arm swinging back to the side and the other bent in front of the chest')
add(82, '舞动 · 侧倾双臂展', '身体侧向倾斜，双腿错步，双臂向两侧展开', 'dancing with the body tilted sideways, the feet staggered and both arms spread open')
add(83, '舞动 · 前倾单臂后展', '上身前倾，一臂向侧后方伸展，另一臂收在胸前', 'dancing with the torso leaning forward, one arm reaching out behind and the other drawn in front')
add(84, '杂技 · 单腿竖直上举', '上体前俯，一腿向上竖直举起，双臂向侧面撑开', 'balancing with the torso folded forward, one leg raised straight up and both arms spread out to the sides')
add(85, '卧姿 · 抬腿展臂翻滚', '仰卧屈膝，双腿向上分开抬起，双臂向两侧张开', 'on the back with the knees bent and both legs lifted apart, arms opened wide to the sides')
add(86, '平衡 · 单腿前伸双臂横展', '单腿站立，另一腿向斜前方伸出，双臂向两侧展开', 'balancing on one leg with the other leg extended forward and outward and both arms spread to the sides')
add(87, '深蹲 · 宽距下蹲双拳架起', '双脚大幅分开下蹲，膝外展，双拳在身前架起', 'in a wide deep squat with the knees pushed out and both fists raised in front of the chest')
add(88, '弓步 · 宽展劈腿单臂上扬', '双腿大幅分开成弓步，一臂高举，另一臂向侧下方伸出', 'in a wide striding lunge with one arm raised high and the other reaching down and out')
add(89, '手撑 · 倒立分腿', '双手撑地身体倒立，双腿向两侧分开', 'in a handstand with the legs spread wide apart to the sides')
add(90, '站立 · 背身开立屈臂', '背对镜头站立，双腿分开，双臂屈肘举在胸前', 'standing with the back to the viewer, legs apart and both arms bent up in front of the chest')
add(91, '低蹲 · 单手探地侧头', '深蹲身体低垂，一只手朝地面伸出，头向另一侧倾斜', 'in a low crouch with one hand reaching toward the floor and the head tilted to one side')
add(92, '跃起 · 屈腿后蹬展臂', '腾空跃起，后腿屈膝蹬起，双臂向两侧伸展', 'leaping into the air with the back leg bent and pushing off and both arms extended outward')
add(93, '半跪 · 双手抱头弓背', '单膝跪地弓着背，双手抱在头后，肘部外展', 'kneeling on one knee with the back rounded and both hands clasped behind the head, elbows flared out')
add(94, '仰卧 · 双足过头抱膝', '仰卧蜷起身体，双脚举到头顶上方，双手抱住小腿', 'lying on the back curled up with both feet raised above the head and the hands holding the shins')
add(95, '站立 · 后仰单臂斜举', '身体后仰，一臂向斜上方举起，另一臂向侧方展开', 'leaning back with one arm raised diagonally and the other arm spread out to the side')
add(96, '站立 · 交叉步单臂外展', '双腿交叉站立，一臂向侧上方展开，另一手叉腰', 'standing with the legs crossed, one arm opened out and up to the side and the other hand on the hip')
add(97, '站立 · 单臂直举侧立', '身体侧向站立，一臂伸直高举', 'standing turned to the side with one arm extended straight up')
add(98, '平衡 · 抬腿屈膝臂绕头', '单腿站立，另一腿屈膝抬起，一臂绕过头顶上方', 'balancing on one leg with the other knee lifted and one arm curving over the head')
add(99, '舞动 · 交叉步双臂前伸', '双腿交叉成弓步，双臂向斜前方一同伸出', 'dancing with the legs crossed in a lunge and both arms reaching out together in front')
add(100, '手撑 · 单腿垂直支撑', '一只手撑地，另一条腿向上笔直伸直成倒立', 'in a one-handed handstand with one leg extended straight up')
add(101, '平衡 · 单腿后折一臂侧展', '单腿站立，另一腿向后屈起，一臂向侧方展平', 'standing on one leg with the other bent up behind and one arm extended straight to the side')
add(102, '半跪 · 单臂上举侧展', '半跪在地，一臂向侧上方举起，另一臂向旁展开', 'kneeling on one leg with one arm raised up and to the side and the other arm opened out beside it')
add(103, '平衡 · 抬腿绕臂侧倾', '单腿支撑，另一腿抬起，一臂绕过头顶、身体侧倾', 'balancing on one leg with the other lifted, one arm arcing over the head and the body leaning sideways')
add(104, '弓步 · 腾空跨步一臂上扬', '向前腾空跨出一大步，一臂高举过头', 'leaping forward into a long stride with one arm raised high above the head')
add(105, '跳跃 · 双臂上举交叉腿', '向上跃起，双臂在头顶张开，双腿在空中交叉', 'jumping upward with both arms opened above the head and the legs crossed in mid-air')
add(106, '弓步 · 宽蹲双臂前推', '双脚分开屈膝下蹲，双臂向正前方用力推出', 'in a wide squat with the knees bent and both arms pushing straight forward')
add(107, '平衡 · 单腿后举手扶头', '单腿站立，另一腿向后折起，一手扶在头侧', 'standing on one leg with the other folded up behind and one hand resting beside the head')
add(108, '站立 · 双肘外展双手搭头', '正面站立，双臂抬起，双肘向两侧张开、双手靠近头部', 'standing front-on with both arms raised so the elbows flare outward and the hands hover near the head')
add(109, '手撑 · 倒立屈膝', '双手撑地成倒立，双膝弯曲向胸前收拢', 'in a handstand with both knees bent and drawn up toward the chest')
add(110, '站立 · 双臂交叠圆肩', '正面站立，双臂在胸前交叠，肩膀向前内收', 'standing front-on with the arms folded across the chest and the shoulders rolled forward')
add(111, '站立 · 抱胸侧立交叉腿', '双臂抱在胸前，一腿交叉站到另一腿前，身体侧向', 'standing with the arms folded across the chest and one leg crossed in front of the other, body turned sideways')
add(112, '站立 · 双手托后脑', '正面站立，双臂上举、双手托住后脑，双肘宽展', 'standing front-on with both arms raised and the hands cradling the back of the head, elbows wide open')
add(113, '弓步 · 低蹲单臂上举', '低弓步半蹲，一臂向斜上方举起，另一臂撑在大腿上', 'in a low lunging squat with one arm raised diagonally and the other braced on the thigh')
add(114, '深蹲 · 双手垂地深屈膝', '深蹲到大腿接近水平，双手垂向地面', 'squatting deep until the thighs are near horizontal with both hands hanging down toward the floor')
add(115, '跳跃 · 双臂大展交叉腿', '腾空跃起，双臂向两侧大幅展开，双腿在空中交叠', 'jumping into the air with both arms spread wide and the legs crossed together in mid-air')
add(116, '站立 · 单手抚头侧身', '身体侧向站立，一手抬起扶在头后，另一臂向旁伸出', 'standing turned to the side with one hand lifted behind the head and the other arm reaching out')
add(117, '手撑 · 倒立开腿', '双手撑地倒立身体，双腿分开向两侧伸直', 'in a handstand with both legs extended and spread wide apart')
add(118, '跳跃 · 双臂上冲屈腿', '向上腾空跳起，双臂高举，一腿屈膝后收', 'jumping upward with both arms raised and one leg bent and drawn up behind')
add(119, '跳跃 · 单臂高举跨步', '跨步跳跃中，一臂高举向上，另一臂向侧平伸', 'leaping in a stride with one arm raised high and the other extended horizontally to the side')
add(120, '平衡 · 单腿抬膝双臂展开', '单腿站立，另一腿屈膝抬到体侧，双臂向两侧展开', 'balancing on one leg with the other knee lifted to the side and both arms spread outward')
add(121, '站立 · 屈臂侧摆', '正面站立，一臂屈肘向侧上方摆动，另一臂弯在体侧', 'standing front-on with one arm swung bent up and to the side and the other arm bent near the body')
add(122, '平衡 · 单腿抬膝一臂下压', '单腿支撑，另一腿屈膝抬起，一臂向斜下方压', 'balancing on one leg with the other knee raised and one arm pressing down diagonally')
add(123, '站立 · 单臂上举交叉腿', '双腿交叉站立，一臂屈肘举到头后上方', 'standing with the legs crossed and one arm bent and lifted up behind the head')
add(124, '弓步 · 大跨步俯身展臂', '双腿大幅分开成弓步，上身向一侧俯倾，双臂向身后下方伸展', 'in a long wide lunge with the torso tilted to one side and both arms reaching back and down')
add(125, '站立 · 单臂上举平展', '正面站立，一臂斜向上举，另一臂向侧平举，双腿交叉', 'standing front-on with one arm raised diagonally and the other extended horizontally, legs crossed')
add(126, '站立 · 侧倾双臂下压', '身体向侧方倾斜，双臂同时向斜下方压', 'leaning the body sideways with both arms pressing down and outward on the same side')
add(127, '站立 · 抬腿垂臂', '单腿站立，另一条腿抬起，双臂自然垂在身体两侧', 'standing on one leg with the other leg lifted and both arms hanging relaxed at the sides')
add(128, '站立 · 双手肩上推举', '正面站立，双臂弯曲、双手举到肩部两侧向上推', 'standing front-on with both arms bent and the hands raised beside the shoulders in a press-up position')
add(129, '站立 · 双臂水平外展', '正面站立，双臂向两侧水平伸直张开', 'standing front-on with both arms extended straight out horizontally to the sides')
add(130, '平衡 · 单腿折叠双臂前伸', '单腿支撑，另一腿向后折叠抬起，双臂向前伸出', 'balancing on one leg with the other folded up behind and both arms reaching forward')
add(131, '奔跑 · 腾空屈腿摆臂', '向前腾空奔跑，一腿屈膝后提，双臂前后摆动', 'sprinting forward into the air with one leg bent and lifted behind and the arms swinging fore and aft')
add(132, '行走 · 单臂上举侧展', '向前行走，一臂向斜上方举起，另一臂向侧方摆开', 'walking forward with one arm raised diagonally up and the other arm swung out to the side')
add(133, '站立 · 双掌下按身前', '正面站立，双肘弯曲，双手在身前向下按压', 'standing front-on with both elbows bent and the palms pressing downward in front of the body')
add(134, '站立 · 双臂前推', '正面站立，双臂向正前方平行推出', 'standing front-on with both arms pushing straight out in front of the body')
add(135, '平衡 · 单腿站立单臂直举', '单腿站立支撑，另一条腿抬起贴地，一臂向上直举', 'standing on one leg with the other lifted close to the ground and one arm extended straight up')
add(136, '行走 · 抬手前行', '正面向前行走，一臂屈肘抬到胸前，另一臂自然摆动', 'walking forward with one arm bent and lifted to chest height while the other arm swings naturally')
add(137, '站立 · 屈臂仰头叉腰', '一臂屈肘举到头后、头略后仰，另一手叉腰', 'with one arm bent and raised behind the head, the chin tipped back and the other hand on the hip')
add(138, '站立 · 侧身一手叉腰', '侧身站立，一手叉腰，另一臂垂在体侧，双腿错开', 'standing turned to the side with one hand on the hip, the other arm hanging down and the feet staggered')
add(139, '站立 · 仰头单臂上举', '身体略后仰，头抬起，一臂向侧上方高举', 'leaning slightly back with the head tilted up and one arm raised high to the side')
add(140, '行走 · 双臂展平', '行走向前，双臂向两侧平展打开', 'walking forward with both arms opened out flat to the sides')
add(141, '平衡 · 单腿折叠双臂下压', '单腿站立，另一腿弯折抬起，双臂向斜下方压', 'standing on one leg with the other bent and lifted while both arms press down and outward')
add(142, '平衡 · 抬腿双臂展', '单腿站立，另一腿向后抬起，双臂向两侧展开保持平衡', 'balancing on one leg with the other extended behind and both arms spread out to the sides')
add(143, '深蹲 · 蹲低单臂外伸', '极低蹲姿，一腿深屈，一臂向侧方伸出、另一手触地', 'in a very deep crouch with one leg fully bent, one arm reaching out to the side and the other hand near the floor')
add(144, '站立 · 单手抚额侧立', '侧身站立，一只手抬起横在额前，另一臂向下方伸出', 'standing turned to the side with one hand raised across the forehead and the other arm reaching down')
add(145, '站立 · 背身单臂高举', '背对镜头站立，一臂伸直高举过头顶', 'standing with the back to the viewer and one arm extended straight up overhead')
add(146, '平衡 · 交腿双臂环胸前', '双腿交叉站立，双臂在胸前交叠成环', 'standing with the legs crossed and both arms folded into a rounded shape across the chest')
add(147, '站立 · 搭肩含胸', '一臂横过胸前搭在肩侧，身体微微含胸', 'with one arm crossing the chest to rest on the shoulder and the upper body slightly rounded forward')
add(148, '站立 · 单臂上举开步', '双腿分开站立，一臂向上直举，头转向一侧', 'standing with the feet apart and one arm extended straight up, the head turned to one side')
add(149, '站立 · 双臂上举成V', '正面站立，双腿交叉，双臂向斜上方张开成V形', 'standing front-on with the legs crossed and both arms opened into a wide v shape overhead')
add(150, '站立 · 单臂高举交叉腿', '双腿交叉站立，一臂高举过头顶', 'standing with the legs crossed and one arm raised high above the head')
add(151, '俯身 · 一手叉腰一手下垂', '上身向前俯倾，一手叉腰，另一臂向下垂落', 'leaning the torso forward with one hand on the hip and the other arm hanging down')
add(152, '平衡 · 单腿抬起双臂侧展', '单腿站立，另一条腿屈膝抬起，双臂向两侧斜上方展开', 'balancing on one leg with the other knee lifted and both arms spread diagonally upward to the sides')
add(153, '倒立 · 单臂支撑分腿', '单手撑地倒立身体，另一臂张开，双腿向两侧分开', 'inverted on one hand with the other arm opened out and the legs spread wide apart')
add(154, '前屈 · 双手垂下拱背', '从髋部向前深弯，双臂松垂向下，背部拱起', 'folding forward deeply from the hips with the arms hanging loose and the back rounded')
add(155, '俯卧 · 单腿后踢', '俯卧在垫上，双臂撑地，一条腿向上后踢', 'lying prone with both arms braced on the floor and one leg kicked up behind')
add(156, '四足跪 · 单腿后抬', '四足着地爬姿，一条后腿向上抬起', 'on all fours with one hind leg lifted up behind the body')
add(157, '深蹲 · 俯身双手撑地', '深蹲前倾，双手撑在地面上，抬头看前方', 'in a deep forward squat with both hands planted on the floor and the head lifted looking ahead')
add(158, '低蹲 · 双手垂地侧身', '低身下蹲身体侧转，双手垂向地面', 'crouching low with the body turned to the side and both hands reaching down toward the ground')
add(159, '深蹲 · 单手撑地侧撑', '深蹲并以一只手撑地，另一臂向侧上方伸出', 'in a deep squat braced on one hand with the other arm extended up and to the side')
add(160, '跳跃 · 屈腿展臂', '腾空跃起，双腿一前一后屈曲，双臂分别斜向上方和侧前方张开', 'mid-leap with both knees bent and the legs trailing, one arm reaching up-diagonally and the other opening forward')
add(161, '站立 · 单臂高举抬腿', '单腿支撑站立，另一条腿屈膝抬起，一只手直举过头', 'balancing on one leg with the other knee lifted, one arm reaching straight overhead')
add(162, '站立 · 单臂侧平举', '双脚分开站立，一只手向侧前方水平伸出，另一只手垂在身侧', 'standing with feet apart, one arm extended horizontally to the side and the other hanging down')
add(163, '弓步 · 屈臂后撤', '前腿屈膝弓步，后腿屈膝后撤，一只手屈肘举到肩侧', 'in a crouched lunge with the front knee bent and the rear knee tucked under, one arm flexed up beside the shoulder')
add(164, '站立 · 双腿开立展臂', '双腿大幅分开站立，一臂斜举过头，另一臂向侧方平伸', 'standing in a wide straddle, one arm lifted diagonally overhead and the other stretched out sideways')
add(165, '站立 · 抬膝勾手', '单腿站立，另一条腿屈膝抬到髋部高度，一手向下勾指', 'standing on one leg with the other knee raised to hip height, one hand reaching downward with fingers curled')
add(166, '坐地 · 屈腿后撑', '坐在地面上双腿屈曲折叠，一手撑在身后支撑上身', 'seated on the floor with both legs folded, one hand planted behind to prop up the torso')
add(167, '站立 · 高侧踢', '单腿支撑，另一条腿向侧上方高高踢出，一臂上指一手下垂', 'standing on one leg while kicking the other leg high out to the side, one arm pointing up and the other hanging down')
add(168, '半跪 · 交臂前伸', '后腿跪地前腿屈膝，双臂在身前交叠向前伸出', 'kneeling on the rear knee with the front knee bent, both arms crossed and extended forward in front of the chest')
add(169, '半跪 · 单臂上举后展', '半跪跪姿，双膝分开落地，一臂高举过头，另一臂向侧后伸展，上身后仰', 'kneeling with the knees apart, one arm raised overhead and the other extended out behind, torso leaning back')
add(170, '半跪 · 屈臂上撑', '后腿跪地，一只手屈肘向上撑起，另一只手向前下方按落', 'kneeling on the rear leg, one arm propped upward with a bent elbow and the other pressing down and forward')
add(171, '站立 · 单臂上扬侧倾', '站立时上身向一侧倾斜，一只手斜举过头顶，另一只手向侧前方伸出', 'standing with the torso tilted to one side, one arm raised diagonally overhead and the other reaching out to the front side')
add(172, '平衡 · 展体侧倾', '单腿支撑，另一条腿向后侧抬起，双臂水平展开，上身前倾', 'balancing on one leg with the other leg swept back and out, both arms spread horizontally as the torso tips forward')
add(173, '跳跃 · 屈膝扬臂', '腾空时一腿屈膝抬起，一只手屈肘举过头顶，另一只手向后拉开', 'airborne with one knee raised high, one arm flexed above the head and the other pulled back behind the body')
add(174, '站立 · 侧举屈臂', '双腿分开站立，一只手向侧方平举，另一只手屈肘弯到肩上', 'standing with the legs apart, one arm extended out to the side and the other flexed up near the shoulder')
add(175, '平衡 · 侧举腿', '单腿站立，另一条腿向侧后方向斜举，一只手向上伸出', 'balancing on one leg while lifting the other leg diagonally out and back, one arm reaching upward')
add(176, '站立 · 双手抱头', '双脚分开站立，双手都放到后脑上，肘部向两侧张开', 'standing with feet apart and both hands resting behind the head, elbows flared out to the sides')
add(177, '站立 · 单臂绕头', '双腿开立，一只手绕到头顶上方，另一只手向下伸向大腿', 'standing with legs apart, one arm curved over the top of the head and the other reaching down toward the thigh')
add(178, '站立 · 双拳上举', '侧身站立，双拳屈肘举到肩部两侧，一腿微微弯起', 'standing in a slight turn with both fists flexed up beside the shoulders and one leg lightly bent')
add(179, '深蹲 · 俯首按膝', '深蹲屈膝，双臂向前下方伸出，双手按住大腿，视线向下', 'in a deep squat with both arms reaching forward to press the thighs, head angled down toward the knees')
add(180, '半跪 · 单臂上指', '后腿跪地前腿屈起，一只手伸直向上指，另一只手撑在前腿上', 'kneeling on the rear knee with the front leg bent, one arm reaching straight up and the other resting on the raised thigh')
add(181, '半跪 · 挥臂上举', '后腿跪地，身体侧转，一只手握拳高举过头', 'kneeling on one knee with the torso turned sideways, one fist raised high above the head')
add(182, '站立 · 前倾指天', '双脚分开站立，上身前倾，一只手举起在脸旁竖起手指', 'standing with feet apart and the torso leaning forward, one hand lifted beside the face with fingers raised')
add(183, '站立 · 抱臂侧倾', '双腿交叉站立，一只手横抱在胸前，另一只手垂落，上身微侧', 'standing with the legs crossed, one arm folded across the chest and the other hanging down, torso angled slightly')
add(184, '站立 · 单臂过头', '单腿站立，另一条腿屈膝后勾，一只手弯过头顶，另一只手向下', 'standing on one leg with the other knee bent and hooked behind, one arm curving over the head and the other reaching down')
add(185, '站立 · 侧身抚颌', '侧身站立，一手抬到下颌处轻托，另一只手横在腰前', 'standing in profile with one hand raised to the chin and the other held across in front of the waist')
add(186, '站立 · 提膝举拳', '单腿支撑，另一条腿屈膝抬到腰际，一只手握拳举到肩前', 'balancing on one leg with the other knee lifted to waist level, one fist held up in front of the shoulder')
add(187, '侧弓步 · 展臂斜伸', '双腿大幅分开侧向跨步，一只手斜举过头，另一只手向体侧下垂', 'in a wide side lunge with one arm reaching diagonally overhead and the other dropping toward the hip')
add(188, '跳跃 · 单臂上冲', '双脚离地跃起，一只手握拳向上冲出，双腿一前一后屈起', 'leaping off the ground with one fist punching upward and both legs tucked, one forward and one back')
add(189, '平衡 · 后踢展臂', '单腿站立，另一条腿向后屈起，一只手向前伸出，另一只手向后拉开', 'balancing on one leg with the other bent behind, one arm reaching forward and the other pulled back')
add(190, '手撑倒立 · 直腿侧分', '一手撑地倒立，一条腿竖直向上，另一条腿向侧方伸直打开', 'in a one-handed handstand with one leg straight up and the other leg opened straight out to the side')
add(191, '站立 · 叉腰交腿', '双腿交叉站立，一手叉腰，另一只手横在腹前', 'standing with the legs crossed, one hand on the hip and the other resting across the front of the belly')
add(192, '坐地 · 单臂上撑', '坐在地面上双腿屈起，一只手撑地，另一只手向上伸出', 'seated on the ground with both knees bent, one hand braced behind and the other arm reaching up')
add(193, '行走 · 摆臂迈步', '双腿前后跨步站立，一只手屈肘摆到肩侧，另一只手自然后摆', 'standing mid-stride with the legs apart, one arm swung up beside the shoulder and the other trailing behind')
add(194, '站立 · 扶后脑侧身', '侧身站立，一手扶住后脑勺，另一只手搭在体侧', 'standing in profile with one hand resting on the back of the head and the other arm down at the side')
add(195, '站立 · 仰身扶发', '双腿交叉站立，双手抬到头顶撩起头发，肩部后展', 'standing with the legs crossed and both hands lifted into the hair, shoulders drawn back and the chest lifted')
add(196, '站立 · 交腿掩面', '单腿站立，另一条腿的脚踝交叉到支撑腿前，一手举到脸侧', 'standing on one leg with the other ankle crossed in front, one hand raised beside the face')
add(197, '背面 · 双臂展V字', '背对镜头站立，双臂向斜上方张开成V字，双腿并拢', 'seen from behind with both arms raised diagonally in a wide V and the legs together')
add(198, '站立 · 单臂上举侧展', '侧身站立，一臂高举过头，另一臂向侧后方展开，重心偏一侧', 'standing with the feet apart, one arm raised overhead and the other extended out behind, weight shifted to one side')
add(199, '行走 · 单手叉腰', '迈步向前，一手叉腰，另一只手向身后摆，双腿前后交错', 'stepping forward with one hand on the hip and the other arm swung behind, legs staggered forward and back')
add(200, '站立 · 双臂屈举', '双脚分开站立，双臂屈肘弯举到肩部两侧，前臂向上', 'standing with feet apart and both arms flexed upward beside the shoulders with the forearms raised')
add(201, '站立 · 交腿双臂过头', '单腿站立，另一条腿屈膝交叉到支撑腿前，双臂在头顶交叠', 'standing on one leg with the other knee crossed in front, both arms crossed and lifted overhead')
add(202, '站立 · 抬膝绕臂', '单腿支撑，另一条腿屈膝抬起，一只手弯过头顶，另一只手向下', 'balancing on one leg with the other knee raised, one arm curving over the head and the other reaching down')
add(203, '站立 · 正面叉腰', '正面站立，双腿分开，一手叉腰，另一只手垂在腿侧', 'facing forward with the legs apart, one hand on the hip and the other arm hanging by the thigh')
add(204, '站立 · 抬腿曲臂', '单腿支撑，另一条腿向后屈起，一手抬到脸旁，另一手屈肘向外', 'balancing on one leg with the other bent up behind, one hand raised beside the face and the other arm flexed outward')
add(205, '站立 · 直腿侧踢', '单腿站立，另一条腿向侧方伸直踢出，一手抬到下巴处', 'standing on one leg while extending the other straight out to the side, one hand lifted to the chin')
add(206, '平衡 · 弯腿后勾', '单腿支撑，另一条腿屈膝向上后勾，双臂屈起挡在脸前', 'balancing on one leg with the other leg bent and hooked up behind, both arms flexed up in front of the face')
add(207, '蹲姿 · 单手撑地抬腿', '低蹲成球形，一手撑地，另一腿向上弯折抬起', 'in a deep tuck squat with one hand on the ground and the other leg bent and lifted upward')
add(208, '侧卧 · 屈肘撑身', '侧身卧地，一只手屈肘撑起上身，另一条腿向上屈起', 'lying on the side propped up on one elbow, the other leg bent and raised above the hip')
add(209, '坐地 · 单腿竖起', '坐地一腿伸直，另一条腿竖直向上，一只手在身后撑地', 'seated on the floor with one leg extended and the other raised straight up, one hand braced behind')
add(210, '俯身 · 前倾展臂', '身体几乎水平前倾，双臂向后展开，双腿伸直支撑', 'with the torso tipped almost horizontal forward, both arms stretched back behind and the legs straight')
add(211, '蹲跳 · 后伸手臂', '屈膝腾空起跳，一只手向侧前方伸出，另一只手向后拉开', 'springing up from bent knees with one arm reaching forward to the side and the other pulled back')
add(212, '手撑 · 侧翻抬腿', '一手撑地，身体侧向翻转成横姿，一条腿向后上方弯起', 'supported on one hand with the body rotated sideways into a horizontal line and one leg bent upward behind')
add(213, '前屈 · 双手够脚踝', '上身前屈，双膝微屈，双手向下伸到脚踝处', 'folded forward at the hips with the knees slightly bent and both hands reaching down to the ankles')
add(214, '站立 · 单手后脑叉腰', '侧身站立，一手扶住后脑，另一只手叉在腰上', 'standing in profile with one hand on the back of the head and the other hand on the waist')
add(215, '半蹲 · 单手掩口', '半蹲屈膝，一只手抬到嘴边，另一只手向下伸出', 'in a half squat with one hand raised to the mouth and the other arm reaching down')
add(216, '站立 · 交臂并腿', '双腿交叉站立，双臂在身前交叠环抱，肩部内收', 'standing with the legs crossed and both arms folded around each other in front of the chest')
add(217, '站立 · 叉腰侧首', '双腿分开站立，一手叉腰，另一只手抬起靠近脸侧，头转向一侧', 'standing with legs apart, one hand on the hip and the other raised near the face with the head turned to one side')
add(218, '站立 · 平举横臂', '站立时一只手臂横在胸前水平伸出，另一只手垂在身侧', 'standing with one arm held horizontally across the chest and the other arm relaxed at the side')
add(219, '跳跃 · 后仰甩臂', '腾空后仰，一只手弯过头顶向后甩，双腿一前一后抬离地面', 'leaping with the torso arched back, one arm flung up and over behind the head and both legs lifted clear of the ground')
add(220, '深蹲 · 抱膝低头', '深蹲成蹲踞，双臂环抱小腿，头部低垂贴近膝盖', 'in a deep squat hugging the shins with both arms wrapped around the legs and the head bowed to the knees')
add(221, '后弯 · 单臂撑展', '身体后仰成弓形，一只手向上伸出撑开，另一只手向腿侧伸展', 'arching the torso backward into a bow shape with one arm reaching up and the other stretching toward the leg')
add(222, '站立 · 掩口叉腰', '正面站立，一手抬到嘴前，另一只手叉腰', 'standing facing forward with one hand raised in front of the mouth and the other hand on the hip')
add(223, '站立 · 单臂绕头侧身', '侧身站立，一只手弯过头顶向下，另一只手横在身前', 'standing in profile with one arm curving over the head and the other held across the front of the body')
add(224, '蹲姿 · 屈臂抬膝', '低蹲成团，一手屈肘举到头顶，另一手向下撑地，膝部抬起', 'in a low tuck squat with one arm flexed above the head and the other bracing down, a knee lifted high')
add(225, '行走 · 掩面迈步', '双腿前后交叠迈步，一手抬到脸旁，另一手垂在体侧', 'walking with the legs crossed in a staggered step, one hand raised beside the face and the other at the side')
add(226, '弓步 · 单拳上举侧身', '前腿屈膝大弓步后腿伸直，一只手握拳举到肩侧，身体侧转', 'in a deep lunge with the front knee bent and back leg straight, one fist raised beside the shoulder as the torso turns sideways')
add(227, '弓步 · 屈臂开肩', '大幅弓步双腿分开，一手屈肘弯举在头侧，另一手向下伸出', 'in a wide lunge with one arm flexed up beside the head and the other reaching down toward the floor')
add(228, '站立 · 上指转身', '双腿分开站立，一手横在胸前，另一只手高举竖起手指', 'standing with the legs apart, one hand held across the chest and the other raised high with the fingers pointing up')
add(229, '平衡 · 屈腿后举臂', '单腿支撑，另一条腿屈膝在身后勾起，一只手举过头顶上方', 'balancing on one leg with the other hooked up behind at the knee, one arm lifted above the head')
add(230, '手撑倒立 · 分腿展臂', '单手撑地倒立，双腿向两侧分开呈剪刀状，一手向上伸展', 'in a one-handed handstand with the legs scissored apart to the sides and one arm extended upward')
add(231, '跳跃 · 水平俯冲', '身体腾空成水平俯冲姿态，双臂向前方伸出，双腿向后绷直', 'airborne in a horizontal diving position with both arms reaching forward and both legs extended straight back')
add(232, '站立 · 双臂合掌', '单腿支撑，另一条腿向后屈起，双手在头顶合拢相贴', 'balancing on one leg with the other bent behind, both hands pressed together above the head')
add(233, '跳跃 · 前伸探身', '腾空屈膝，双臂一前一后伸向前方探出，躯干前倾', 'airborne with the knees bent and both arms reaching forward in succession as the torso tips ahead')
add(234, '站立 · 直臂举天', '双腿分开站立，一只手直臂举向天顶，另一只手屈肘放在胸前', 'standing with the legs apart, one arm stretched straight up toward the sky and the other flexed across the chest')
add(235, '后仰 · 屈臂后靠', '上身后仰头部后仰，一只手屈肘举在肩侧，双腿前后错开屈膝', 'leaning back with the head tipped behind and one arm flexed beside the shoulder, both knees bent in a staggered stance')
add(236, '站立 · 单手上举叉腰', '双腿分开站立，一只手举过头顶，另一只手叉在腰上', 'standing with the legs apart, one arm raised overhead and the other hand resting on the hip')
add(237, '站立 · 举臂侧展', '双脚分开站立，一只手屈肘举高，另一只手向侧下方伸展', 'standing with the feet apart, one arm flexed and raised high and the other extended down and out to the side')
add(238, '行走 · 掌心前推', '侧身迈步，一手在腰侧，另一只手向前伸出掌心朝上，头部侧倾', 'stepping sideways with one hand at the waist and the other extended forward palm up, head tilted to one side')
add(239, '平衡 · 侧举摆臂', '单腿支撑，另一条腿在身后屈起，一只手向斜上方摆出', 'balancing on one leg with the other bent up behind, one arm swung out diagonally upward')
add(240, '站立 · 交叉双腿', '正面站立，双腿在脚踝处交叉，双臂垂在身体两侧', 'standing facing forward with the ankles crossed and both arms hanging loosely at the sides')
add(241, '站立 · 侧胯站姿', '侧身站立，一手叉腰，双腿一前一后交叠，身体重心落在一侧髋部', 'standing in profile with one hand on the hip, legs overlapped and the weight settled onto one hip')
add(242, '站立 · 侧平举绕臂', '双腿交叉站立，一只手水平伸向侧方，另一只手弯过头顶', 'standing with the legs crossed, one arm extended horizontally to the side and the other curved over the head')
add(243, '后仰 · 双臂后展', '上身后仰头后仰，双臂向身体后方展开，一腿屈起', 'leaning the torso back with the head dropped behind and both arms opened out behind the body, one leg bent')
add(244, '站立 · 侧身抚发', '侧身站立，一手绕到脑后撩住头发，另一只手垂在体侧', 'standing in profile with one hand reaching behind the head into the hair and the other arm down at the side')
add(245, '站立 · 对角展臂', '双腿分开站立，一只手斜举向头顶上方，另一只手向另一侧斜下方伸展', 'standing with the legs apart, one arm reaching diagonally up and the other stretching diagonally down to the opposite side')
add(246, '弓步 · 侧向开臂', '前腿屈膝弓步，上身侧转，一手抬到脸旁，另一手向侧方张开', 'in a lunge with the front knee bent and the torso turned, one hand raised beside the face and the other opened out to the side')
add(247, '站立 · 屈臂叉腰', '双腿分开站立，一手叉腰，另一只手屈肘弯过头顶', 'standing with the legs apart, one hand on the hip and the other arm flexed up over the head')
add(248, '侧倾 · 单腿侧抬', '身体向一侧倾斜，一条腿向侧方抬起，双臂向下垂展', 'tipping the torso to one side while lifting a leg out to the side, both arms hanging and extended downward')
add(249, '跪坐 · 双手前伸', '跪坐在脚跟上，双臂向前下方伸出，双手靠向地面', 'kneeling back on the heels with both arms reaching forward and down toward the ground')
add(250, '站立 · 双臂直举', '正面站立，双腿并拢，双臂贴耳直直举过头顶', 'standing facing forward with the legs together and both arms raised straight up close to the ears')
add(251, '坐姿 · 单臂上举', '低坐屈膝，一手撑地支撑，另一只手向上举起', 'seated low with the knees bent, one hand bracing on the ground and the other arm raised upward')
add(252, '半跪 · 斜举手臂', '半跪在地，一只手向斜上方举起，另一只手在胸前屈起', 'kneeling on one knee with one arm raised diagonally upward and the other flexed in front of the chest')
add(253, '站立 · 单臂上举框形', '双腿分开站立，一只手臂向上直举，另一只手屈肘扶在头侧', 'standing with the legs apart, one arm raised straight up and the other bent with the hand resting beside the head')
add(254, '侧卧 · 屈腿抬脚', '侧身卧地，一腿向上屈起抬高手臂撑起上身，另一腿伸直', 'lying on the side with one leg bent and lifted high, propped on one arm, the other leg extended straight')
add(255, '平衡 · 单腿侧开', '单腿支撑，另一条腿向侧方伸直打开，一只手竖直举过头顶', 'balancing on one leg while extending the other straight out to the side, one arm raised vertically overhead')
add(256, '弓步 · 单臂上引', '大幅弓步双腿分开，一只手向上斜举引展，另一只手向下按落', 'in a wide lunge with one arm reaching diagonally up and the other pressing down toward the floor')
add(257, '弓步 · 反弓展臂', '前腿深屈弓步，一手绕过头顶向后展开，头部向后上方仰起', 'in a deep lunge with one arm curved back over the head and the chin lifted to look up behind')
add(258, '平衡 · 抬膝开臂', '单腿支撑，另一条腿屈膝抬起，一手向上举高，一手向侧方张开', 'balancing on one leg with the other knee lifted, one arm raised high and the other opened out to the side')
add(259, '后弯 · 提腿翻仰', '上半身向后翻转，一条腿向上抬起，手臂向上牵引身体', 'flipping the torso backward with one leg lifted upward and an arm reaching up to pull the body through')
add(260, '平衡 · 抬腿开臂', '单腿支撑，另一条腿屈膝压在支撑腿内侧，一只手举高一手侧平', 'balancing on one leg with the other knee bent against the inside of the standing leg, one arm raised and the other level')
add(261, '平衡 · 交叉腿举臂', '单腿站立，另一条腿的脚背贴在支撑腿小腿上，一只手举过头顶', 'standing on one leg with the other foot resting against the calf, one arm raised above the head')
add(262, '平衡 · 双臂过头', '单腿支撑，另一条腿向后屈起，双臂在头顶弯成弧线', 'balancing on one leg with the other bent behind, both arms curved overhead into an arc')
add(263, '站立 · 环臂绕头', '双腿前后错步站立，双臂在头部上方交环绕成圆环', 'standing with the legs staggered, both arms circling and crossing above the head to form a ring')
add(264, '弓步 · 双手交叠头上', '大弓步前腿屈膝，双臂抬起在头顶交叠，肘部向两侧打开', 'in a wide lunge with the front knee bent, both arms lifted and crossed above the head with the elbows flared out')
add(265, '平衡 · 抬膝举手', '单腿支撑，另一条腿屈膝抬起，双臂在头顶交叠成菱形', 'balancing on one leg with the other knee raised, both arms crossed overhead forming a diamond shape')
add(266, '侧弯腰 · 单臂上展', '双腿分开站立，上身向一侧弯倾，一只手向斜上方伸展，另一只手下滑到腿侧', 'standing with legs apart and the torso bent sideways, one arm reaching diagonally up and the other sliding down the leg')
add(267, '平衡 · 展体后伸', '单腿支撑，另一条腿向后伸直抬起，双臂向两侧展开', 'balancing on one leg with the other extended straight back, both arms spread out to the sides')
add(268, '平衡 · 侧展抱头', '单腿站立，另一条腿屈膝在身前交叠，一手抱头一手向侧伸展', 'standing on one leg with the other knee bent and crossed in front, one hand on the head and the other extended sideways')
add(269, '前屈 · 单手够踝', '上身前屈，一手向下伸到脚踝，另一只手绕过头顶向后打开', 'folded forward with one hand reaching down to the ankle and the other arm curving back over the head')
add(270, '站立 · 双臂开肩', '双腿大幅分开站立，双臂向两侧水平打开，头部转向一侧', 'standing in a wide straddle with both arms opened horizontally to the sides and the head turned to one side')
add(271, '跳跃 · 跨步飞身', '腾空跨步，一手向上举起，另一手向侧方伸展，双腿前后分开', 'leaping through the air with one arm raised and the other stretched sideways, the legs split front and back')
add(272, '半跪 · 托腮侧身', '后腿跪地，一手抬到下巴处，另一手叉在腰上，上身侧转', 'kneeling on the rear knee with one hand raised to the chin and the other on the hip, torso turned sideways')
add(273, '跪姿 · 双手上举', '跪姿屈膝，双臂在头顶交叠上举，一侧脚跟抬起', 'kneeling with the knees bent and both arms crossed and raised overhead, one heel lifted')
add(274, '平衡 · 提膝摆手', '单腿支撑，另一条腿屈膝抬起，一手向前伸出，另一手向后摆', 'balancing on one leg with the other knee lifted, one arm reaching forward and the other swinging back')
add(275, '蹲姿 · 前伸手臂', '低蹲屈膝，双臂向正前方伸出，手掌相对靠拢', 'in a low squat with both arms extended forward, the palms facing each other and held close')
add(276, '蹲姿 · 单手撑地', '蹲成低姿，一手撑地，另一条腿向侧后抬起，手臂向外打开', 'in a low crouch with one hand braced on the ground and the opposite leg lifted out to the back and the arm opened wide')
add(277, '蹲姿 · 双手下探', '深蹲屈膝，双臂向前下方伸直探出，头部抬起看向前方', 'in a deep squat with both arms reaching straight forward and down while the head lifts to look ahead')
add(278, '平衡 · 前举后平臂', '单腿支撑，另一条腿在身后屈起，一手高举过头，另一手向侧后平伸', 'balancing on one leg with the other bent up behind, one arm raised overhead and the other extended level behind')
add(279, '舞蹈 · 单臂划弧', '单腿站立，另一条腿屈膝抬起，一只手向斜上方划出弧线', 'standing on one leg with the other knee raised, one arm sweeping an arc diagonally upward')
add(280, '弓步 · 单臂上举', '前腿屈膝弓步，一只手直臂举过头顶，另一只手向侧方伸出', 'in a lunge with the front knee bent, one arm stretched straight overhead and the other extended out to the side')
add(281, '站立 · 叉腰举拳', '双腿分开站立，一手叉腰，另一只手握拳举到肩侧', 'standing with the legs apart, one hand on the hip and the other fist raised beside the shoulder')
add(282, '平衡 · 抬膝平举', '单腿支撑，另一条腿屈膝抬起，一手水平伸向前方，另一手扶在腰间', 'balancing on one leg with the other knee lifted, one arm extended level in front and the other hand at the waist')
add(283, '蹲姿 · 顶髋下撑', '屈膝深蹲，一手绕过头顶，另一手向下撑地，一条腿向外抬起', 'in a deep crouch with one arm curved over the head and the other pressing down to the ground, one leg lifted out to the side')
add(284, '站立 · 双腿开立举臂', '双腿大幅分开站立，一只手向上高举，另一只手垂在身侧', 'standing with the legs spread wide, one arm raised high overhead and the other hanging at the side')
add(285, '半蹲 · 屈臂展肩', '半蹲屈膝重心下沉，一只手屈肘举过头顶，另一只手向侧方抬起', 'in a half squat with the weight lowered, one arm flexed above the head and the other lifted out to the side')
add(286, '宽蹲 · 单臂平举', '双腿大幅分开屈膝下蹲，一只手水平平举，另一只手屈肘弯举', 'in a very wide squat with one arm extended horizontally and the other flexed upward beside the shoulder')
add(287, '半跪 · 单手上撑', '后腿跪地前腿屈起，一手向上举起，另一手扶在前膝上', 'kneeling on the rear knee with the front leg bent, one arm raised upward and the other hand resting on the front knee')
add(288, '平衡 · 抬腿举臂', '单腿支撑，另一条腿向前抬起伸直，一只手举过头顶', 'balancing on one leg with the other lifted and extended straight forward, one arm raised overhead')
add(289, '半跪 · 侧举长弓', '后腿跪地后腿向后伸直，一只手向斜上方举起，躯干侧转打开', 'kneeling on one knee with the back leg extended straight behind, one arm raised diagonally upward and the torso rotated open')
add(290, '站立 · 举臂侧倾', '侧身站立，一只手向斜上方举起，上身向另一侧倾', 'standing in profile with one arm raised diagonally upward and the torso leaning to the opposite side')
add(291, '站立 · 举臂交叉腿', '双腿交叉站立，一手高举过头，另一只手扶在腰侧', 'standing with the legs crossed, one arm raised overhead and the other hand resting at the waist')
add(292, '跪姿 · 侧臂后仰', '跪坐后仰，一手向侧方伸出，另一手在胸前屈起，头部后仰', 'kneeling and leaning back with one arm extended to the side and the other flexed at the chest, head tipped behind')
add(293, '坐地 · 横叉开臂', '坐地双腿横向打开成横叉，一只手向上举起，另一只手向侧方伸出', 'seated on the floor in a wide side split with one arm raised and the other extended to the side')
add(294, '站立 · 双手扶髋', '正面站立，双腿分开，双手同时扶在两侧腰髋上', 'standing facing forward with the legs apart and both hands resting on the hips')
add(295, '平衡 · 深抬膝冠臂', '单腿支撑，脚尖踩稳，另一条腿屈膝抬到髋部，一手在头顶弯成半圆', 'balancing on one leg with the toes grounded, the other knee lifted to hip height and one arm arched into a half circle over the head')
add(296, '平衡 · 屈膝举臂', '单腿支撑，另一条腿在身后屈起，一手向上举起，一手向前伸出', 'balancing on one leg with the other bent up behind, one arm raised upward and the other extended forward')
add(297, '平衡 · 冠臂提膝', '单腿支撑，另一条腿屈膝抬起，一手在头顶弯成环形', 'balancing on one leg with the other knee raised, one arm curved into an arch over the head')
add(298, '站立 · 抱臂含胸', '双腿交叉站立，双臂环抱在胸前，肩部微微内含', 'standing with the legs crossed and both arms wrapped around the chest, shoulders drawn in slightly')
add(299, '站立 · 交叉腿叉腰', '正面站立，双腿交叉，一手叉腰，另一只手垂在体侧', 'standing facing forward with the legs crossed, one hand on the hip and the other arm down at the side')
add(300, '站立 · 屈臂摆动', '双腿分开站立，一只手屈肘弯在胸前，另一只手向侧下方摆出', 'standing with the legs apart, one arm flexed across the chest and the other swung out down and to the side')
add(301, '站立 · 掩面叉腰', '正面站立，一手抬到脸旁，另一手叉在腰上', 'standing facing forward with one hand raised beside the face and the other hand on the hip')
add(302, '前屈 · 双手背后', '上身前屈，双臂背到身后交握，双腿交叉站立', 'folded forward at the hips with both arms clasped behind the back and the legs crossed')
add(303, '平衡 · 抬腿弯臂', '单腿支撑，另一条腿屈膝抬起，一手弯过头顶，另一手垂在体侧', 'balancing on one leg with the other knee lifted, one arm curved over the head and the other hanging at the side')
add(304, '平衡 · 双臂展平', '单腿支撑，另一条腿在身后屈起，双臂向两侧水平展开', 'balancing on one leg with the other bent up behind, both arms extended horizontally to the sides')
add(305, '站立 · 扶头叉腰', '双腿分开站立，一手扶住后脑，另一只手叉在腰上', 'standing with the legs apart, one hand on the back of the head and the other on the hip')
add(306, '平衡 · 后踢屈臂', '单腿支撑，另一条腿向后伸直踢起，一只手屈肘举在肩前', 'balancing on one leg while kicking the other straight out behind, one arm flexed up in front of the shoulder')
add(307, '蹲姿 · 单臂绕头', '屈膝深蹲，一手弯过头顶向后，另一手向下伸出', 'in a deep squat with one arm curved back over the head and the other reaching down')
add(308, '站立 · 单臂后屈', '双腿分开站立，一只手臂屈肘向后弯到腰后，另一手垂在身侧', 'standing with the legs apart, one arm bent back behind the waist and the other hanging at the side')
add(309, '站立 · 侧展抱头', '侧身站立，一手抱头，另一只手向侧方平伸，一腿交叉', 'standing in profile with one hand on the head and the other extended level to the side, one leg crossed')
add(310, '蹲姿 · 侧伸抬腿', '屈膝半蹲，一手向侧方平伸，另一手向下撑地，一条腿外展抬起', 'in a half squat with one arm extended to the side and the other braced down, the opposite leg lifted out to the side')
add(311, '手撑倒立 · 单腿上冲', '单手撑地，一条腿竖直向上，另一条腿屈膝收拢在体侧', 'in a one-handed handstand with one leg punched straight up and the other bent and tucked close to the body')
add(312, '平衡 · 上举侧平臂', '单腿支撑，另一条腿在身后屈起，上身侧倾，一手向上举高，另一手向侧方展开', 'balancing on one leg with the other bent behind and the torso tilted sideways, one arm reaching up and the other opened out to the side')
add(313, '平衡 · 抬腿展臂', '单腿支撑，另一条腿向前抬起，双臂向两侧张开保持平衡', 'balancing on one leg with the other lifted forward, both arms opened out to the sides for balance')
add(314, '侧撑 · 前臂支撑', '侧身以前臂撑地，身体斜向撑起，一条腿向外伸直', 'propped on one forearm with the body held diagonally up and one leg extended straight out')
add(315, '深蹲 · 垂臂深蹲', '双脚踩实，双膝与髋部深屈，双手自然垂于两腿外侧，背部挺直', 'in a deep squat with both feet planted, knees and hips deeply bent, both arms hanging at the outside of the legs, back straight')
add(316, '前屈 · 单臂下探', '上身前屈几乎与地面平行，一只手向下伸向脚踝，另一只手向后打开', 'folded forward with the torso nearly parallel to the floor, one hand reaching down to the ankle and the other opened back')
add(317, '站立 · 侧倾伸臂', '双腿分开站立，上身向一侧弯倾，一只手向斜上方伸展', 'standing with the legs apart and the torso bent sideways, one arm reaching out diagonally upward')
add(318, '行走 · 双臂侧展', '双腿前后交错迈步，双臂向两侧微微展开保持平衡', 'stepping with the legs staggered and both arms opened slightly out to the sides for balance')
add(319, '站立 · 单手侧指', '侧身站立，一手向侧前方伸出指，另一只手垂在体侧，一腿交叉', 'standing in profile with one hand pointing out forward to the side and the other at the hip, one leg crossed')
add(320, '平衡 · 侧倾双腿腾空', '身体向侧方倾倒失去平衡，双臂向两侧甩开，双腿一前一后离地蜷起', 'tipping sideways off balance with both arms flung out and both legs lifted and curled off the ground')
add(321, '行走 · 交叉步侧身', '侧身向前行走，双腿前后交叉迈步，双臂沿身侧自然摆动', 'walking in profile with the legs crossing mid-stride and the arms swinging loose at the sides')
add(322, '站立 · 单臂高举挥动', '站直身体，一只手高举过头顶做出挥手动作，另一只手在胸前平举', 'standing upright with one arm raised high overhead in a wave and the other hand held flat in front of the chest')
add(323, '站立 · 双手抱头交踝', '双脚脚踝交叉站立，双手交叠抱在头顶上方', 'standing with the ankles crossed and both hands clasped together on top of the head')
add(324, '站立 · 单臂斜举握拳', '一腿微屈支撑，另一腿向侧后方点地，一臂斜向上举成拳', 'standing on one slightly bent leg with the other foot pointed to the side, one arm raised diagonally upward in a clenched fist')
add(325, '站立 · 双手掩面低头', '双脚并拢站直，低头的同时用双手遮住面部', 'standing with the feet together and the head bowed while both hands cover the face')
add(326, '深蹲 · 单臂上勾', '深蹲压低重心，一只手向上勾肘抬起，另一只手向地面下探', 'in a deep squat with the weight lowered, one arm hooked upward at the elbow and the other reaching down toward the floor')
add(327, '站立 · 单手抱头侧倚', '一手绕到脑后扶着颈后，另一手叉在腰间，躯干微微侧倾', 'standing with one hand behind the head and the other on the hip, the torso leaning slightly to the side')
add(328, '跪姿 · 双臂上举开胸', '单膝跪地成弓步，胸口打开，双臂向斜上方大幅张开', 'kneeling in a lunge with the front knee bent, the chest open and both arms raised wide overhead')
add(329, '深蹲 · 双臂前推', '蹲到最低点，双脚分开踩实，双臂同时向前上方推出，手掌朝外', 'squatting low with the feet planted apart and both arms pushed forward and upward, palms facing out')
add(330, '深蹲 · 抱腿团身', '低低蹲下蜷成一团，双臂环抱住小腿，额头靠近膝盖', 'curled into a compact low squat with both arms wrapped around the shins and the forehead close to the knees')
add(331, '地面 · 俯卧抬腿', '俯卧在地面上，双前臂撑地，一条腿向后高高抬起', 'lying prone on the ground, propped on both forearms, with one leg lifted high behind')
add(332, '站立 · 叉腰勾脚', '一手叉腰，另一条腿屈膝向后勾起脚跟，上身微微后仰', 'standing with one hand on the hip and the other leg bent so the heel lifts back toward the glutes, the torso tipped slightly back')
add(333, '站立 · 单臂前指', '一脚交叉到身前站稳，一手叉腰，另一只手向前平伸指出', 'standing with one foot crossed in front of the other, one hand on the hip and the other arm reaching straight out forward')
add(334, '站立 · 交臂点脚', '双臂在胸前交叠，上身直立，一只脚在身后轻轻点地', 'standing tall with both arms folded across the chest and one foot lightly pointed up behind')
add(335, '站立 · 抬膝侧展', '单腿站立，另一条腿屈膝向侧外打开，双手扶在髋部', 'balancing on one leg with the other knee opened out to the side and both hands resting on the hips')
add(336, '站立 · 叉腰伸腿仰头', '双手叉腰，一腿向前伸直绷脚，头部后仰看向斜上方', 'standing with both hands on the hips, one leg extended forward with a pointed foot and the head tipped back to look upward')
add(337, '站立 · 双手叉腰正面', '正面对镜头站直，双脚微分外展，双手同时撑在腰胯两侧', 'standing squarely facing the viewer with the feet slightly apart and both hands planted on the hips')
add(338, '站立 · 抚臂侧头', '身体略侧，一手扶髋，另一只手搭在对侧肩上，头向一侧偏转', 'standing slightly turned to the side with one hand on the hip and the other hand resting on the opposite shoulder, head tilted away')
add(339, '站立 · 双指上指', '双脚分开站定，双肘弯曲抬起，双手食指同时朝上指出', 'standing with the feet apart, both elbows bent and raised, and both index fingers pointing straight up')
add(340, '行走 · 交叉步垂臂', '正面迈步行走，双腿交替交叉，双臂垂在身侧微微后摆', 'walking toward the viewer with the legs crossing in front of each other and the arms hanging back at the sides')
add(341, '弓步 · 屈膝侧身', '一腿向前屈膝成弓步，另一腿蹬地伸直，躯干侧转，双臂自然摆动', 'in a lunge with the front knee bent and the back leg extended straight, the torso turned to the side and the arms loose')
add(342, '站立 · 屈臂后仰', '双脚平行站立，双臂屈肘抬到腰侧，胸部向后挺起', 'standing with the feet parallel, both elbows bent at the waist and the chest pushed back')
add(343, '站立 · 双腕交于颌前', '侧身站立，双腕在身体前方交叠抬起至下巴位置', 'standing in profile with both wrists crossed and lifted up in front of the body to chin height')
add(344, '站立 · 双臂屈肘上扬', '双脚微分站立，双臂向上弯曲抬起，两手在头顶上方张开', 'standing with the feet slightly apart, both arms raised and bent so the hands open above the head')
add(345, '舞蹈 · 提膝摆臂', '一腿提起屈膝，另一腿支撑，双臂一前一后摆动，身体上下起伏', 'dancing with one knee lifted and the other leg supporting, the arms swinging one in front of the other')
add(346, '站立 · 前倾迈步', '躯干前倾，重心落在前移的腿上，双臂自然下垂随步伐摆动', 'leaning the torso forward over the advancing leg with both arms hanging down and swinging with the step')
add(347, '站立 · 抚额侧身', '侧身站立，一手抬起按在额头前，另一手叉腰，双腿前后分开', 'standing in profile with one hand pressed to the forehead and the other on the hip, the feet staggered apart')
add(348, '站立 · 勾脚叉腰', '一腿支撑，另一条腿屈膝勾起脚尖，一手叉腰，另一手随身前摆', 'standing on one leg with the other knee bent and the toe pointed up, one hand on the hip while the other arm swings forward')
add(349, '行走 · 侧步回望', '侧身横向迈出一步，头扭向后方回望，双臂一前一后自然摆动', 'stepping sideways while the head twists back to look behind, the arms swinging front and back')
add(350, '奔跑 · 后撤步回身', '身体向后撤步扭转，一手向后甩臂，头部回转向后', 'twisting the body in a backward retreating step with one arm flung behind and the head turned back')
add(351, '弓步 · 大步侧压', '大步分开成宽弓步，前腿屈膝后腿绷直，一手叉腰并向侧面推出', 'in a wide striding lunge with the front knee bent and the back leg straight, one hand on the hip pressing out to the side')
add(352, '舞蹈 · 侧踢腿', '单腿支撑，另一条腿向斜侧高高踢出，支撑臂上举、踢腿臂下摆', 'balancing on one leg while the other leg kicks high out to the side, the supporting arm raised and the kicking arm lowered')
add(353, '舞蹈 · 腾空后仰', '双腿腾空离地，身体向后仰起，双臂一前一后大幅展开', 'airborne with both feet off the ground, the torso arched backward and both arms spread wide')
add(354, '舞蹈 · 抬膝勾手', '一腿屈膝抬起，支撑腿微蹲，双臂弯肘在胸前勾手上抬', 'dancing with one knee lifted and the supporting leg in a slight squat, both arms bent at the elbows and hooked upward in front of the chest')
add(355, '舞蹈 · 单腿展臂', '单腿站立，另一腿屈膝向外打开，双臂一高一低向两侧展开', 'balancing on one leg with the other knee opened out, both arms extended to the sides at different heights')
add(356, '站立 · 侧身合掌前伸', '侧身站立，双掌在胸前合拢并向前推出，颈部后仰', 'standing in profile with both palms pressed together and pushed out in front of the chest, the neck tilted back')
add(357, '站立 · 屈臂举拳', '正面站定，双臂屈肘举到肩侧，两手握拳，肘部向外撑开', 'facing forward with both arms bent up beside the shoulders, hands clenched into fists and elbows flared outward')
add(358, '站立 · 拄杖侧倚', '一只手拄着直立的杆杖辅助支撑，身体重心侧压在同侧腿上', 'leaning sideways with one hand resting on a tall upright pole for support, the weight on the same-side leg')
add(359, '武术 · 持剑侧举', '双手握住长剑横举在胸前，身体侧向站立，双腿前后分立', 'holding a longsword with both hands across the front of the chest, the body in profile with the feet staggered')
add(360, '武术 · 持枪弓步刺', '双手握长枪向前下方刺出，前腿屈膝成弓步，后腿蹬直', 'thrusting a long spear forward and downward with both hands, the front leg bent in a lunge and the back leg straight')
add(361, '武术 · 双手握棍下压', '双手握长棍斜向下压，双腿左右分开微蹲，躯干侧对前方', 'pressing a long staff downward at an angle with both hands, the feet apart in a slight squat and the body turned sideways')
add(362, '行走 · 屈臂含胸', '低头含胸向前行走，双臂屈肘收在躯干两侧', 'walking forward with the head down and the chest rounded, both arms bent and held close to the sides')
add(363, '武术 · 仰身举棍', '上身后仰，一手将长棍高举过头顶，双腿前后大开', 'arching the torso back with one arm lifting a long staff overhead and the feet spread wide front to back')
add(364, '跳跃 · 单手举棍腾空', '身体腾空跃起，一只手把长棍高高举过头顶，双腿收离地面', 'leaping into the air with one arm holding a long staff high overhead and both feet clear of the ground')
add(365, '武术 · 斜举长刀', '双手握长刀斜举向斜上方，双腿宽分开成站立架势', 'raising a long sword diagonally overhead with both hands while standing with the feet spread wide')
add(366, '武术 · 双手持棍斜劈', '双手持棍从斜上方劈向斜下方，前腿屈膝弓步，重心下沉', 'chopping a long staff down diagonally from above with both hands, the front knee bent in a lunge and the weight lowered')
add(367, '武术 · 弓步持棍平推', '一腿在前屈膝成弓步，双手持长棍水平向前推出', 'in a lunge with the front knee bent, pushing a long staff straight forward horizontally with both hands')
add(368, '武术 · 立姿持棍上举', '双脚并立站直，双手把长棍竖直举在面前，棍身贴向脸侧', 'standing straight with the feet together, both hands holding a long staff upright in front of the face')
add(369, '弓步 · 单手前伸后拉', '一腿向后伸直，前腿弓步下沉，一只手向前伸，另一只手向后拉', 'in a lunge with the back leg straight, one arm reaching forward and the other pulling backward')
add(370, '倒立 · 单臂撑地', '单手撑地倒立，身体侧向绷直，双腿并拢向上伸直', 'balancing upside down on one straight arm with the body held rigid and both legs extended upward together')
add(371, '蹲姿 · 持棍横撑', '低蹲屈膝，握着一根长杆横在身前，肩部靠住杆身', 'crouched low with a long pole held horizontally across the front and one shoulder braced against it')
add(372, '倒立 · 攀柱屈腿', '双手攀住竖直柱子倒挂身体，双腿弯曲收向腹部', 'hanging upside down from a vertical pole with both hands, the legs bent and tucked toward the abdomen')
add(373, '倒立 · 头手撑柱倒挂', '头与双手一起撑在竖直柱上倒挂，双腿向上分开伸直', 'inverting with the head and both hands braced on a vertical pole, the legs split and extended upward')
add(374, '悬挂 · 单臂悬垂', '单臂抓住横杆高悬，身体侧向舒展，双腿并拢微弯', 'hanging from a horizontal bar on one arm, the body extended sideways with both legs together and slightly bent')
add(375, '舞蹈 · 半蹲双臂外展', '半蹲压低身体，双臂向两侧外展成一条横线', 'in a half squat with the body lowered and both arms spread out to the sides in a wide horizontal line')
add(376, '拉伸 · 双臂上举合掌', '双脚分开站立，双臂上举过头顶，双手合十相扣向上拉伸', 'standing with the feet apart, both arms raised overhead and the palms pressed together as if stretching upward')
add(377, '站立 · 单臂上举屈膝', '一腿屈膝抬起，另一腿支撑站立，一只手高举向上', 'standing on one leg with the other knee bent and lifted while one arm reaches straight up')
add(378, '舞蹈 · 俯身双臂后展', '上身大幅前俯贴近水平，双臂向身后两侧展平', 'bending the torso forward almost horizontal with both arms stretched out and back to the sides')
add(379, '舞蹈 · 单臂高举抬膝', '一腿屈膝抬起，支撑腿微屈，一只手高举过头，颈部后仰', 'dancing with one knee lifted, the supporting leg slightly bent and one arm raised high with the neck extended back')
add(380, '站立 · 抱腿抬膝', '单腿站立，双手抱住另一条腿屈膝提起贴近胸前', 'standing on one leg while using both hands to hug the other bent leg up toward the chest')
add(381, '弓步 · 屈臂顶髋', '宽弓步站立，前腿屈膝，一只手屈肘顶在髋部，另一手叉腰', 'in a wide lunge with the front knee bent, one hand flexed at the elbow pressing against the hip and the other on the waist')
add(382, '行走 · 抱臂前倾', '边走边把双臂抱在胸前，上身微微前倾', 'walking with both arms folded across the chest and the upper body leaning slightly forward')
add(383, '站立 · 侧身扬臂', '侧身站立，一臂向后上方扬起，另一臂垂在身前', 'standing in profile with one arm raised up and behind and the other hanging down in front')
add(384, '蹲坐 · 抱膝托腮', '蹲坐在脚跟上，双膝并拢抱起，一只手托住下巴', 'squatting on the heels with both knees drawn up and one hand propping the chin')
add(385, '弓步 · 前臂横挡', '前腿屈膝弓步，两条前臂在胸前交叉横挡在身前', 'in a forward lunge with both forearms crossed horizontally in front of the chest as a guard')
add(386, '拉伸 · 双臂上举踮脚', '双脚踮起脚尖，双臂伸直高举过头顶并交叠手指', 'rising onto the toes with both arms stretched straight overhead and the hands overlapping')
add(387, '舞蹈 · 侧倾单臂上扬', '身体向侧方倾斜成弧线，一只手向上扬起，另一只手向外伸出', 'dancing with the body curved in a side lean, one arm swept up and the other reaching outward')
add(388, '地面 · 仰卧剪刀腿', '仰卧在地面上，双腿高举在空中交叉张开成剪刀状', 'lying on the back with both legs lifted high and crossed apart in a scissor shape')
add(389, '站立 · 侧身垂臂后望', '侧身站立，双臂垂落身侧，头扭向斜后方', 'standing in profile with both arms hanging at the sides and the head turned to look back over the shoulder')
add(390, '蹲坐 · 环抱小腿', '低低蹲坐，双臂环抱住小腿两侧，肩膀收拢', 'crouching very low with both arms wrapped around the outsides of the shins and the shoulders drawn in')
add(391, '弓步 · 展臂后仰', '弓步分开双腿，双臂上举过头，躯干向后仰起', 'in a lunge with both arms raised overhead and the torso leaning backward')
add(392, '弓步 · 屈臂下压', '前腿屈膝弓步，双臂屈肘向下压向身体前侧', 'in a lunge with the front knee bent, both arms flexed at the elbows and pressed down in front of the body')
add(393, '弓步 · 单臂高举', '宽弓步站立，一只手高举过头顶，另一只手向斜下方伸出', 'in a wide lunge with one arm reaching straight up and the other extended diagonally downward')
add(394, '站立 · 双臂交叉上举', '双脚并拢站立，双臂在头顶交叉后向两侧打开', 'standing with the feet together and both arms crossed overhead before opening out to the sides')
add(395, '地面 · 俯卧屈膝抬脚', '俯卧在地面上，双腿屈膝向上抬起交叠在小腿后方', 'lying prone with both knees bent so the feet lift up and cross behind the calves')
add(396, '站立 · 抱头后仰', '站直身体，双手抱住后脑，肘部向两侧撑开，头部后仰', 'standing with both hands behind the head, elbows flared out and the head tilted back')
add(397, '站立 · 持棍俯身', '握着长杆垂在身侧，上身向前俯下贴近水平', 'holding a long staff down at the side while the torso bends forward to almost horizontal')
add(398, '舞蹈 · 侧步扬臂', '向侧方跨出一步，一只手向斜上方扬起，身体随步伐扭转', 'stepping to the side while one arm sweeps up diagonally and the torso twists with the movement')
add(399, '弓步 · 屈臂上举', '前腿屈膝弓步，双手屈肘上举到头侧，前臂向上发力', 'in a forward lunge with both arms flexed and raised beside the head, forearms driving upward')
add(400, '行走 · 抱臂侧步', '侧向迈步移动，双臂交抱在胸前，头部转向行走方向', 'walking sideways with both arms folded across the chest and the head turned toward the direction of travel')
add(401, '弓步 · 侧举长棍', '一腿向侧方伸直点地，一只手把长棍竖直举在头侧', 'extending one leg straight out to the side on the toes while holding a long staff upright beside the head')
add(402, '行走 · 垂臂迈步', '向前行走时双腿交替迈出，双臂垂直向下贴着身体', 'walking forward with the legs alternating in long steps and both arms hanging straight down against the body')
add(403, '跳跃 · 展臂腾空', '双腿腾空离地，双臂向两侧水平展开', 'airborne with both feet off the ground and both arms stretched out horizontally to the sides')
add(404, '站立 · 双臂外展分腿', '双脚大幅分开站立，双臂斜向两侧张开，与地面形成三角形', 'standing with the feet spread wide and both arms opened diagonally to the sides in a triangular shape')
add(405, '弓步 · 屈肘后撤', '一腿向后撤步屈膝，重心落在后腿，前臂向后拉', 'stepping back with the rear knee bent so the weight sits over the back leg, the forearms pulled behind')
add(406, '半跪 · 单臂上举撑地', '单膝跪地，一臂垂直上举，另一手撑在大腿上，髋部前推', 'kneeling on one knee with one arm raised straight up and the other hand braced on the thigh, hips pushed forward')
add(407, '弓步 · 双手扶膝', '双腿宽分开成站立弓步，双手同时按在膝盖上，上身略前倾', 'in a wide standing lunge with both hands pressing on the knees and the upper body leaning slightly forward')
add(408, '弓步 · 侧身拉弓', '双腿分开侧身站立，一只手向后拉弓臂，另一只手在身前控弦', 'standing side-on with the legs apart, one arm pulling a bow back while the other hand holds the string in front')
add(409, '弓步 · 双手拉弓', '前腿屈膝半蹲，双手在胸前横向拉开一张弓', 'in a half squat with the front knee bent, drawing a bowstring back across the chest with both hands')
add(410, '弓步 · 举棍过头', '弓步分开双腿，双手把长棍举过头顶，棍身斜在身后', 'in a lunge with both hands lifting a long staff overhead so the pole rests diagonally behind')
add(411, '站立 · 横持长棍', '双脚分开站立，双手握着一根长棍横在腰腹前', 'standing with the feet apart, holding a long staff horizontally across the waist with both hands')
add(412, '弓步 · 双手持棍上举', '前后弓步站立，双手把长棍斜举到头顶上方', 'in a front-back lunge with both hands raising a long staff diagonally above the head')
add(413, '弓步 · 抬膝单臂后展', '前腿屈膝抬起，后腿蹬地支撑，一只手向侧后方展平', 'lifting the front knee while balancing on the rear leg and extending one arm out and back to the side')
add(414, '弓步 · 双臂前推', '半蹲弓步，双臂同时向前伸出推直，两手张开', 'in a half squat lunge with both arms pushed out straight in front and the hands open')
add(415, '站立 · 单臂侧前伸', '身体侧向站立，一只手向斜前方伸出，颈部随之外转', 'standing with the body turned sideways and one arm extended diagonally forward, the neck turning to follow')
add(416, '站立 · 叉腰并腿', '正面站直，双腿并拢交叉，双手同时撑在腰胯上', 'standing straight facing forward with the legs together and crossed and both hands on the hips')
add(417, '站立 · 双臂上举开掌', '双脚并拢站立，双臂高举向两侧斜上方打开，双掌朝外', 'standing with the feet together and both arms raised diagonally up and out, palms open')
add(418, '弓步 · 持棍前刺', '前腿弓步下压，双手握长棍水平向斜下方刺出', 'in a forward lunge, thrusting a long staff forward and downward while gripping it with both hands')
add(419, '站立 · 双臂上举交叠', '双脚分开站立，双臂高举过头并在头顶交叠，掌心相对', 'standing with the feet apart and both arms raised overhead, crossing over each other with palms facing')
add(420, '弯腰 · 双手撑膝', '双脚分开站定，上身弯腰前俯，双手撑在两个膝盖上', 'standing with the feet apart, bending forward and resting both hands on the knees')
add(421, '弓步 · 单臂后摆', '一腿弓步前屈，另一只手向后大幅摆出，肩部后旋', 'in a lunge with the front knee bent while one arm swings far behind with the shoulder rotating back')
add(422, '平衡 · 抬膝展臂', '单腿站立，另一条腿屈膝抬起，双臂向两侧平平展开', 'balancing on one leg with the other knee raised and both arms stretched out flat to the sides')
add(423, '舞蹈 · 后仰双臂上扬', '躯干后仰弓起，双臂从身侧向斜上方扬起', 'arching the torso backward while sweeping both arms up and out from the sides')
add(424, '站立 · 叉腰侧倚', '一手叉腰，身体重心压向一侧，髋部侧移，双腿微分', 'standing with one hand on the hip, the weight shifted to one side so the hip juts out and the feet stay slightly apart')
add(425, '弓步 · 单手举棍后拉', '宽弓步站立，一只手把长棍高高举起向后拉，另一手扶在髋部', 'in a wide lunge with one arm lifting a long staff high and back while the other hand rests on the hip')
add(426, '弓步 · 单手侧举长棍', '一腿支撑抬起，另一只手把长棍水平举在体侧，另一臂向上张开', 'balancing on one leg with the other foot raised, holding a long staff horizontally at the side while the other arm opens upward')
add(427, '跳跃 · 双手举棍', '双腿前后分立成跳跃姿态，双手把长棍举到肩后蓄力', 'in a leaping stance with the legs split front and back, both hands drawing a long staff back behind the shoulder')
add(428, '弓步 · 双手举棍斜举', '弓步沉胯，双手把长棍斜举过头顶上方', 'in a lunge with the hips lowered, both hands raising a long staff diagonally above the head')
add(429, '弓步 · 持棍架肩', '弓步站立，一只手把长棍横搭在肩上，棍身斜向身后', 'in a lunge with one hand resting a long staff across the shoulder, the pole angled behind the back')
add(430, '弓步 · 低头持棍下压', '低头弓步，双手把长棍斜压到身前最低处', 'head lowered in a lunge while both hands press a long staff down toward the ground in front')
add(431, '弓步 · 举棍仰首', '弓步站定，双手把长棍举过面门，头部随棍抬起', 'in a lunge with both hands lifting a long staff up past the face and the head tilting up to follow it')
add(432, '倒立 · 单手撑地弓背', '单手撑地倒立，背部弓成弧形，双腿并拢向上弯曲', 'inverting on one arm with the back arched into a curve and both legs extended upward and slightly bent')
add(433, '行走 · 屈臂迈臂', '向前行走，双臂屈肘在胸前交替摆动', 'walking forward with both arms bent at the elbows and swinging alternately in front of the chest')
add(434, '站立 · 双臂上举张掌', '双脚分开站立，双臂屈肘上举到头侧，两手张开掌心朝前', 'standing with the feet apart, both arms raised and bent beside the head with the palms spread forward')
add(435, '站立 · 抱臂后仰', '双脚分开站直，双臂抱在胸前，上身向后挺起', 'standing straight with the feet apart, both arms folded across the chest and the upper body leaning back')
add(436, '站立 · 交臂侧身', '身体侧转，双臂在身前交抱，颈部转向镜头', 'the body turned sideways with both arms crossed in front and the neck rotated toward the viewer')
add(437, '半跪 · 双臂上举', '一腿跪地一腿弓起，双臂同时上举向两侧张开', 'half kneeling with one leg down and the other bent, both arms raised and opened to the sides')
add(438, '站立 · 双臂交叠腹前', '正面站直，双臂在腹部前方交叠，双肩微微内收', 'standing straight facing forward with both arms crossed low over the abdomen and the shoulders drawn in slightly')
add(439, '站立 · 扶颈后弓', '一手绕到颈后扶着后颈，头部后仰，胸口挺起', 'standing with one hand resting on the back of the neck, the head tilted back and the chest lifted')
add(440, '弓步 · 双手叉腰侧倾', '双腿宽分站定，双手叉腰，躯干向一侧倾斜', 'standing with the legs wide apart, both hands on the hips and the torso tilted to one side')
add(441, '站立 · 垂臂交叉腿', '正面站立，双腿在脚踝处交叉，双臂垂在身侧', 'standing facing forward with the ankles crossed and both arms hanging at the sides')
add(442, '站立 · 单臂高举开腿', '双脚分开站立，一只手笔直举过头顶，另一只手随身后摆', 'standing with the feet apart, one arm reaching straight overhead and the other swinging behind')
add(443, '站立 · 双手抱头后仰', '双手交叠托在脑后，肘部撑开，头部后仰', 'both hands clasped behind the head with the elbows flared out and the head tilted back')
add(444, '弓步 · 单臂上举侧看', '前腿弓步屈膝，一只手向上高举，头部看向手的方向', 'in a lunge with the front knee bent, one arm raised high and the head turned to look toward it')
add(445, '行走 · 交叉腿侧身', '侧身站立时一条腿交叉到另一条腿前方，双臂自然垂落', 'standing in profile with one leg crossed in front of the other and both arms resting naturally')
add(446, '站立 · 双臂环抱肘前', '正面站直，双臂环抱，两只手分别托住对侧手肘', 'standing straight facing forward with the arms wrapped around the torso, each hand holding the opposite elbow')
add(447, '行走 · 单手抬臂', '向前迈步行走，一只手抬到腰侧向斜上方摆动', 'stepping forward while raising one hand to the side of the waist and swinging it diagonally upward')
add(448, '行走 · 双手叉腰迈步', '一边行走一边双手叉腰，双腿交替跨步', 'walking forward with both hands on the hips and the legs alternating in long strides')
add(449, '平衡 · 抬膝前伸', '单腿站立，另一条腿屈膝抬起，同时一只手向前伸出', 'balancing on one leg with the other knee raised while one arm reaches straight out in front')
add(450, '站立 · 单手抚颊', '站定身体，一手抬起轻贴脸颊，另一只手垂在身侧', 'standing still with one hand lifted against the cheek and the other arm hanging at the side')
add(451, '弓步 · 反臂后摆', '弓步下蹲，一只手反手向斜后方甩出，身体随之扭转', 'in a deep lunge with one arm thrown back and out behind as the torso twists away')
add(452, '平衡 · 抬膝抱头', '单腿站立，另一腿屈膝抬起，双手抱在头顶', 'balancing on one leg with the other knee raised and both hands clasped on top of the head')
add(453, '平衡 · 抬膝抱胸', '单腿站立，另一条腿屈膝横在身前，双臂抱住膝盖', 'balancing on one leg with the other knee drawn across the body and both arms hugging the raised knee')
add(454, '站立 · 屈肘举指', '双腿交叉站立，一手叉腰，另一只手屈肘举起手指向上', 'standing with the legs crossed, one hand on the hip and the other hand flexed at the elbow with fingers raised')
add(455, '弓步 · 单手叉腰', '一腿向前伸出点地，另一只手叉在腰间，上身微微后倾', 'with one leg extended forward on the toes, the other hand planted on the hip and the torso leaning slightly back')
add(456, '深蹲 · 广脚蹲俯身', '双脚大幅分开深蹲成蛤式，躯干前俯，双臂垂在两腿之间', 'squatting very wide into a frog stance with the torso pitched forward and both arms hanging between the legs')
add(457, '站立 · 垂臂正面', '正面对镜头站直，双脚分开，双臂自然垂在身体两侧', 'standing straight and facing the viewer with the feet apart and both arms hanging at the sides')
add(458, '弓步 · 双臂侧展', '双腿分开成站立弓步，双臂向两侧水平展开', 'in a wide standing lunge with both arms extended horizontally out to the sides')
add(459, '站立 · 双臂微展', '正面站立，双腿微分，双臂在身体两侧微微离开躯干', 'standing facing forward with the feet slightly apart and both arms held a little away from the body')
add(460, '站立 · 单手抚胸', '站定身体，一手按在胸前，另一只手垂在身侧', 'standing still with one hand pressed to the chest and the other arm hanging at the side')
add(461, '弓步 · 屈肘举拳', '前腿弓步屈膝，一只手屈肘举到肩侧并握拳', 'in a forward lunge with one hand flexed at the elbow and raised beside the shoulder in a fist')
add(462, '弓步 · 屈肘撑腿', '宽弓步站立，一手撑在大腿上，另一只手屈肘抬在胸前', 'in a wide lunge with one hand braced on the thigh and the other flexed at the elbow in front of the chest')
add(463, '弓步 · 抱胸侧立', '双腿分开侧身站立，双臂抱在胸前，颈部转向镜头', 'standing side-on with the legs apart and both arms folded across the chest, the head turned to the camera')
add(464, '弓步 · 跪姿持棍', '一腿跪地一腿屈膝，单手把长棍竖直插在身侧地面', 'kneeling on one knee with the other leg bent, holding a long staff vertically planted on the ground beside the body')
add(465, '弓步 · 持棍斜扛', '弓步分开双腿，一只手把长棍斜扛在肩上，棍身指向斜上方', 'in a wide lunge with one hand shouldering a long staff at an angle pointing up')
add(466, '弓步 · 持棍后拉', '前腿屈膝弓步，一只手握长棍在身体后方低位拉出', 'in a forward lunge with one hand drawing a long staff back low behind the body')
add(467, '弓步 · 双臂平展持棍', '弓步下蹲，两臂向两侧平展，一手握长棍横在身前', 'in a lowered lunge with both arms extended out to the sides and one hand holding a long staff horizontally in front')
add(468, '行走 · 垂臂正面', '正面对镜头行走，双臂垂直下垂，双腿交替迈步', 'walking toward the viewer with both arms hanging straight down and the legs alternating in steps')
add(469, '平衡 · 抬膝后仰', '单腿站立，另一条腿屈膝抬起，上身向后仰起', 'balancing on one leg with the other knee raised and the torso leaning backward')
add(470, '行走 · 侧身背手', '侧身行走时双手背在身后，双脚交替迈步', 'walking in profile with both hands clasped behind the back and the feet alternating in steps')
add(471, '平衡 · 单腿后折举臂', '单腿站立，另一条腿向后折起，手臂高举过头', 'standing on one leg with the other leg folded back and the arms lifted overhead')
add(472, '行走 · 双臂平展', '向前行走时双臂向两侧水平伸直展开', 'walking forward with both arms extended straight out horizontally to the sides')
add(473, '平衡 · 抬膝竖拇指', '单腿站立，另一腿屈膝抬起，一只手朝前竖起大拇指', 'balancing on one leg with the other knee raised and one hand held in front with the thumb up')
add(474, '站立 · 单手扶头侧倾', '一手扶在头顶上侧，躯干向同侧倾斜，双腿微分站立', 'standing with one hand resting on top of the head and the body leaning to that side, the feet slightly apart')
add(475, '弓步 · 抬膝勾脚', '支撑腿屈膝下压，另一条腿屈膝勾脚抬起，手臂向外侧张开', 'lowering onto one bent leg while lifting the other with the knee bent and toe pointed up, the arms opening outward')
add(476, '舞蹈 · 侧踢腿展臂', '单腿支撑，另一条腿向斜上方踢起，双臂向两侧张开保持平衡', 'balancing on one leg while kicking the other leg up and out to the side with both arms spread for balance')
add(477, '弓步 · 抱臂立正', '双腿分开站直，双臂交抱在胸前，肩部向后打开', 'standing straight with the legs apart and both arms folded across the chest, the shoulders opened back')
add(478, '舞蹈 · 跃起张臂', '身体腾空跃起，双臂向前上方张开，双腿一前一后蹬离地面', 'leaping into the air with both arms opening forward and upward and the legs pushing off one behind the other')
add(479, '平衡 · 抬膝双臂交扣', '单腿站立，另一腿屈膝抬起，双臂在胸前交扣成环', 'balancing on one leg with the other knee raised and both arms crossed into a shape in front of the chest')
add(480, '跳跃 · 持铃屈臂空屈膝', '腾空跳起，一手举小哑铃向上，另一手屈肘把铃举到肩前，双膝弯曲成跑步状', 'caught mid-jump holding a small dumbbell in each hand, one arm punched up and the other bent at the shoulder, both knees bent in a running shape')
add(481, '站立 · 双臂平举开肩', '站直身体，双腿分开与肩同宽，双臂向两侧平举略低于肩，胸口打开', 'standing upright with the feet apart and both arms stretched straight out to the sides just below shoulder height, the chest opened')
add(482, '仰卧 · 双腿垂直上举', '仰面躺卧，双腿并拢垂直向上伸直，双臂也向上举向脚尖方向', 'lying on the back with both legs extended straight up together and both arms reaching upward toward the toes')
add(483, '站立 · 单臂垂直高举', '单腿微屈站直，一只手笔直举过头顶向上，另一只手垂在身侧，视线朝上', 'standing with one knee slightly bent and one arm raised straight up overhead while the other arm hangs loose at the side')
add(484, '坐姿 · 抬膝双臂上举', '坐姿悬空，双膝屈曲抬起，双臂屈肘上举，双手呈抓举状停在肩侧', 'seated in mid air with both knees drawn up and both arms bent and raised beside the shoulders in a lifted grip')
add(485, '站立 · 单臂高举侧立', '身体侧对镜头站立，一只手高举过头顶，另一只手沿身侧下垂，重心落在后腿', 'standing with the body turned sideways, one arm reaching high above the head and the other arm hanging down along the thigh, the weight on the back leg')
add(486, '奔跑 · 前倾一臂后甩', '身体大幅前倾成奔跑状，一条手臂向前上方摆，另一条手臂向斜后方甩开，后腿蹬地', 'sprinting with the torso pitched far forward, one arm swinging up in front and the other flung back behind, the rear leg pushing off the ground')
add(487, '弓步 · 一臂上举侧展', '双腿大跨开成弓步，一只手弯肘举过头顶，另一只手臂向侧方水平展开', 'in a wide lunge with one arm bent and raised over the head while the other arm extends straight out to the side')
add(488, '器械 · 长矛斜举过顶', '双手握一根长矛，把矛斜举过头顶上方，一条腿抬起屈膝', 'holding a long spear with both hands and raising it diagonally above the head while one leg lifts with the knee bent')
add(489, '器械 · 双臂横持长矛', '双腿分开站立，双臂向斜上方伸直，双手在身前横握一根长矛', 'standing with the feet apart and both arms extended diagonally upward, gripping a long spear horizontally in front of the body')
add(490, '器械 · 举杆侧身', '双手把一根长杆斜举向上方，身体向侧面拧转，一条腿屈膝点地', 'lifting a long pole diagonally upward with both hands while the torso twists to the side and one knee bends')
add(491, '器械 · 单手持匕首', '一臂屈肘举在肩旁，另一只手在体侧握着匕首短刃，双腿微分立', 'one arm bent and raised beside the shoulder while the other hand holds a short dagger down at the side, feet slightly apart')
add(492, '器械 · 竖举长杆', '双手握住一根长杆竖直举在头顶，一条腿向侧方抬起', 'both hands holding a long pole raised vertically overhead while one leg lifts out to the side')
add(493, '坐姿 · 单腿高抬弯臂', '半躺坐姿靠肘支撑，一条腿高高伸直抬起，另一条腿屈曲着地，双臂弯举', 'reclining in a supported seated pose with one leg lifted high and straight, the other leg bent on the floor and both arms flexed')
add(494, '站立 · 双臂上举成环侧身', '侧身站立，双臂高举弯成圆环，肘部微屈', 'standing upright in profile with both arms raised overhead curving into a ring, elbows slightly bent')
add(495, '平衡 · 抬膝对侧展开', '单腿站立，另一条腿屈膝侧抬，一只手向上举、另一只手向侧下方展开保持平衡', 'balancing on one leg with the other knee lifted out to the side, one arm reaching up while the other opens out low and wide')
add(496, '坐姿 · 单手撑地斜举', '坐姿悬空，一只手在身侧撑地，另一条手臂斜向上方伸展，双腿屈曲', 'seated in mid air with one hand planted on the ground for support and the other arm reaching diagonally upward, both legs bent')
add(497, '平衡 · 屈腿双臂上举', '单腿站立支撑，另一条腿向后折起，双臂屈肘举在肩上方', 'balancing on one leg with the other leg folded back behind, both arms bent and raised above the shoulders')
add(498, '平衡 · 后抬腿双臂张开', '单腿站立，一条腿向后抬起，双臂向两侧斜上方大幅张开成展翅状', 'balancing on one leg with the other leg trailing back, both arms opened wide and diagonally upward like spread wings')
add(499, '深蹲 · 抱头深蹲', '双脚并拢深深下蹲，双膝大幅屈曲，双臂从两侧环抱头顶', 'squatting deeply with the feet together and both knees fully bent, the arms wrapping around the top of the head')
add(500, '俯身 · 弯腰双臂下垂', '背对镜头弯腰前俯，双臂松松地朝地面垂直下垂，双膝微屈', 'seen from behind and folded forward at the waist with both arms hanging loosely straight down toward the floor and the knees slightly bent')
add(501, '俯卧 · 俯身双臂后伸', '身体几乎水平前俯，双腿向后伸展，双臂向斜后方举起', 'the body pitched forward almost horizontally with both legs extended back and both arms lifted diagonally behind')
add(502, '站立 · 双拳抵腰', '双脚分开站直，双拳握紧抵在腰侧，肘部向后打开', 'standing with the feet apart and both fists pressed against the sides of the waist, elbows pulled back')
add(503, '站立 · 双臂上举交叠侧身', '侧身站立，双臂在头顶交叠，手肘微屈，上身轻微后仰', 'standing upright in profile with both arms raised and crossed above the head, elbows slightly bent, torso leaning back')
add(504, '站立 · 分腿侧倾', '双腿分开站立，身体向侧面倾斜，一只手在腰后、另一只手垂在体侧', 'standing with the legs apart and the body leaning to one side, one hand resting behind the waist and the other hanging down')
add(505, '舞蹈 · 高踢双腿上展', '单腿支撑站立，另一条腿向前上方高高踢起，双臂向上展开成扇形', 'balancing on one leg while kicking the other leg high up in front, both arms opened upward in a fan')
add(506, '站立 · 单手举胸前', '双脚分开站直，一只手握拳举到胸前，另一只手叉在腰上', 'standing straight with the feet apart, one fist raised in front of the chest and the other hand on the hip')
add(507, '站立 · 单手抚头侧立', '身体微侧站立，一只手抬到头侧轻抚，另一只手屈肘停在胸前，双腿错开', 'standing slightly turned with one hand lifted to the side of the head and the other arm bent in front of the chest, the legs staggered')
add(508, '站立 · 双臂前平举', '双脚分开站稳，双膝微屈，双臂向前下方平举，手掌相对', 'standing with the feet apart and the knees slightly bent, both arms extended forward and slightly downward with the palms facing each other')
add(509, '平衡 · 弯腰抱腿', '站立时弯腰向下折叠，双臂伸向后方抱住抬起的一条腿，身体成折叠状', 'folded forward at the waist from standing, both arms reaching behind to hold one lifted leg, the body compressed in a fold')
add(510, '平衡 · 侧抬腿单臂高举', '单腿站立，另一条腿向侧方抬起，一只手高举过头，另一只手向斜后摆', 'standing on one leg with the other leg raised out to the side, one arm lifted overhead and the other swinging back')
add(511, '半跪 · 单臂垂直上举', '半跪在地，一只手笔直举向上方，另一只手垂在体侧，跪姿身体挺直', 'kneeling on one knee with the torso upright, one arm raised straight up overhead and the other resting at the side')
add(512, '坐姿 · 空中蹬腿', '仰卧在地面，两条腿在空中屈膝交替蹬出，双臂张开撑住身体', 'on the back with both legs raised and alternating bent-knee kicks in the air while both arms spread out to brace the body')
add(513, '倒立 · 双臂撑地分腿', '双手撑地做倒立，身体倒立，两条腿朝空中分开成大八字', 'handstand with both arms locked and straight, the body inverted and the legs spread wide apart in a large V overhead')
add(514, '平衡 · 抬膝双臂上举', '单腿站立，另一腿屈膝抬至腰高，双臂高举过头', 'balancing on one leg with the other knee raised to waist height and both arms raised overhead')
add(515, '站立 · 单手扶额错步', '双腿一前一后错步站立，一只手抬到额头处搭着，另一只手垂在身侧', 'standing with the feet staggered front to back, one hand resting on the forehead and the other arm hanging down')
add(516, '弓步 · 低蹲双手前伸', '双腿大幅分开低成弓步，身体下蹲，双手朝前下方伸出去', 'in a deep wide lunge with the body lowered, both arms reaching forward and down')
add(517, '站立 · 单手扶髋分腿', '双腿分开站直，一只手扶在髋骨上，另一只手自然垂放', 'standing straight with the legs apart, one hand resting on the hip and the other arm hanging freely')
add(518, '站立 · 双手交握交叉腿', '双脚交叉站立，双手在身前交握成拳，双臂自然下垂', 'standing with the ankles crossed and both hands clasped together in front of the thighs')
add(519, '行走 · 双臂交替摆动', '向侧前方行走，双臂随步伐一前一后自然摆动，双腿跨开成步', 'walking forward and to the side with both arms swinging alternately in rhythm with the stride')
add(520, '行走 · 双臂屈肘上摆', '向前行走，双臂屈肘向上摆动，前腿抬起重心前移', 'walking forward with both arms bent at the elbows and swinging upward as the lead leg lifts')
add(521, '弓步 · 双拳交替击出', '弓步半蹲，双拳一前一后向前击出，后手收在胸前', 'in a lunging stance with both fists punching forward one after the other, the other fist drawn back at the chest')
add(522, '弓步 · 大跨步前推', '双腿大跨成弓步，一只手向前推出，另一只手垂在体侧，躯干侧转', 'in a long forward lunge with one hand pushing ahead and the other hanging at the side, the torso turned')
add(523, '站立 · 头顶交握成环', '站直身体，双臂弯肘举过头顶，两手在头顶交握成一个环', 'standing upright with both arms bent and raised overhead, the hands clasped together in a ring above the head')
add(524, '侧腰 · 单臂过头下探', '身体向侧方弯腰，一只手从头顶越过伸向另一侧，另一只手向下滑', 'bending sideways with one arm reaching over the head toward the far side while the other arm slides down the leg')
add(525, '深蹲 · 双臂抱头下蹲', '双脚分开深蹲下坐，双膝屈曲，双臂弯肘抱在头后', 'squatting deep with the feet apart, both knees bent and both arms wrapped behind the head')
add(526, '站立 · 双臂交叉前伸', '站直身体，双臂在胸前交叉向前伸出，双腿微分立', 'standing upright with both arms crossed and extended forward in front of the chest, feet slightly apart')
add(527, '平衡 · 单手扶头抬膝', '单腿站立，另一条腿屈膝抬起，一只手扶在头侧，另一只手屈肘于胸前', 'balancing on one leg with the other knee lifted, one hand touching the side of the head and the other arm bent at the chest')
add(528, '站立 · 单臂上举叉腰', '站直身体，一只手向上举过头顶，另一只手叉在腰上，双膝微屈', 'standing with one arm raised straight overhead and the other hand on the hip, the knees slightly bent')
add(529, '深蹲 · 双手撑膝单臂举', '半蹲下坐，双手撑在大腿上，另一只手臂向侧上方举起', 'squatting partway down with both hands braced on the thighs while the other arm lifts out to the side and up')
add(530, '行走 · 侧身屈臂摆动', '背对镜头侧身行走，双臂屈肘前后摆动，双腿一前一后交叉迈步', 'seen from behind while walking sideways, both arms bent and swinging in opposition as the legs cross in stride')
add(531, '后弯 · 单手撑地举臂', '深度后弓成桥状，一只手撑地支撑身体，另一只手向侧上方高举，双腿抬起离地', 'in a deep backbend with one hand planted on the ground and the other arm raised up and out, both feet lifted off the floor')
add(532, '站立 · 单臂屈肘上举', '双脚分开站直，一条手臂屈肘举到肩侧，另一只手垂在身侧', 'standing straight with the feet apart, one arm bent and lifted beside the shoulder and the other hanging at the side')
add(533, '弓步 · 单指前探', '低弓步半蹲，一只手向前伸出用手指探，另一只手撑在大腿上', 'in a low lunge with one hand reaching forward and pointing the fingers out while the other braces on the thigh')
add(534, '奔跑 · 屈肘大步跑', '大步奔跑，一条腿前跨双臂屈肘摆动，另一条腿在身后蹬伸', 'running with a long stride, one leg reaching ahead while both arms bent at the elbows pump and the other leg extends behind')
add(535, '站立 · 单臂绕头后', '站直身体，一只手绕到脑后抓住后颈，双腿交叠站着', 'standing upright with one hand reaching around behind the head to the back of the neck, the legs crossed')
add(536, '弓步 · 一臂上举一臂平', '双腿大开成弓步，一只手向上举过头，另一只手臂向侧面平伸', 'in a wide lunge with one arm raised overhead and the other extended straight out to the side')
add(537, '站立 · 单手前指横臂', '站直身体，一只手向前平伸用手指点，另一只手横搭在腹前', 'standing upright with one hand extended forward pointing a finger and the other arm lying horizontally across the abdomen')
add(538, '站立 · 单手按腹侧倾', '身体向侧方微倾，一只手按在腹部，另一只手撑在髋部', 'leaning slightly to the side with one hand pressed on the abdomen and the other braced on the hip')
add(539, '平衡 · 俯身单腿后抬', '俯身向前倾，一条腿向后抬起，一手扶在头侧，另一只手向下伸展', 'hinging forward at the hips with one leg raised behind, one hand near the side of the head and the other arm reaching down')
add(540, '站立 · 双臂松垂', '双脚分开自然站立，双臂松松垂在身体两侧，视线略向下', 'standing naturally with the feet apart and both arms hanging loosely at the sides, the gaze angled down')
add(541, '站立 · 单臂横胸前', '身体侧对镜头站立，一条手臂横在胸前，另一只手在体侧，双腿错开', 'standing with the body turned sideways, one arm laid horizontally across the chest and the other at the side, legs staggered')
add(542, '站立 · 双臂上举交叉', '双脚分开站直，双臂向上举起并在头顶前方交叉，胸口挺起', 'standing with the feet apart and both arms raised and crossed in front above the head, the chest lifted')
add(543, '站立 · 双拳弯举', '双脚分开站直，双拳屈肘弯举在腰侧，肘部夹紧身体', 'standing with the feet apart and both fists flexed up beside the waist with the elbows tucked in')
add(544, '行走 · 单臂弯举侧走', '侧身行走，一条手臂屈肘弯举在胸前，另一只手在体侧，双腿前后迈', 'walking to the side with one arm flexed up in front of the chest and the other at the side, legs stepping forward and back')
add(545, '倒立 · 头顶地分腿弯', '双手与头顶撑地做倒立，身体完全倒置，两条腿在空中弯曲分开', 'supported headstand with both hands and the crown of the head on the floor, the body fully inverted and both legs bent apart in the air')
add(546, '弓步 · 屈臂前后摆', '大弓步向前奔跑感，双臂屈肘一前一后摆动，后腿蹬直', 'striding forward in a long lunge with both arms bent and swinging one in front of the other, the rear leg extended')
add(547, '弓步 · 双手前推', '双腿分开成半蹲弓步，双手在胸前掌心朝前向前推出', 'in a half squat with the legs apart, both hands pushed forward in front of the chest with the palms facing out')
add(548, '站立 · 单手托颈侧立', '身体侧对镜头站立，一只手抬到颈侧托着，另一只手垂下，双腿错步', 'standing turned sideways with one hand lifted to the side of the neck and the other hanging down, feet staggered')
add(549, '站立 · 交叉腿抱臂', '双脚交叉站立，双臂交抱在胸前，肩部微微后收', 'standing with the ankles crossed and both arms folded across the chest with the shoulders drawn slightly back')
add(550, '行走 · 单臂胸前弯举', '向前行走，一条手臂屈肘弯举停在胸前，双腿一前一后跨步', 'walking forward with one arm flexed and held in front of the chest, the legs stepping one in front of the other')
add(551, '站立 · 举手叉腰', '身体侧转站立，一只手举起停在头侧，另一只手叉在腰后，双腿交叉', 'standing with the body turned, one hand raised beside the head and the other resting on the back of the hip, legs crossed')
add(552, '站立 · 侧身单手前伸', '身体侧对镜头，一只手向前平伸，另一只手叉腰，双腿前后错开', 'standing with the body sideways, one hand extended straight forward and the other on the hip, the legs staggered')
add(553, '站立 · 侧身一臂斜伸', '侧身站立，一只手向斜前方伸出，手掌朝下，双腿一前一后', 'standing sideways with one arm reaching out diagonally forward, the palm facing down, legs split front and back')
add(554, '深蹲 · 双臂弯举下蹲', '双脚分开下蹲，双膝屈曲，双臂屈肘弯举在身体两侧', 'squatting with the feet apart and both knees bent, both arms flexed up along the sides of the body')
add(555, '平衡 · 后折腿单臂展', '单腿站立，一条腿向后折起抬到身后，一只手向上举、另一只手向侧后方展开', 'balancing on one leg with the other folded back and lifted behind, one arm reaching up and the other opening out and back')
add(556, '站立 · 单臂胸前弯举', '站直身体，一条手臂屈肘弯举在胸前，双臂一前一后，另一手自然下垂', 'standing upright with one arm flexed up in front of the chest while the other arm hangs straight down')
add(557, '站立 · 双臂前伸交叠', '双脚分开站直，双臂向前伸出并交叠在一起，双膝微屈', 'standing with the feet apart and the knees slightly bent, both arms extended forward and overlapping each other')
add(558, '平衡 · 后抬腿双臂大幅张', '单腿支撑，一条腿向后抬起，双臂大幅向两侧斜上方张开，头偏向一侧', 'balancing on one leg with the other leg raised behind and both arms opened very wide and diagonally upward, the head tilted to one side')
add(559, '行走 · 单臂前后摆大跨', '大步向前行走，一条手臂向前摆、另一条向斜后摆，双腿跨得很大', 'striding forward in a long step with one arm swinging ahead and the other swinging out behind')
add(560, '器械 · 长矛横扛肩上', '双腿分开站立，双手握一根长矛横搭在肩颈处，矛身横贯身后', 'standing with the feet apart, both hands holding a long spear laid horizontally across the shoulders with the shaft running behind the neck')
add(561, '站立 · 双手抱头后', '站直身体，双臂弯肘上抬，两手交叠抱在头后，肩部打开', 'standing upright with both arms bent upward and the hands clasped behind the head, the shoulders opened')
add(562, '平衡 · 侧卧单手撑地', '身体向侧方倾斜成侧撑，一只手向地面撑住支撑，另一只手臂向上举起，双腿并拢伸直', 'tilted sideways in a one-handed side support with one arm reaching up and the legs together and straight')
add(563, '站立 · 立正双臂微张', '双脚并拢笔直站立，双臂在身体两侧微微离开身面，头部正立', 'standing straight with the feet together and both arms held slightly away from the body, the head upright')
add(564, '站立 · 单臂上举一臂抚后脑', '双脚分开站立，一只手臂上举过头，另一只手臂弯肘把手放在后脑上', 'standing with the feet apart, one arm raised overhead and the other bent with the hand resting on the back of the head')
add(565, '站立 · 侧身单掌外推', '身体侧对镜头站立，一只手掌向外侧推出，另一只手垂在身侧，双腿错步', 'standing with the body sideways, one palm pushed out to the side and the other arm hanging down, legs staggered')
add(566, '弓步 · 双拳防守弯举', '双脚分开半蹲，双拳屈肘举到胸前作防守姿势，肩部收紧', 'in a half squat with the feet apart, both fists flexed up in front of the chest in a guard position')
add(567, '站立 · 交叉腿单臂上举', '双腿交叉站立，一只手臂向上举起，另一只手垂在身前', 'standing with the legs crossed, one arm raised upward and the other hanging in front of the body')
add(568, '行走 · 一臂前伸一臂后摆', '向前行走，一只手臂向前伸出，另一只手臂向斜后方摆动', 'walking forward with one arm reaching ahead and the other swinging diagonally back')
add(569, '器械 · 长杆下压', '双腿大幅分开，双手握一根长杆向下压在身前，身体微俯', 'standing with the legs spread wide, both hands pressing a long pole downward in front of the body as the torso leans forward')
add(570, '站立 · 双拳前推交握', '双脚分开站直，双臂向前平伸，两只手在身前互相交握推出去', 'standing with the feet apart, both arms extended forward with the hands clasped together and pushed out')
add(571, '站立 · 一臂前举一臂侧', '站直身体，一只手臂向前上方举起，另一只手臂向侧方水平伸出', 'standing upright with one arm raised forward and up and the other extended horizontally to the side')
add(572, '行走 · 抬膝双臂摆', '向前行走时抬起一条腿，双臂在身体两侧自然摆动', 'walking forward while lifting one knee, both arms swinging naturally at the sides')
add(573, '深蹲 · 双肘撑膝低头', '深深下蹲，双膝屈曲到极限，双肘撑在大腿上，头部低垂', 'squatting very deep with both knees fully bent, the elbows braced on the thighs and the head dropped')
add(574, '站立 · 单手抱头侧倾', '身体向侧方倾斜站立，一只手弯肘举到头侧，另一只手按在腹前', 'standing with the body leaning to one side, one arm bent up beside the head and the other hand resting in front of the abdomen')
add(575, '行走 · 俯身前垂双手', '身体向前弯垂，双手朝地面下垂，双腿一前一后迈开', 'hinged forward with both arms hanging down toward the floor, the legs split one in front of the other')
add(576, '平衡 · 后折腿双臂上合', '单腿站立，一条腿向后折起，双臂在头顶斜上方交合，躯干微微后仰', 'balancing on one leg with the other folded back, both arms meeting and closing above the head as the torso leans slightly back')
add(577, '支撑 · 蹲姿双手撑地', '蹲低成半跪式支撑，双手撑在大腿前方的地面上，双臂伸直，背部拱起', 'lowered into a crouching support with both hands planted on the ground in front of the thighs, arms straight and the back arched')
add(578, '俯卧撑 · 平板支撑后踢', '身体斜向悬空成平板俯撑，双臂伸直撑地，双腿向后伸直并抬起', 'held in an angled plank with both arms straight and the legs extended back and lifted off the ground')
add(579, '深蹲 · 深蹲双臂上举交叠', '双脚并拢深深下蹲，双臂向上举过头顶并在前方交叠成环', 'squatting deeply with the feet together, both arms raised overhead and crossed together into an arch')
add(580, '舞蹈 · 双手撑地双腿腾空', '双手撑在地面上，身体腾空旋转，一条腿向上伸直，另一条腿弯曲', 'both hands planted on the ground with the body airborne in a rotation, one leg extended straight up and the other leg bent')
add(581, '弓步 · 大开步双臂平展', '双腿大幅分开成大弓步，双臂向两侧水平平举展开，躯干侧转', 'in a very wide lunge with both arms stretched out horizontally to the sides and the torso turned')
add(582, '坐姿 · 悬空撑地屈腿', '半躺悬空坐姿，双手在身后撑地支撑，双腿屈曲抬起并向一侧偏移', 'reclining in a supported seat with both hands planted behind, both legs bent and lifted, shifted to one side')
add(583, '奔跑 · 屈臂交叉步', '向前奔跑，双腿交叉跨步，双臂屈肘前后快速摆动', 'running forward with the legs crossing mid-stride and both arms bent at the elbows pumping')
add(584, '平衡 · 勾脚提腿双展臂', '单腿站立，另一条腿屈膝向前提起并勾住脚尖，双臂向两侧张开保持平衡', 'balancing on one leg with the other knee drawn up in front and the toes pointed, both arms spread out to the sides for balance')
add(585, '奔跑 · 前伸手臂交跑', '向前奔跑，双腿交叉迈步，一只手臂向前伸出，另一只手臂屈肘在胸前', 'running forward with crossing steps, one arm reaching out ahead and the other bent in front of the chest')
add(586, '俯身 · 双手垂地', '弯腰俯身，双臂松松垂向地面，双膝微屈，头部向下', 'bent forward at the waist with both arms hanging loosely down toward the ground, knees slightly bent and head lowered')
add(587, '器械 · 扛棍奔跑', '奔跑向前，一只手把一根长棍扛在肩上，棍身斜指身后，后腿蹬地', 'running forward with one hand carrying a long pole across the shoulder, the pole angled out behind as the rear leg pushes off')
add(588, '器械 · 持棍侧劈', '双腿大跨开站定，双手握一根长棍向侧方斜劈下来，身体随之扭转', 'standing with the legs spread wide and both hands swinging a long pole down diagonally to the side as the body turns with it')
add(589, '器械 · 单手抓杆单腿勾', '一只手抓住立杆，一条腿勾住杆身向上抬起，身体离地斜向伸展', 'gripping a vertical pole with one hand and hooking one leg up around it, the body lifted and stretched out diagonally')
add(590, '器械 · 双腿夹杆悬垂', '身体贴着一根立杆悬起，双腿一上一下夹住杆身，双臂向两侧张开', 'suspended against a vertical pole with the legs clamped one above and one below the shaft, both arms spread out to the sides')
add(591, '器械 · 倒挂双腿交替', '双手抓着一根立杆，身体倒挂向上，双腿一弯一伸交替打开', 'hanging upside down from a vertical pole with both hands, the legs opened and bent alternately')
add(592, '器械 · 横杆水平悬垂展腿', '身体水平悬挂在一根横杆上，双腿向两侧大幅分开成大V形', 'hanging horizontally from a bar with the legs spread very wide apart into a big V')
add(593, '器械 · 横杆侧挂伸腿', '身体斜着挂在一根横杆上，一条腿勾住杆身，另一条腿向斜上方伸直', 'hanging at an angle from a bar with one leg hooked over it and the other leg extended straight up and out')
add(594, '器械 · 坐地撑杆后仰', '坐在地上，双臂向后撑住立杆把身体撑开，躯干后仰双腿前伸', 'seated on the floor with both arms braced behind against a vertical pole, the chest opened and the torso leaning back with the legs extended forward')
add(595, '器械 · 低蹲扶杆', '蹲低在立杆旁，一手扶着杆身，双膝屈曲收在胸前', 'crouched low beside a vertical pole with one hand resting on the shaft and both knees drawn up')
add(596, '器械 · 横杆俯卧展体', '身体俯卧横跨在一根横杆上，双腿向两侧张开下垂', 'lying prone across a horizontal bar with the legs opened out to the sides and hanging down')
add(597, '蹲姿 · 双肘撑膝俯首', '蹲低成蹲姿，双肘撑在膝盖上，头部深深低下，背部弓起', 'crouched low with both elbows resting on the knees and the head dropped so far that the back is rounded')
add(598, '站立 · 单手扶大腿', '双腿分开站直，一只手按在大腿外侧，另一只手垂在身前', 'standing straight with the legs apart, one hand resting on the outside of the thigh and the other hanging in front')
add(599, '平衡 · 侧抬腿单手过头', '单腿站立，另一条腿向侧方水平抬起，一只手举过头顶，另一只手叉在腰上', 'balancing on one leg with the other leg lifted out horizontally to the side, one arm raised above the head and the other on the hip')
add(600, '舞蹈 · 后折腿双臂前探', '单腿站立，另一条腿向后折起，双臂向前上方斜伸出去，身体微微后仰', 'balancing on one leg with the other folded back behind, both arms reaching diagonally forward and up as the body leans slightly back')
