# sheet 24-30: idx 480-600
add(480, '跳跃 · 持铃屈臂空屈膝', '腾空跳起，一手举小哑铃向上，另一手屈肘把铃举到肩前，双膝弯曲成跑步状', 'caught mid-jump holding a small dumbbell in each hand, one arm punched up and the other bent at the shoulder, both knees bent in a running shape')
add(481, '站立 · 双臂平举开肩', '站直身体，双腿分开与肩同宽，双臂向两侧平举略低于肩，胸口打开', 'standing upright with the feet apart and both arms stretched straight out to the sides just below shoulder height, the chest opened')
add(482, '仰卧 · 双腿垂直上举', '仰面躺卧，双腿并拢垂直向上伸直，双臂也向上举向脚尖方向', 'lying on the back with both legs extended straight up together and both arms reaching upward toward the toes')
add(483, '站立 · 单臂垂直高举', '单腿微屈站直，一只手笔直举过头顶向上，另一只手垂在身侧，视线朝上', 'standing with one knee slightly bent and one arm raised straight up overhead while the other arm hangs loose at the side')
add(484, '坐姿 · 抬膝双臂上举', '坐姿悬空，双膝屈曲抬起，双臂屈肘上举，双手呈抓举状停在肩侧', 'seated in mid air with both knees drawn up and both arms bent and raised beside the shoulders in a lifted grip')
add(485, '站立 · 单臂高举侧立', '身体侧对镜头站立，一只手高举过头顶，另一只手沿身侧下垂，重心落在后腿', 'standing with the body turned sideways, one arm reaching high above the head and the other arm hanging down along the thigh, the weight on the back leg')
add(486, '奔跑 · 前倾一臂后甩', '身体大幅前倾成奔跑状，一条手臂向前上方摆，另一条手臂向斜后方甩开，后腿蹬地', 'sprinting with the torso pitched far forward, one arm swinging up in front and the other flung back behind, the rear leg pushing off the ground')
add(487, '弓步 · 一臂上举侧展', '双腿大跨开成弓步，一只手弯肘举过头顶，另一只手臂向侧方水平展开', 'in a wide lunge with one arm bent and raised over the head while the other arm extends straight out to the side')
add(488, '器械 · 长矛斜举过顶', '双手握一根长矛，把矛斜举过头顶上方，一条腿抬起屈膝', 'holding a long spear with both hands and raising it diagonally above the head while one leg lifts with the knee bent')
add(489, '器械 · 双臂横持长矛', '双腿分开站立，双臂向斜上方伸直，双手在身前横握一根长矛', 'standing with the feet apart and both arms extended diagonally upward, gripping a long spear horizontally in front of the body')
add(490, '器械 · 举杆侧身', '双手把一根长杆斜举向上方，身体向侧面拧转，一条腿屈膝点地', 'lifting a long pole diagonally upward with both hands while the torso twists to the side and one knee bends')
add(491, '器械 · 单手持匕首', '一臂屈肘举在肩旁，另一只手在体侧握着匕首短刃，双腿微分立', 'one arm bent and raised beside the shoulder while the other hand holds a short dagger down at the side, feet slightly apart')
add(492, '器械 · 竖举长杆', '双手握住一根长杆竖直举在头顶，一条腿向侧方抬起', 'both hands holding a long pole raised vertically overhead while one leg lifts out to the side')
add(493, '坐姿 · 单腿高抬弯臂', '半躺坐姿靠肘支撑，一条腿高高伸直抬起，另一条腿屈曲着地，双臂弯举', 'reclining in a supported seated pose with one leg lifted high and straight, the other leg bent on the floor and both arms flexed')
add(494, '站立 · 双臂上举成环', '站直身体，双臂向上举过头顶，两只手臂在头顶弯成一个圆环', 'standing upright with both arms raised overhead, the two arms curving into a ring above the head')
add(495, '平衡 · 抬膝对侧展开', '单腿站立，另一条腿屈膝侧抬，一只手向上举、另一只手向侧下方展开保持平衡', 'balancing on one leg with the other knee lifted out to the side, one arm reaching up while the other opens out low and wide')
add(496, '坐姿 · 单手撑地斜举', '坐姿悬空，一只手在身侧撑地，另一条手臂斜向上方伸展，双腿屈曲', 'seated in mid air with one hand planted on the ground for support and the other arm reaching diagonally upward, both legs bent')
add(497, '平衡 · 屈腿双臂上举', '单腿站立支撑，另一条腿向后折起，双臂屈肘举在肩上方', 'balancing on one leg with the other leg folded back behind, both arms bent and raised above the shoulders')
add(498, '平衡 · 后抬腿双臂张开', '单腿站立，一条腿向后抬起，双臂向两侧斜上方大幅张开成展翅状', 'balancing on one leg with the other leg trailing back, both arms opened wide and diagonally upward like spread wings')
add(499, '深蹲 · 抱头深蹲', '双脚并拢深深下蹲，双膝大幅屈曲，双臂从两侧环抱头顶', 'squatting deeply with the feet together and both knees fully bent, the arms wrapping around the top of the head')
add(500, '俯身 · 弯腰双臂下垂', '背对镜头弯腰前俯，双臂松松地朝地面垂直下垂，双膝微屈', 'seen from behind and folded forward at the waist with both arms hanging loosely straight down toward the floor and the knees slightly bent')
add(501, '俯卧 · 俯身双臂后伸', '身体几乎水平前俯，双腿向后伸展，双臂向斜后方举起', 'the body pitched forward almost horizontally with both legs extended back and both arms lifted diagonally behind')
add(502, '站立 · 双拳抵腰', '双脚分开站直，双拳握紧抵在腰侧，肘部向后打开', 'standing with the feet apart and both fists pressed against the sides of the waist, elbows pulled back')
add(503, '站立 · 双臂上举交叠', '站直身体，双臂在胸前斜向上伸出并交叠在一起，头部微微后仰', 'standing upright with both arms raised and crossed together above the chest, the head tilted slightly back')
add(504, '站立 · 分腿侧倾', '双腿分开站立，身体向侧面倾斜，一只手在腰后、另一只手垂在体侧', 'standing with the legs apart and the body leaning to one side, one hand resting behind the waist and the other hanging down')
add(505, '舞蹈 · 高踢双腿上展', '单腿支撑站立，另一条腿向前上方高高踢起，双臂向上展开成扇形', 'balancing on one leg while kicking the other leg high up in front, both arms opened upward in a fan')
add(506, '站立 · 单手举胸前', '双脚分开站直，一只手握拳举到胸前，另一只手叉在腰上', 'standing straight with the feet apart, one fist raised in front of the chest and the other hand on the hip')
add(507, '站立 · 单手抚头侧立', '身体微侧站立，一只手抬到头侧轻抚，另一只手屈肘停在胸前，双腿错开', 'standing slightly turned with one hand lifted to the side of the head and the other arm bent in front of the chest, the legs staggered')
add(508, '站立 · 双臂前平举', '双脚分开站稳，双膝微屈，双臂向前下方平举，手掌相对', 'standing with the feet apart and the knees slightly bent, both arms extended forward and slightly downward with the palms facing each other')
add(509, '平衡 · 弯腰抱腿', '站立时弯腰向下折叠，双臂伸向后方抱住抬起的一条腿，身体成折叠状', 'folded forward at the waist from standing, both arms reaching behind to hold one lifted leg, the body compressed in a fold')
add(510, '平衡 · 侧抬腿单臂高举', '单腿站立，另一条腿向侧方抬起，一只手高举过头，另一只手向斜后摆', 'standing on one leg with the other leg raised out to the side, one arm lifted overhead and the other swinging back')
add(511, '半跪 · 单臂垂直上举', '半跪在地，一只手笔直举向上方，另一只手垂在体侧，跪姿身体挺直', 'kneeling on one knee with the torso upright, one arm raised straight up overhead and the other resting at the side')
add(512, '坐姿 · 空中蹬腿', '仰卧在地面，两条腿在空中屈膝交替蹬出，双臂张开撑住身体', 'on the back with both legs raised and alternating bent-knee kicks in the air while both arms spread out to brace the body')
add(513, '倒立 · 双臂撑地分腿', '双手撑地做倒立，身体倒立，两条腿朝空中分开成大八字', 'handstand with both arms locked and straight, the body inverted and the legs spread wide apart in a large V overhead')
add(514, '平衡 · 抬膝双臂上举', '单腿站立，另一条腿屈膝抬到腰高，双臂向上张开举过头顶', 'balancing on one leg with the other knee raised to waist height and both arms lifted overhead and opened')
add(515, '站立 · 单手扶额错步', '双腿一前一后错步站立，一只手抬到额头处搭着，另一只手垂在身侧', 'standing with the feet staggered front to back, one hand resting on the forehead and the other arm hanging down')
add(516, '弓步 · 低蹲双手前伸', '双腿大幅分开低成弓步，身体下蹲，双手朝前下方伸出去', 'in a deep wide lunge with the body lowered, both arms reaching forward and down')
add(517, '站立 · 单手扶髋分腿', '双腿分开站直，一只手扶在髋骨上，另一只手自然垂放', 'standing straight with the legs apart, one hand resting on the hip and the other arm hanging freely')
add(518, '站立 · 双手交握交叉腿', '双脚交叉站立，双手在身前交握成拳，双臂自然下垂', 'standing with the ankles crossed and both hands clasped together in front of the thighs')
add(519, '行走 · 双臂交替摆动', '向侧前方行走，双臂随步伐一前一后自然摆动，双腿跨开成步', 'walking forward and to the side with both arms swinging alternately in rhythm with the stride')
add(520, '行走 · 双臂屈肘上摆', '向前行走，双臂屈肘向上摆动，前腿抬起重心前移', 'walking forward with both arms bent at the elbows and swinging upward as the lead leg lifts')
add(521, '弓步 · 双拳交替击出', '弓步半蹲，双拳一前一后向前击出，后手收在胸前', 'in a lunging stance with both fists punching forward one after the other, the other fist drawn back at the chest')
add(522, '弓步 · 大跨步前推', '双腿大跨成弓步，一只手向前推出，另一只手垂在体侧，躯干侧转', 'in a long forward lunge with one hand pushing ahead and the other hanging at the side, the torso turned')
add(523, '站立 · 头顶交握成环', '站直身体，双臂弯肘举过头顶，两手在头顶交握成一个环', 'standing upright with both arms bent and raised overhead, the hands clasped together in a ring above the head')
add(524, '侧腰 · 单臂过头下探', '身体向侧方弯腰，一只手从头顶越过伸向另一侧，另一只手向下滑', 'bending sideways with one arm reaching over the head toward the far side while the other arm slides down the leg')
add(525, '深蹲 · 双臂抱头下蹲', '双脚分开深蹲下坐，双膝屈曲，双臂弯肘抱在头后', 'squatting deep with the feet apart, both knees bent and both arms wrapped behind the head')
add(526, '站立 · 双臂交叉前伸', '站直身体，双臂在胸前交叉向前伸出，双腿微分立', 'standing upright with both arms crossed and extended forward in front of the chest, feet slightly apart')
add(527, '平衡 · 单手扶头抬膝', '单腿站立，另一条腿屈膝抬起，一只手扶在头侧，另一只手屈肘于胸前', 'balancing on one leg with the other knee lifted, one hand touching the side of the head and the other arm bent at the chest')
add(528, '站立 · 单臂上举叉腰', '站直身体，一只手向上举过头顶，另一只手叉在腰上，双膝微屈', 'standing with one arm raised straight overhead and the other hand on the hip, the knees slightly bent')
add(529, '深蹲 · 双手撑膝单臂举', '半蹲下坐，双手撑在大腿上，另一只手臂向侧上方举起', 'squatting partway down with both hands braced on the thighs while the other arm lifts out to the side and up')
add(530, '行走 · 侧身屈臂摆动', '背对镜头侧身行走，双臂屈肘前后摆动，双腿一前一后交叉迈步', 'seen from behind while walking sideways, both arms bent and swinging in opposition as the legs cross in stride')
add(531, '后弯 · 单手撑地举臂', '深度后弓成桥状，一只手撑地支撑身体，另一只手向侧上方高举，双腿抬起离地', 'in a deep backbend with one hand planted on the ground and the other arm raised up and out, both feet lifted off the floor')
add(532, '站立 · 单臂屈肘上举', '双脚分开站直，一条手臂屈肘举到肩侧，另一只手垂在身侧', 'standing straight with the feet apart, one arm bent and lifted beside the shoulder and the other hanging at the side')
add(533, '弓步 · 单指前探', '低弓步半蹲，一只手向前伸出用手指探，另一只手撑在大腿上', 'in a low lunge with one hand reaching forward and pointing the fingers out while the other braces on the thigh')
add(534, '奔跑 · 屈肘大步跑', '大步奔跑，一条腿前跨双臂屈肘摆动，另一条腿在身后蹬伸', 'running with a long stride, one leg reaching ahead while both arms bent at the elbows pump and the other leg extends behind')
add(535, '站立 · 单臂绕头后', '站直身体，一只手绕到脑后抓住后颈，双腿交叠站着', 'standing upright with one hand reaching around behind the head to the back of the neck, the legs crossed')
add(536, '弓步 · 一臂上举一臂平', '双腿大开成弓步，一只手向上举过头，另一只手臂向侧面平伸', 'in a wide lunge with one arm raised overhead and the other extended straight out to the side')
add(537, '站立 · 单手前指横臂', '站直身体，一只手向前平伸用手指点，另一只手横搭在腹前', 'standing upright with one hand extended forward pointing a finger and the other arm lying horizontally across the abdomen')
add(538, '站立 · 单手按腹侧倾', '身体向侧方微倾，一只手按在腹部，另一只手撑在髋部', 'leaning slightly to the side with one hand pressed on the abdomen and the other braced on the hip')
add(539, '平衡 · 俯身单腿后抬', '俯身向前倾，一条腿向后抬起，一手扶在头侧，另一只手向下伸展', 'hinging forward at the hips with one leg raised behind, one hand near the side of the head and the other arm reaching down')
add(540, '站立 · 双臂松垂', '双脚分开自然站立，双臂松松垂在身体两侧，视线略向下', 'standing naturally with the feet apart and both arms hanging loosely at the sides, the gaze angled down')
add(541, '站立 · 单臂横胸前', '身体侧对镜头站立，一条手臂横在胸前，另一只手在体侧，双腿错开', 'standing with the body turned sideways, one arm laid horizontally across the chest and the other at the side, legs staggered')
add(542, '站立 · 双臂上举交叉', '双脚分开站直，双臂向上举起并在头顶前方交叉，胸口挺起', 'standing with the feet apart and both arms raised and crossed in front above the head, the chest lifted')
add(543, '站立 · 双拳弯举', '双脚分开站直，双拳屈肘弯举在腰侧，肘部夹紧身体', 'standing with the feet apart and both fists flexed up beside the waist with the elbows tucked in')
add(544, '行走 · 单臂弯举侧走', '侧身行走，一条手臂屈肘弯举在胸前，另一只手在体侧，双腿前后迈', 'walking to the side with one arm flexed up in front of the chest and the other at the side, legs stepping forward and back')
add(545, '倒立 · 头顶地分腿弯', '双手与头顶撑地做倒立，身体完全倒置，两条腿在空中弯曲分开', 'supported headstand with both hands and the crown of the head on the floor, the body fully inverted and both legs bent apart in the air')
add(546, '弓步 · 屈臂前后摆', '大弓步向前奔跑感，双臂屈肘一前一后摆动，后腿蹬直', 'striding forward in a long lunge with both arms bent and swinging one in front of the other, the rear leg extended')
add(547, '弓步 · 双手前推', '双腿分开成半蹲弓步，双手在胸前掌心朝前向前推出', 'in a half squat with the legs apart, both hands pushed forward in front of the chest with the palms facing out')
add(548, '站立 · 单手托颈侧立', '身体侧对镜头站立，一只手抬到颈侧托着，另一只手垂下，双腿错步', 'standing turned sideways with one hand lifted to the side of the neck and the other hanging down, feet staggered')
add(549, '站立 · 交叉腿抱臂', '双脚交叉站立，双臂交抱在胸前，肩部微微后收', 'standing with the ankles crossed and both arms folded across the chest with the shoulders drawn slightly back')
add(550, '行走 · 单臂胸前弯举', '向前行走，一条手臂屈肘弯举停在胸前，双腿一前一后跨步', 'walking forward with one arm flexed and held in front of the chest, the legs stepping one in front of the other')
add(551, '站立 · 举手叉腰', '身体侧转站立，一只手举起停在头侧，另一只手叉在腰后，双腿交叉', 'standing with the body turned, one hand raised beside the head and the other resting on the back of the hip, legs crossed')
add(552, '站立 · 侧身单手前伸', '身体侧对镜头，一只手向前平伸，另一只手叉腰，双腿前后错开', 'standing with the body sideways, one hand extended straight forward and the other on the hip, the legs staggered')
add(553, '站立 · 侧身一臂斜伸', '侧身站立，一只手向斜前方伸出，手掌朝下，双腿一前一后', 'standing sideways with one arm reaching out diagonally forward, the palm facing down, legs split front and back')
add(554, '深蹲 · 双臂弯举下蹲', '双脚分开下蹲，双膝屈曲，双臂屈肘弯举在身体两侧', 'squatting with the feet apart and both knees bent, both arms flexed up along the sides of the body')
add(555, '平衡 · 后折腿单臂展', '单腿站立，一条腿向后折起抬到身后，一只手向上举、另一只手向侧后方展开', 'balancing on one leg with the other folded back and lifted behind, one arm reaching up and the other opening out and back')
add(556, '站立 · 单臂胸前弯举', '站直身体，一条手臂屈肘弯举在胸前，双臂一前一后，另一手自然下垂', 'standing upright with one arm flexed up in front of the chest while the other arm hangs straight down')
add(557, '站立 · 双臂前伸交叠', '双脚分开站直，双臂向前伸出并交叠在一起，双膝微屈', 'standing with the feet apart and the knees slightly bent, both arms extended forward and overlapping each other')
add(558, '平衡 · 后抬腿双臂大幅张', '单腿支撑，一条腿向后抬起，双臂大幅向两侧斜上方张开，头偏向一侧', 'balancing on one leg with the other leg raised behind and both arms opened very wide and diagonally upward, the head tilted to one side')
add(559, '行走 · 单臂前后摆大跨', '大步向前行走，一条手臂向前摆、另一条向斜后摆，双腿跨得很大', 'striding forward in a long step with one arm swinging ahead and the other swinging out behind')
add(560, '器械 · 长矛横扛肩上', '双腿分开站立，双手握一根长矛横搭在肩颈处，矛身横贯身后', 'standing with the feet apart, both hands holding a long spear laid horizontally across the shoulders with the shaft running behind the neck')
add(561, '站立 · 双手抱头后', '站直身体，双臂弯肘上抬，两手交叠抱在头后，肩部打开', 'standing upright with both arms bent upward and the hands clasped behind the head, the shoulders opened')
add(562, '平衡 · 侧卧单手撑地', '身体向侧方倾斜成侧撑，一只手向地面撑住支撑，另一只手臂向上举起，双腿并拢伸直', 'tilted sideways in a one-handed side support with one arm reaching up and the legs together and straight')
add(563, '站立 · 立正双臂微张', '双脚并拢笔直站立，双臂在身体两侧微微离开身面，头部正立', 'standing straight with the feet together and both arms held slightly away from the body, the head upright')
add(564, '站立 · 单臂上举一臂抚后脑', '双脚分开站立，一只手臂上举过头，另一只手臂弯肘把手放在后脑上', 'standing with the feet apart, one arm raised overhead and the other bent with the hand resting on the back of the head')
add(565, '站立 · 侧身单掌外推', '身体侧对镜头站立，一只手掌向外侧推出，另一只手垂在身侧，双腿错步', 'standing with the body sideways, one palm pushed out to the side and the other arm hanging down, legs staggered')
add(566, '弓步 · 双拳防守弯举', '双脚分开半蹲，双拳屈肘举到胸前作防守姿势，肩部收紧', 'in a half squat with the feet apart, both fists flexed up in front of the chest in a guard position')
add(567, '站立 · 交叉腿单臂上举', '双腿交叉站立，一只手臂向上举起，另一只手垂在身前', 'standing with the legs crossed, one arm raised upward and the other hanging in front of the body')
add(568, '行走 · 一臂前伸一臂后摆', '向前行走，一只手臂向前伸出，另一只手臂向斜后方摆动', 'walking forward with one arm reaching ahead and the other swinging diagonally back')
add(569, '器械 · 长杆下压', '双腿大幅分开，双手握一根长杆向下压在身前，身体微俯', 'standing with the legs spread wide, both hands pressing a long pole downward in front of the body as the torso leans forward')
add(570, '站立 · 双拳前推交握', '双脚分开站直，双臂向前平伸，两只手在身前互相交握推出去', 'standing with the feet apart, both arms extended forward with the hands clasped together and pushed out')
add(571, '站立 · 一臂前举一臂侧', '站直身体，一只手臂向前上方举起，另一只手臂向侧方水平伸出', 'standing upright with one arm raised forward and up and the other extended horizontally to the side')
add(572, '行走 · 抬膝双臂摆', '向前行走时抬起一条腿，双臂在身体两侧自然摆动', 'walking forward while lifting one knee, both arms swinging naturally at the sides')
add(573, '深蹲 · 双肘撑膝低头', '深深下蹲，双膝屈曲到极限，双肘撑在大腿上，头部低垂', 'squatting very deep with both knees fully bent, the elbows braced on the thighs and the head dropped')
add(574, '站立 · 单手抱头侧倾', '身体向侧方倾斜站立，一只手弯肘举到头侧，另一只手按在腹前', 'standing with the body leaning to one side, one arm bent up beside the head and the other hand resting in front of the abdomen')
add(575, '行走 · 俯身前垂双手', '身体向前弯垂，双手朝地面下垂，双腿一前一后迈开', 'hinged forward with both arms hanging down toward the floor, the legs split one in front of the other')
add(576, '平衡 · 后折腿双臂上合', '单腿站立，一条腿向后折起，双臂在头顶斜上方交合，躯干微微后仰', 'balancing on one leg with the other folded back, both arms meeting and closing above the head as the torso leans slightly back')
add(577, '支撑 · 蹲姿双手撑地', '蹲低成半跪式支撑，双手撑在大腿前方的地面上，双臂伸直，背部拱起', 'lowered into a crouching support with both hands planted on the ground in front of the thighs, arms straight and the back arched')
add(578, '俯卧撑 · 平板支撑后踢', '身体斜向悬空成平板俯撑，双臂伸直撑地，双腿向后伸直并抬起', 'held in an angled plank with both arms straight and the legs extended back and lifted off the ground')
add(579, '深蹲 · 深蹲双臂上举交叠', '双脚并拢深深下蹲，双臂向上举过头顶并在前方交叠成环', 'squatting deeply with the feet together, both arms raised overhead and crossed together into an arch')
add(580, '舞蹈 · 双手撑地双腿腾空', '双手撑在地面上，身体腾空旋转，一条腿向上伸直，另一条腿弯曲', 'both hands planted on the ground with the body airborne in a rotation, one leg extended straight up and the other leg bent')
add(581, '弓步 · 大开步双臂平展', '双腿大幅分开成大弓步，双臂向两侧水平平举展开，躯干侧转', 'in a very wide lunge with both arms stretched out horizontally to the sides and the torso turned')
add(582, '坐姿 · 悬空撑地屈腿', '半躺悬空坐姿，双手在身后撑地支撑，双腿屈曲抬起并向一侧偏移', 'reclining in a supported seat with both hands planted behind, both legs bent and lifted, shifted to one side')
add(583, '奔跑 · 屈臂交叉步', '向前奔跑，双腿交叉跨步，双臂屈肘前后快速摆动', 'running forward with the legs crossing mid-stride and both arms bent at the elbows pumping')
add(584, '平衡 · 勾脚提腿双展臂', '单腿站立，另一条腿屈膝向前提起并勾住脚尖，双臂向两侧张开保持平衡', 'balancing on one leg with the other knee drawn up in front and the toes pointed, both arms spread out to the sides for balance')
add(585, '奔跑 · 前伸手臂交跑', '向前奔跑，双腿交叉迈步，一只手臂向前伸出，另一只手臂屈肘在胸前', 'running forward with crossing steps, one arm reaching out ahead and the other bent in front of the chest')
add(586, '俯身 · 双手垂地', '弯腰俯身，双臂松松垂向地面，双膝微屈，头部向下', 'bent forward at the waist with both arms hanging loosely down toward the ground, knees slightly bent and head lowered')
add(587, '器械 · 扛棍奔跑', '奔跑向前，一只手把一根长棍扛在肩上，棍身斜指身后，后腿蹬地', 'running forward with one hand carrying a long pole across the shoulder, the pole angled out behind as the rear leg pushes off')
add(588, '器械 · 持棍侧劈', '双腿大跨开站定，双手握一根长棍向侧方斜劈下来，身体随之扭转', 'standing with the legs spread wide and both hands swinging a long pole down diagonally to the side as the body turns with it')
add(589, '器械 · 单手抓杆单腿勾', '一只手抓住立杆，一条腿勾住杆身向上抬起，身体离地斜向伸展', 'gripping a vertical pole with one hand and hooking one leg up around it, the body lifted and stretched out diagonally')
add(590, '器械 · 双腿夹杆悬垂', '身体贴着一根立杆悬起，双腿一上一下夹住杆身，双臂向两侧张开', 'suspended against a vertical pole with the legs clamped one above and one below the shaft, both arms spread out to the sides')
add(591, '器械 · 倒挂双腿交替', '双手抓着一根立杆，身体倒挂向上，双腿一弯一伸交替打开', 'hanging upside down from a vertical pole with both hands, the legs opened and bent alternately')
add(592, '器械 · 横杆水平悬垂展腿', '身体水平悬挂在一根横杆上，双腿向两侧大幅分开成大V形', 'hanging horizontally from a bar with the legs spread very wide apart into a big V')
add(593, '器械 · 横杆侧挂伸腿', '身体斜着挂在一根横杆上，一条腿勾住杆身，另一条腿向斜上方伸直', 'hanging at an angle from a bar with one leg hooked over it and the other leg extended straight up and out')
add(594, '器械 · 坐地撑杆后仰', '坐在地上，双臂向后撑住立杆把身体撑开，躯干后仰双腿前伸', 'seated on the floor with both arms braced behind against a vertical pole, the chest opened and the torso leaning back with the legs extended forward')
add(595, '器械 · 低蹲扶杆', '蹲低在立杆旁，一手扶着杆身，双膝屈曲收在胸前', 'crouched low beside a vertical pole with one hand resting on the shaft and both knees drawn up')
add(596, '器械 · 横杆俯卧展体', '身体俯卧横跨在一根横杆上，双腿向两侧张开下垂', 'lying prone across a horizontal bar with the legs opened out to the sides and hanging down')
add(597, '蹲姿 · 双肘撑膝俯首', '蹲低成蹲姿，双肘撑在膝盖上，头部深深低下，背部弓起', 'crouched low with both elbows resting on the knees and the head dropped so far that the back is rounded')
add(598, '站立 · 单手扶大腿', '双腿分开站直，一只手按在大腿外侧，另一只手垂在身前', 'standing straight with the legs apart, one hand resting on the outside of the thigh and the other hanging in front')
add(599, '平衡 · 侧抬腿单手过头', '单腿站立，另一条腿向侧方水平抬起，一只手举过头顶，另一只手叉在腰上', 'balancing on one leg with the other leg lifted out horizontally to the side, one arm raised above the head and the other on the hip')
add(600, '舞蹈 · 后折腿双臂前探', '单腿站立，另一条腿向后折起，双臂向前上方斜伸出去，身体微微后仰', 'balancing on one leg with the other folded back behind, both arms reaching diagonally forward and up as the body leans slightly back')