# sheet 02-07: idx 40-159
add(40, '站立 · 举拳屈臂叉腰', '正面站立，右臂屈肘举拳至头侧，左手叉腰', 'front view standing with the right arm bent up in a fist beside the head and the left hand on the hip')
add(41, '站立 · 单臂侧平扬掌', '侧身站立，右臂向侧后方平伸，掌心朝上，头微侧', 'standing in three-quarter view with one arm extended out to the side palm up and the head turned slightly')
add(42, '腾跃 · 单腿后踢探臂', '腾空跃起，左腿向后屈踢，双臂前上方探出', 'mid-air leaping with one leg kicked back bent and both arms reaching forward and up')
add(43, '前倾 · 交叉步掠臂', '上身前倾，双腿交叉成弓步，一臂向后方高处甩出', 'leaning the torso forward with the legs crossed in a lunge and one arm swung back and up')
add(44, '站立 · 双臂水平展开', '正面站立，双腿微微分开，双臂向两侧水平伸直', 'front view standing with legs slightly apart and both arms stretched straight out to the sides')
add(45, '低蹲 · 双臂外张屈肘', '深低蹲姿，膝盖弯曲，双臂向两侧张开、肘部弯曲', 'in a deep squat with the knees bent and both arms spread out to the sides with elbows bent')
add(46, '后弯 · 单臂上举挺胸', '身体向后挺出胸腔，一臂高举过头顶，双膝微屈', 'arching the torso backward with the chest open and one arm reaching overhead, knees slightly bent')
add(47, '跳跃 · 单臂高举屈膝', '腾空跳跃，一臂向上高举，另一臂侧平，双腿屈膝后收', 'jumping with one arm raised high, the other extended sideways and both knees bent back')
add(48, '平衡 · 单腿前抬双臂前伸', '单腿站立支撑，另一腿向前抬起，双臂前伸交叠', 'balancing on one leg with the other leg raised forward and both arms extended in front')
add(49, '仰卧 · 双臂上举双腿交举', '仰卧在地，双臂向上举直，一条腿伸直上抬、另一条屈膝', 'lying on the back with both arms raised straight up, one leg extended up and the other knee bent')
add(50, '俯卧 · 四肢抬起游泳姿', '俯卧伸直身体，双臂前伸，双腿屈膝向上翘起', 'lying prone with the body straight, arms reaching forward and both legs bent upward')
add(51, '深蹲 · 前伸双手探地', '半蹲成弓步，双臂向前下方伸出，指尖朝地', 'in a half squat lunge with both arms reaching forward and down toward the floor')
add(52, '低弓步 · 单手触地后蹬', '一腿屈膝下蹲、一腿向后蹬直，一手撑在地面', 'in a low lunge with one knee bent, the back leg extended straight and one hand touching the ground')
add(53, '平衡 · 单腿侧举一手扶足', '单腿站立，另一腿向侧上方大幅抬起，一手抓住抬起的脚', 'standing on one leg while lifting the other high out to the side and holding the raised foot with one hand')
add(54, '站立 · 双臂上举成环', '单脚重心站立，双臂在头顶上方弯成圆环', 'standing on one foot with both arms curved into an oval ring above the head')
add(55, '站立 · 单臂绕弧上伸', '身体侧倾，一臂绕过头顶上方，另一臂向侧下方伸展', 'leaning sideways with one arm arcing over the head and the other reaching down and out')
add(56, '奔跑 · 大步跨开双臂展平', '大幅跨步奔跑，双腿前后分开，双臂向两侧展开', 'running with a long stride, legs split front and back and both arms spread wide')
add(57, '撑地 · 侧身单臂撑起', '侧身俯卧撑起，一只手撑住地面，另一臂向上举起', 'holding a side support on one hand with the body turned side-on and the other arm raised upward')
add(58, '平衡 · 俯身单腿后折', '单腿站立，上身俯向前方，另一腿向后上方折起', 'balancing on one leg with the torso folded forward and the other leg bent up behind')
add(59, '站立 · 双手贴身垂放', '正面自然站立，双臂垂放在身体两侧', 'standing neutrally front-on with both arms hanging relaxed at the sides')
add(60, '行走 · 抬手招呼', '正面行走，一手高举向外招呼，另一臂向侧下方摆动', 'walking forward with one hand raised high in a wave and the other arm swinging down and out')
add(61, '站立 · 绕臂上举叉腰', '一臂弯过头顶向上，另一手叉腰，双腿前后错开', 'standing with one arm curving up over the head, the other hand on the hip and the feet staggered')
add(62, '倒立 · 腾空分腿翻转', '身体倒立腾空，双腿向两侧分开成剪刀状', 'inverted in mid-air with the legs split wide apart in a scissor shape')
add(63, '弓步 · 单臂斜指前推', '单膝跪地成弓步，一臂向斜前上方指出去，另一臂收在体侧', 'in a kneeling lunge with one arm reaching diagonally forward and up while the other rests at the side')
add(64, '平衡 · 单腿后折一臂前伸', '单腿站立，另一腿向后屈起，一臂向前伸出', 'standing on one leg with the other leg bent up behind and one arm reaching forward')
add(65, '站立 · 绕臂侧倾交叉步', '双腿交叉站立，一臂绕过头顶，身体向侧方倾斜', 'standing with the legs crossed, one arm arcing over the head and the body tilted sideways')
add(66, '站立 · 双臂垂直上举', '正面站立，双臂伸直高举过头顶', 'standing front-on with both arms extended straight up above the head')
add(67, '站立 · 横臂斜指', '一臂横过胸前向斜上方指出，另一臂自然下垂', 'with one arm crossing the chest to point diagonally upward and the other arm relaxed at the side')
add(68, '深蹲 · 双臂前平伸', '双脚分开半蹲，双臂向正前方平直伸出', 'in a half squat with the feet apart and both arms extended straight forward')
add(69, '前屈 · 俯身双臂下探', '上身前倾，双臂向下伸出探向地面', 'bending the torso forward with both arms reaching down toward the ground')
add(70, '站立 · 屈臂上举托肘', '一臂屈肘举至头顶、掌心向上，另一手托住该侧髋部', 'standing with one arm bent and lifted palm up beside the head and the other hand resting on the hip')
add(71, '前屈 · 双手向前推出', '上身向前倾斜，双臂在身前斜向下方推出', 'leaning the torso forward with both arms reaching out and down in front of the body')
add(72, '站立 · 侧平指引', '一手叉腰，另一臂向侧方平伸、手掌外翻', 'standing with one hand on the hip and the other arm extended sideways with the palm turned out')
add(73, '交叉腿 · 双臂侧展平衡', '单腿支撑，另一腿膝部外展交叉，双臂向两侧展开', 'balancing on one leg with the other knee opened out to the side and both arms spread wide')
add(74, '跳跃 · 屈腿单臂上冲', '腾空跃起，一臂向上伸直，支撑腿屈膝后提', 'leaping into the air with one arm shooting straight up and the supporting leg bent and lifted')
add(75, '深蹲 · 前伸手掌外推', '半蹲身体前倾，双臂前伸、双掌朝外推开', 'in a forward-leaning half squat with both arms reaching ahead and the palms pressing outward')
add(76, '站立 · 叉腰重心后坐', '双手叉腰，膝盖弯曲、重心向后坐，躯干微后仰', 'standing with both hands on the hips, knees bent and the weight shifted back with the torso leaning slightly behind')
add(77, '平衡 · 单腿后折单臂高举', '单腿站立，另一腿向后折起，一臂高举过头', 'standing on one leg with the other folded back and one arm raised overhead')
add(78, '站立 · 双手扶后脑', '正面站立，双肘外展，双手扶在后脑勺上', 'standing front-on with both elbows flared out and the hands placed behind the head')
add(79, '俯身 · 双手扶膝前倾', '上身前倾，双手分别按在两侧膝盖上', 'leaning the torso forward with both hands pressing on the knees')
add(80, '站立 · 单臂屈举侧倾', '身体向侧面弯曲，一臂屈肘举到头侧，另一手叉腰', 'bending sideways with one arm flexed up beside the head and the other hand on the hip')
add(81, '行走 · 侧摆手臂', '行走中一臂向侧后方摆动，另一臂在身前屈起', 'walking with one arm swinging back to the side and the other bent in front of the chest')
add(82, '舞动 · 侧倾双臂展', '身体侧向倾斜，双腿错步，双臂向两侧展开', 'dancing with the body tilted sideways, the feet staggered and both arms spread open')
add(83, '舞动 · 前倾单臂后展', '上身前倾，一臂向侧后方伸展，另一臂收在胸前', 'dancing with the torso leaning forward, one arm reaching out behind and the other drawn in front')
add(84, '杂技 · 单腿竖直上举', '上体前俯，一腿向上竖直举起，双臂向侧面撑开', 'balancing with the torso folded forward, one leg raised straight up and both arms spread out to the sides')
add(85, '卧姿 · 抬腿展臂翻滚', '仰卧屈膝，双腿向上分开抬起，双臂向两侧张开', 'on the back with the knees bent and both legs lifted apart, arms opened wide to the sides')
add(86, '平衡 · 单腿前伸双臂横展', '单腿站立，另一腿向斜前方伸出，双臂向两侧展开', 'balancing on one leg with the other leg extended forward and outward and both arms spread to the sides')
add(87, '深蹲 · 宽距下蹲双拳架起', '双脚大幅分开下蹲，膝外展，双拳在身前架起', 'in a wide deep squat with the knees pushed out and both fists raised in front of the chest')
add(88, '弓步 · 宽展劈腿单臂上扬', '双腿大幅分开成弓步，一臂高举，另一臂向侧下方伸出', 'in a wide striding lunge with one arm raised high and the other reaching down and out')
add(89, '手撑 · 倒立分腿', '双手撑地身体倒立，双腿向两侧分开', 'in a handstand with the legs spread wide apart to the sides')
add(90, '站立 · 背身开立屈臂', '背对镜头站立，双腿分开，双臂屈肘举在胸前', 'standing with the back to the viewer, legs apart and both arms bent up in front of the chest')
add(91, '低蹲 · 单手探地侧头', '深蹲身体低垂，一只手朝地面伸出，头向另一侧倾斜', 'in a low crouch with one hand reaching toward the floor and the head tilted to one side')
add(92, '跃起 · 屈腿后蹬展臂', '腾空跃起，后腿屈膝蹬起，双臂向两侧伸展', 'leaping into the air with the back leg bent and pushing off and both arms extended outward')
add(93, '半跪 · 双手抱头弓背', '单膝跪地弓着背，双手抱在头后，肘部外展', 'kneeling on one knee with the back rounded and both hands clasped behind the head, elbows flared out')
add(94, '仰卧 · 双足过头抱膝', '仰卧蜷起身体，双脚举到头顶上方，双手抱住小腿', 'lying on the back curled up with both feet raised above the head and the hands holding the shins')
add(95, '站立 · 后仰单臂斜举', '身体后仰，一臂向斜上方举起，另一臂向侧方展开', 'leaning back with one arm raised diagonally and the other arm spread out to the side')
add(96, '站立 · 交叉步单臂外展', '双腿交叉站立，一臂向侧上方展开，另一手叉腰', 'standing with the legs crossed, one arm opened out and up to the side and the other hand on the hip')
add(97, '站立 · 单臂直举侧立', '身体侧向站立，一臂伸直高举', 'standing turned to the side with one arm extended straight up')
add(98, '平衡 · 抬腿屈膝臂绕头', '单腿站立，另一腿屈膝抬起，一臂绕过头顶上方', 'balancing on one leg with the other knee lifted and one arm curving over the head')
add(99, '舞动 · 交叉步双臂前伸', '双腿交叉成弓步，双臂向斜前方一同伸出', 'dancing with the legs crossed in a lunge and both arms reaching out together in front')
add(100, '手撑 · 单腿垂直支撑', '一只手撑地，另一条腿向上笔直伸直成倒立', 'in a one-handed handstand with one leg extended straight up')
add(101, '平衡 · 单腿后折一臂侧展', '单腿站立，另一腿向后屈起，一臂向侧方展平', 'standing on one leg with the other bent up behind and one arm extended straight to the side')
add(102, '半跪 · 单臂上举侧展', '半跪在地，一臂向侧上方举起，另一臂向旁展开', 'kneeling on one leg with one arm raised up and to the side and the other arm opened out beside it')
add(103, '平衡 · 抬腿绕臂侧倾', '单腿支撑，另一腿抬起，一臂绕过头顶、身体侧倾', 'balancing on one leg with the other lifted, one arm arcing over the head and the body leaning sideways')
add(104, '弓步 · 腾空跨步一臂上扬', '向前腾空跨出一大步，一臂高举过头', 'leaping forward into a long stride with one arm raised high above the head')
add(105, '跳跃 · 双臂上举交叉腿', '向上跃起，双臂在头顶张开，双腿在空中交叉', 'jumping upward with both arms opened above the head and the legs crossed in mid-air')
add(106, '弓步 · 宽蹲双臂前推', '双脚分开屈膝下蹲，双臂向正前方用力推出', 'in a wide squat with the knees bent and both arms pushing straight forward')
add(107, '平衡 · 单腿后举手扶头', '单腿站立，另一腿向后折起，一手扶在头侧', 'standing on one leg with the other folded up behind and one hand resting beside the head')
add(108, '站立 · 双肘外展双手搭头', '正面站立，双臂抬起，双肘向两侧张开、双手靠近头部', 'standing front-on with both arms raised so the elbows flare outward and the hands hover near the head')
add(109, '手撑 · 倒立屈膝', '双手撑地成倒立，双膝弯曲向胸前收拢', 'in a handstand with both knees bent and drawn up toward the chest')
add(110, '站立 · 双臂交叠圆肩', '正面站立，双臂在胸前交叠，肩膀向前内收', 'standing front-on with the arms folded across the chest and the shoulders rolled forward')
add(111, '站立 · 抱胸侧立交叉腿', '双臂抱在胸前，一腿交叉站到另一腿前，身体侧向', 'standing with the arms folded across the chest and one leg crossed in front of the other, body turned sideways')
add(112, '站立 · 双手托后脑', '正面站立，双臂上举、双手托住后脑，双肘宽展', 'standing front-on with both arms raised and the hands cradling the back of the head, elbows wide open')
add(113, '弓步 · 低蹲单臂上举', '低弓步半蹲，一臂向斜上方举起，另一臂撑在大腿上', 'in a low lunging squat with one arm raised diagonally and the other braced on the thigh')
add(114, '深蹲 · 双手垂地深屈膝', '深蹲到大腿接近水平，双手垂向地面', 'squatting deep until the thighs are near horizontal with both hands hanging down toward the floor')
add(115, '跳跃 · 双臂大展交叉腿', '腾空跃起，双臂向两侧大幅展开，双腿在空中交叠', 'jumping into the air with both arms spread wide and the legs crossed together in mid-air')
add(116, '站立 · 单手抚头侧身', '身体侧向站立，一手抬起扶在头后，另一臂向旁伸出', 'standing turned to the side with one hand lifted behind the head and the other arm reaching out')
add(117, '手撑 · 倒立开腿', '双手撑地倒立身体，双腿分开向两侧伸直', 'in a handstand with both legs extended and spread wide apart')
add(118, '跳跃 · 双臂上冲屈腿', '向上腾空跳起，双臂高举，一腿屈膝后收', 'jumping upward with both arms raised and one leg bent and drawn up behind')
add(119, '跳跃 · 单臂高举跨步', '跨步跳跃中，一臂高举向上，另一臂向侧平伸', 'leaping in a stride with one arm raised high and the other extended horizontally to the side')
add(120, '平衡 · 单腿抬膝双臂展开', '单腿站立，另一腿屈膝抬到体侧，双臂向两侧展开', 'balancing on one leg with the other knee lifted to the side and both arms spread outward')
add(121, '站立 · 屈臂侧摆', '正面站立，一臂屈肘向侧上方摆动，另一臂弯在体侧', 'standing front-on with one arm swung bent up and to the side and the other arm bent near the body')
add(122, '平衡 · 单腿抬膝一臂下压', '单腿支撑，另一腿屈膝抬起，一臂向斜下方压', 'balancing on one leg with the other knee raised and one arm pressing down diagonally')
add(123, '站立 · 单臂上举交叉腿', '双腿交叉站立，一臂屈肘举到头后上方', 'standing with the legs crossed and one arm bent and lifted up behind the head')
add(124, '弓步 · 大跨步俯身展臂', '双腿大幅分开成弓步，上身向一侧俯倾，双臂向身后下方伸展', 'in a long wide lunge with the torso tilted to one side and both arms reaching back and down')
add(125, '站立 · 单臂上举侧展', '正面站立，一臂斜向上举，另一臂向侧面平伸', 'standing front-on with one arm raised diagonally and the other extended horizontally to the side')
add(126, '站立 · 侧倾双臂下压', '身体向侧方倾斜，双臂同时向斜下方压', 'leaning the body sideways with both arms pressing down and outward on the same side')
add(127, '站立 · 抬腿垂臂', '单腿站立，另一条腿抬起，双臂自然垂在身体两侧', 'standing on one leg with the other leg lifted and both arms hanging relaxed at the sides')
add(128, '站立 · 双手肩上推举', '正面站立，双臂弯曲、双手举到肩部两侧向上推', 'standing front-on with both arms bent and the hands raised beside the shoulders in a press-up position')
add(129, '站立 · 双臂水平外展', '正面站立，双臂向两侧水平伸直张开', 'standing front-on with both arms extended straight out horizontally to the sides')
add(130, '平衡 · 单腿折叠双臂前伸', '单腿支撑，另一腿向后折叠抬起，双臂向前伸出', 'balancing on one leg with the other folded up behind and both arms reaching forward')
add(131, '奔跑 · 腾空屈腿摆臂', '向前腾空奔跑，一腿屈膝后提，双臂前后摆动', 'sprinting forward into the air with one leg bent and lifted behind and the arms swinging fore and aft')
add(132, '行走 · 单臂上举侧展', '向前行走，一臂向斜上方举起，另一臂向侧方摆开', 'walking forward with one arm raised diagonally up and the other arm swung out to the side')
add(133, '站立 · 双掌下按身前', '正面站立，双肘弯曲，双手在身前向下按压', 'standing front-on with both elbows bent and the palms pressing downward in front of the body')
add(134, '站立 · 双臂前推', '正面站立，双臂向正前方平行推出', 'standing front-on with both arms pushing straight out in front of the body')
add(135, '平衡 · 单腿站立单臂直举', '单腿站立支撑，另一条腿抬起贴地，一臂向上直举', 'standing on one leg with the other lifted close to the ground and one arm extended straight up')
add(136, '行走 · 抬手前行', '正面向前行走，一臂屈肘抬到胸前，另一臂自然摆动', 'walking forward with one arm bent and lifted to chest height while the other arm swings naturally')
add(137, '站立 · 屈臂仰头叉腰', '一臂屈肘举到头后、头略后仰，另一手叉腰', 'with one arm bent and raised behind the head, the chin tipped back and the other hand on the hip')
add(138, '站立 · 侧身一手叉腰', '侧身站立，一手叉腰，另一臂垂在体侧，双腿错开', 'standing turned to the side with one hand on the hip, the other arm hanging down and the feet staggered')
add(139, '站立 · 仰头单臂上举', '身体略后仰，头抬起，一臂向侧上方高举', 'leaning slightly back with the head tilted up and one arm raised high to the side')
add(140, '行走 · 双臂展平', '行走向前，双臂向两侧平展打开', 'walking forward with both arms opened out flat to the sides')
add(141, '平衡 · 单腿折叠双臂下压', '单腿站立，另一腿弯折抬起，双臂向斜下方压', 'standing on one leg with the other bent and lifted while both arms press down and outward')
add(142, '站立 · 双臂侧平举', '正面站立，双腿并立，双臂向两侧平举', 'standing front-on with the legs together and both arms raised out horizontally to the sides')
add(143, '深蹲 · 蹲低单臂外伸', '极低蹲姿，一腿深屈，一臂向侧方伸出、另一手触地', 'in a very deep crouch with one leg fully bent, one arm reaching out to the side and the other hand near the floor')
add(144, '站立 · 单手抚额侧立', '侧身站立，一只手抬起横在额前，另一臂向下方伸出', 'standing turned to the side with one hand raised across the forehead and the other arm reaching down')
add(145, '站立 · 背身单臂高举', '背对镜头站立，一臂伸直高举过头顶', 'standing with the back to the viewer and one arm extended straight up overhead')
add(146, '平衡 · 交腿双臂环胸前', '双腿交叉站立，双臂在胸前交叠成环', 'standing with the legs crossed and both arms folded into a rounded shape across the chest')
add(147, '站立 · 搭肩含胸', '一臂横过胸前搭在肩侧，身体微微含胸', 'with one arm crossing the chest to rest on the shoulder and the upper body slightly rounded forward')
add(148, '站立 · 单臂上举开步', '双腿分开站立，一臂向上直举，头转向一侧', 'standing with the feet apart and one arm extended straight up, the head turned to one side')
add(149, '站立 · 双臂上举成V', '正面站立，双腿交叉，双臂向斜上方张开成V形', 'standing front-on with the legs crossed and both arms opened into a wide v shape overhead')
add(150, '站立 · 单臂高举交叉腿', '双腿交叉站立，一臂高举过头顶', 'standing with the legs crossed and one arm raised high above the head')
add(151, '俯身 · 一手叉腰一手下垂', '上身向前俯倾，一手叉腰，另一臂向下垂落', 'leaning the torso forward with one hand on the hip and the other arm hanging down')
add(152, '平衡 · 单腿抬起双臂侧展', '单腿站立，另一条腿屈膝抬起，双臂向两侧斜上方展开', 'balancing on one leg with the other knee lifted and both arms spread diagonally upward to the sides')
add(153, '倒立 · 单臂支撑分腿', '单手撑地倒立身体，另一臂张开，双腿向两侧分开', 'inverted on one hand with the other arm opened out and the legs spread wide apart')
add(154, '前屈 · 双手垂下拱背', '从髋部向前深弯，双臂松垂向下，背部拱起', 'folding forward deeply from the hips with the arms hanging loose and the back rounded')
add(155, '俯卧 · 单腿后踢', '俯卧在垫上，双臂撑地，一条腿向上后踢', 'lying prone with both arms braced on the floor and one leg kicked up behind')
add(156, '四足跪 · 单腿后抬', '四足着地爬姿，一条后腿向上抬起', 'on all fours with one hind leg lifted up behind the body')
add(157, '深蹲 · 俯身双手撑地', '深蹲前倾，双手撑在地面上，抬头看前方', 'in a deep forward squat with both hands planted on the floor and the head lifted looking ahead')
add(158, '低蹲 · 双手垂地侧身', '低身下蹲身体侧转，双手垂向地面', 'crouching low with the body turned to the side and both hands reaching down toward the ground')
add(159, '深蹲 · 单手撑地侧撑', '深蹲并以一只手撑地，另一臂向侧上方伸出', 'in a deep squat braced on one hand with the other arm extended up and to the side')
