# sheet 08-15: idx 160-319
add(160, '跳跃 · 屈腿展臂', '腾空跃起，双腿一前一后屈曲，双臂分别斜向上方和侧前方张开', 'mid-leap with both knees bent and the legs trailing, one arm reaching up-diagonally and the other opening forward')
add(161, '站立 · 单臂高举抬腿', '单腿支撑站立，另一条腿屈膝抬起，一只手直举过头', 'balancing on one leg with the other knee lifted, one arm reaching straight overhead')
add(162, '站立 · 单臂侧平举', '双脚分开站立，一只手向侧前方水平伸出，另一只手垂在身侧', 'standing with feet apart, one arm extended horizontally to the side and the other hanging down')
add(163, '弓步 · 屈臂后撤', '前腿屈膝弓步，后腿屈膝后撤，一只手屈肘举到肩侧', 'in a crouched lunge with the front knee bent and the rear knee tucked under, one arm flexed up beside the shoulder')
add(164, '站立 · 双腿开立展臂', '双腿大幅分开站立，一臂斜举过头，另一臂向侧方平伸', 'standing in a wide straddle, one arm lifted diagonally overhead and the other stretched out sideways')
add(165, '站立 · 抬膝勾手', '单腿站立，另一条腿屈膝抬到髋部高度，一手向下勾指', 'standing on one leg with the other knee raised to hip height, one hand reaching downward with fingers curled')
add(166, '坐地 · 屈腿后撑', '坐在地面上双腿屈曲折叠，一手撑在身后支撑上身', 'seated on the floor with both legs folded, one hand planted behind to prop up the torso')
add(167, '站立 · 高侧踢', '单腿支撑，另一条腿向侧上方高高踢出，一臂上指一手下垂', 'standing on one leg while kicking the other leg high out to the side, one arm pointing up and the other hanging down')
add(168, '半跪 · 交臂前伸', '后腿跪地前腿屈膝，双臂在身前交叠向前伸出', 'kneeling on the rear knee with the front knee bent, both arms crossed and extended forward in front of the chest')
add(169, '半跪 · 单臂上举', '双腿分开跪地，一只手高举过头，另一只手向侧方伸展', 'kneeling with the knees apart, one arm raised overhead and the other extended out to the side')
add(170, '半跪 · 屈臂上撑', '后腿跪地，一只手屈肘向上撑起，另一只手向前下方按落', 'kneeling on the rear leg, one arm propped upward with a bent elbow and the other pressing down and forward')
add(171, '站立 · 单臂上扬侧倾', '站立时上身向一侧倾斜，一只手斜举过头顶，另一只手向侧前方伸出', 'standing with the torso tilted to one side, one arm raised diagonally overhead and the other reaching out to the front side')
add(172, '平衡 · 展体侧倾', '单腿支撑，另一条腿向后侧抬起，双臂水平展开，上身前倾', 'balancing on one leg with the other leg swept back and out, both arms spread horizontally as the torso tips forward')
add(173, '跳跃 · 屈膝扬臂', '腾空时一腿屈膝抬起，一只手屈肘举过头顶，另一只手向后拉开', 'airborne with one knee raised high, one arm flexed above the head and the other pulled back behind the body')
add(174, '站立 · 侧举屈臂', '双腿分开站立，一只手向侧方平举，另一只手屈肘弯到肩上', 'standing with the legs apart, one arm extended out to the side and the other flexed up near the shoulder')
add(175, '平衡 · 侧举腿', '单腿站立，另一条腿向侧后方向斜举，一只手向上伸出', 'balancing on one leg while lifting the other leg diagonally out and back, one arm reaching upward')
add(176, '站立 · 双手抱头', '双脚分开站立，双手都放到后脑上，肘部向两侧张开', 'standing with feet apart and both hands resting behind the head, elbows flared out to the sides')
add(177, '站立 · 单臂绕头', '双腿开立，一只手绕到头顶上方，另一只手向下伸向大腿', 'standing with legs apart, one arm curved over the top of the head and the other reaching down toward the thigh')
add(178, '站立 · 双拳上举', '侧身站立，双拳屈肘举到肩部两侧，一腿微微弯起', 'standing in a slight turn with both fists flexed up beside the shoulders and one leg lightly bent')
add(179, '深蹲 · 俯首按膝', '深蹲屈膝，双臂向前下方伸出，双手按住大腿，视线向下', 'in a deep squat with both arms reaching forward to press the thighs, head angled down toward the knees')
add(180, '半跪 · 单臂上指', '后腿跪地前腿屈起，一只手伸直向上指，另一只手撑在前腿上', 'kneeling on the rear knee with the front leg bent, one arm reaching straight up and the other resting on the raised thigh')
add(181, '半跪 · 挥臂上举', '后腿跪地，身体侧转，一只手握拳高举过头', 'kneeling on one knee with the torso turned sideways, one fist raised high above the head')
add(182, '站立 · 前倾指天', '双脚分开站立，上身前倾，一只手举起在脸旁竖起手指', 'standing with feet apart and the torso leaning forward, one hand lifted beside the face with fingers raised')
add(183, '站立 · 抱臂侧倾', '双腿交叉站立，一只手横抱在胸前，另一只手垂落，上身微侧', 'standing with the legs crossed, one arm folded across the chest and the other hanging down, torso angled slightly')
add(184, '站立 · 单臂过头', '单腿站立，另一条腿屈膝后勾，一只手弯过头顶，另一只手向下', 'standing on one leg with the other knee bent and hooked behind, one arm curving over the head and the other reaching down')
add(185, '站立 · 侧身抚颌', '侧身站立，一手抬到下颌处轻托，另一只手横在腰前', 'standing in profile with one hand raised to the chin and the other held across in front of the waist')
add(186, '站立 · 提膝举拳', '单腿支撑，另一条腿屈膝抬到腰际，一只手握拳举到肩前', 'balancing on one leg with the other knee lifted to waist level, one fist held up in front of the shoulder')
add(187, '侧弓步 · 展臂斜伸', '双腿大幅分开侧向跨步，一只手斜举过头，另一只手向体侧下垂', 'in a wide side lunge with one arm reaching diagonally overhead and the other dropping toward the hip')
add(188, '跳跃 · 单臂上冲', '双脚离地跃起，一只手握拳向上冲出，双腿一前一后屈起', 'leaping off the ground with one fist punching upward and both legs tucked, one forward and one back')
add(189, '平衡 · 后踢展臂', '单腿站立，另一条腿向后屈起，一只手向前伸出，另一只手向后拉开', 'balancing on one leg with the other bent behind, one arm reaching forward and the other pulled back')
add(190, '手撑倒立 · 直腿侧分', '一手撑地倒立，一条腿竖直向上，另一条腿向侧方伸直打开', 'in a one-handed handstand with one leg straight up and the other leg opened straight out to the side')
add(191, '站立 · 叉腰交腿', '双腿交叉站立，一手叉腰，另一只手横在腹前', 'standing with the legs crossed, one hand on the hip and the other resting across the front of the belly')
add(192, '坐地 · 单臂上撑', '坐在地面上双腿屈起，一只手撑地，另一只手向上伸出', 'seated on the ground with both knees bent, one hand braced behind and the other arm reaching up')
add(193, '行走 · 摆臂迈步', '双腿前后跨步站立，一只手屈肘摆到肩侧，另一只手自然后摆', 'standing mid-stride with the legs apart, one arm swung up beside the shoulder and the other trailing behind')
add(194, '站立 · 扶后脑侧身', '侧身站立，一手扶住后脑勺，另一只手搭在体侧', 'standing in profile with one hand resting on the back of the head and the other arm down at the side')
add(195, '站立 · 仰身扶发', '双腿交叉站立，双手抬到头顶撩起头发，肩部后展', 'standing with the legs crossed and both hands lifted into the hair, shoulders drawn back and the chest lifted')
add(196, '站立 · 交腿掩面', '单腿站立，另一条腿的脚踝交叉到支撑腿前，一手举到脸侧', 'standing on one leg with the other ankle crossed in front, one hand raised beside the face')
add(197, '背面 · 双臂展V字', '背对镜头站立，双臂向斜上方张开成V字，双腿并拢', 'seen from behind with both arms raised diagonally in a wide V and the legs together')
add(198, '站立 · 单臂上举侧展', '双脚分开站立，一只手举过头顶，另一只手向侧方水平伸出', 'standing with the feet apart, one arm raised overhead and the other extended horizontally to the side')
add(199, '行走 · 单手叉腰', '迈步向前，一手叉腰，另一只手向身后摆，双腿前后交错', 'stepping forward with one hand on the hip and the other arm swung behind, legs staggered forward and back')
add(200, '站立 · 双臂屈举', '双脚分开站立，双臂屈肘弯举到肩部两侧，前臂向上', 'standing with feet apart and both arms flexed upward beside the shoulders with the forearms raised')
add(201, '站立 · 交腿双臂过头', '单腿站立，另一条腿屈膝交叉到支撑腿前，双臂在头顶交叠', 'standing on one leg with the other knee crossed in front, both arms crossed and lifted overhead')
add(202, '站立 · 抬膝绕臂', '单腿支撑，另一条腿屈膝抬起，一只手弯过头顶，另一只手向下', 'balancing on one leg with the other knee raised, one arm curving over the head and the other reaching down')
add(203, '站立 · 正面叉腰', '正面站立，双腿分开，一手叉腰，另一只手垂在腿侧', 'facing forward with the legs apart, one hand on the hip and the other arm hanging by the thigh')
add(204, '站立 · 抬腿曲臂', '单腿支撑，另一条腿向后屈起，一手抬到脸旁，另一手屈肘向外', 'balancing on one leg with the other bent up behind, one hand raised beside the face and the other arm flexed outward')
add(205, '站立 · 直腿侧踢', '单腿站立，另一条腿向侧方伸直踢出，一手抬到下巴处', 'standing on one leg while extending the other straight out to the side, one hand lifted to the chin')
add(206, '平衡 · 弯腿后勾', '单腿支撑，另一条腿屈膝向上后勾，双臂屈起挡在脸前', 'balancing on one leg with the other leg bent and hooked up behind, both arms flexed up in front of the face')
add(207, '蹲姿 · 单手撑地抬腿', '低蹲成球形，一手撑地，另一腿向上弯折抬起', 'in a deep tuck squat with one hand on the ground and the other leg bent and lifted upward')
add(208, '侧卧 · 屈肘撑身', '侧身卧地，一只手屈肘撑起上身，另一条腿向上屈起', 'lying on the side propped up on one elbow, the other leg bent and raised above the hip')
add(209, '坐地 · 单腿竖起', '坐地一腿伸直，另一条腿竖直向上，一只手在身后撑地', 'seated on the floor with one leg extended and the other raised straight up, one hand braced behind')
add(210, '俯身 · 前倾展臂', '身体几乎水平前倾，双臂向后展开，双腿伸直支撑', 'with the torso tipped almost horizontal forward, both arms stretched back behind and the legs straight')
add(211, '蹲跳 · 后伸手臂', '屈膝腾空起跳，一只手向侧前方伸出，另一只手向后拉开', 'springing up from bent knees with one arm reaching forward to the side and the other pulled back')
add(212, '手撑 · 侧翻抬腿', '一手撑地，身体侧向翻转成横姿，一条腿向后上方弯起', 'supported on one hand with the body rotated sideways into a horizontal line and one leg bent upward behind')
add(213, '前屈 · 双手够脚踝', '上身前屈，双膝微屈，双手向下伸到脚踝处', 'folded forward at the hips with the knees slightly bent and both hands reaching down to the ankles')
add(214, '站立 · 单手后脑叉腰', '侧身站立，一手扶住后脑，另一只手叉在腰上', 'standing in profile with one hand on the back of the head and the other hand on the waist')
add(215, '半蹲 · 单手掩口', '半蹲屈膝，一只手抬到嘴边，另一只手向下伸出', 'in a half squat with one hand raised to the mouth and the other arm reaching down')
add(216, '站立 · 交臂并腿', '双腿交叉站立，双臂在身前交叠环抱，肩部内收', 'standing with the legs crossed and both arms folded around each other in front of the chest')
add(217, '站立 · 叉腰侧首', '双腿分开站立，一手叉腰，另一只手抬起靠近脸侧，头转向一侧', 'standing with legs apart, one hand on the hip and the other raised near the face with the head turned to one side')
add(218, '站立 · 平举横臂', '站立时一只手臂横在胸前水平伸出，另一只手垂在身侧', 'standing with one arm held horizontally across the chest and the other arm relaxed at the side')
add(219, '跳跃 · 后仰甩臂', '腾空后仰，一只手弯过头顶向后甩，双腿一前一后抬离地面', 'leaping with the torso arched back, one arm flung up and over behind the head and both legs lifted clear of the ground')
add(220, '深蹲 · 抱膝低头', '深蹲成蹲踞，双臂环抱小腿，头部低垂贴近膝盖', 'in a deep squat hugging the shins with both arms wrapped around the legs and the head bowed to the knees')
add(221, '后弯 · 单臂撑展', '身体后仰成弓形，一只手向上伸出撑开，另一只手向腿侧伸展', 'arching the torso backward into a bow shape with one arm reaching up and the other stretching toward the leg')
add(222, '站立 · 掩口叉腰', '正面站立，一手抬到嘴前，另一只手叉腰', 'standing facing forward with one hand raised in front of the mouth and the other hand on the hip')
add(223, '站立 · 单臂绕头侧身', '侧身站立，一只手弯过头顶向下，另一只手横在身前', 'standing in profile with one arm curving over the head and the other held across the front of the body')
add(224, '蹲姿 · 屈臂抬膝', '低蹲成团，一手屈肘举到头顶，另一手向下撑地，膝部抬起', 'in a low tuck squat with one arm flexed above the head and the other bracing down, a knee lifted high')
add(225, '行走 · 掩面迈步', '双腿前后交叠迈步，一手抬到脸旁，另一手垂在体侧', 'walking with the legs crossed in a staggered step, one hand raised beside the face and the other at the side')
add(226, '弓步 · 单拳上举侧身', '前腿屈膝大弓步后腿伸直，一只手握拳举到肩侧，身体侧转', 'in a deep lunge with the front knee bent and back leg straight, one fist raised beside the shoulder as the torso turns sideways')
add(227, '弓步 · 屈臂开肩', '大幅弓步双腿分开，一手屈肘弯举在头侧，另一手向下伸出', 'in a wide lunge with one arm flexed up beside the head and the other reaching down toward the floor')
add(228, '站立 · 上指转身', '双腿分开站立，一手横在胸前，另一只手高举竖起手指', 'standing with the legs apart, one hand held across the chest and the other raised high with the fingers pointing up')
add(229, '平衡 · 屈腿后举臂', '单腿支撑，另一条腿屈膝在身后勾起，一只手举过头顶上方', 'balancing on one leg with the other hooked up behind at the knee, one arm lifted above the head')
add(230, '手撑倒立 · 分腿展臂', '单手撑地倒立，双腿向两侧分开呈剪刀状，一手向上伸展', 'in a one-handed handstand with the legs scissored apart to the sides and one arm extended upward')
add(231, '跳跃 · 水平俯冲', '身体腾空成水平俯冲姿态，双臂向前方伸出，双腿向后绷直', 'airborne in a horizontal diving position with both arms reaching forward and both legs extended straight back')
add(232, '站立 · 双臂合掌', '单腿支撑，另一条腿向后屈起，双手在头顶合拢相贴', 'balancing on one leg with the other bent behind, both hands pressed together above the head')
add(233, '跳跃 · 前伸探身', '腾空屈膝，双臂一前一后伸向前方探出，躯干前倾', 'airborne with the knees bent and both arms reaching forward in succession as the torso tips ahead')
add(234, '站立 · 直臂举天', '双腿分开站立，一只手直臂举向天顶，另一只手屈肘放在胸前', 'standing with the legs apart, one arm stretched straight up toward the sky and the other flexed across the chest')
add(235, '后仰 · 屈臂后靠', '上身后仰头部后仰，一只手屈肘举在肩侧，双腿前后错开屈膝', 'leaning back with the head tipped behind and one arm flexed beside the shoulder, both knees bent in a staggered stance')
add(236, '站立 · 单手上举叉腰', '双腿分开站立，一只手举过头顶，另一只手叉在腰上', 'standing with the legs apart, one arm raised overhead and the other hand resting on the hip')
add(237, '站立 · 举臂侧展', '双脚分开站立，一只手屈肘举高，另一只手向侧下方伸展', 'standing with the feet apart, one arm flexed and raised high and the other extended down and out to the side')
add(238, '行走 · 掌心前推', '侧身迈步，一手在腰侧，另一只手向前伸出掌心朝上，头部侧倾', 'stepping sideways with one hand at the waist and the other extended forward palm up, head tilted to one side')
add(239, '平衡 · 侧举摆臂', '单腿支撑，另一条腿在身后屈起，一只手向斜上方摆出', 'balancing on one leg with the other bent up behind, one arm swung out diagonally upward')
add(240, '站立 · 交叉双腿', '正面站立，双腿在脚踝处交叉，双臂垂在身体两侧', 'standing facing forward with the ankles crossed and both arms hanging loosely at the sides')
add(241, '站立 · 侧胯站姿', '侧身站立，一手叉腰，双腿一前一后交叠，身体重心落在一侧髋部', 'standing in profile with one hand on the hip, legs overlapped and the weight settled onto one hip')
add(242, '站立 · 侧平举绕臂', '双腿交叉站立，一只手水平伸向侧方，另一只手弯过头顶', 'standing with the legs crossed, one arm extended horizontally to the side and the other curved over the head')
add(243, '后仰 · 双臂后展', '上身后仰头后仰，双臂向身体后方展开，一腿屈起', 'leaning the torso back with the head dropped behind and both arms opened out behind the body, one leg bent')
add(244, '站立 · 侧身抚发', '侧身站立，一手绕到脑后撩住头发，另一只手垂在体侧', 'standing in profile with one hand reaching behind the head into the hair and the other arm down at the side')
add(245, '站立 · 对角展臂', '双腿分开站立，一只手斜举向头顶上方，另一只手向另一侧斜下方伸展', 'standing with the legs apart, one arm reaching diagonally up and the other stretching diagonally down to the opposite side')
add(246, '弓步 · 侧向开臂', '前腿屈膝弓步，上身侧转，一手抬到脸旁，另一手向侧方张开', 'in a lunge with the front knee bent and the torso turned, one hand raised beside the face and the other opened out to the side')
add(247, '站立 · 屈臂叉腰', '双腿分开站立，一手叉腰，另一只手屈肘弯过头顶', 'standing with the legs apart, one hand on the hip and the other arm flexed up over the head')
add(248, '侧倾 · 单腿侧抬', '身体向一侧倾斜，一条腿向侧方抬起，双臂向下垂展', 'tipping the torso to one side while lifting a leg out to the side, both arms hanging and extended downward')
add(249, '跪坐 · 双手前伸', '跪坐在脚跟上，双臂向前下方伸出，双手靠向地面', 'kneeling back on the heels with both arms reaching forward and down toward the ground')
add(250, '站立 · 双臂直举', '正面站立，双腿并拢，双臂贴耳直直举过头顶', 'standing facing forward with the legs together and both arms raised straight up close to the ears')
add(251, '坐姿 · 单臂上举', '低坐屈膝，一手撑地支撑，另一只手向上举起', 'seated low with the knees bent, one hand bracing on the ground and the other arm raised upward')
add(252, '半跪 · 斜举手臂', '半跪在地，一只手向斜上方举起，另一只手在胸前屈起', 'kneeling on one knee with one arm raised diagonally upward and the other flexed in front of the chest')
add(253, '站立 · 单臂上举框形', '双腿分开站立，一只手臂向上直举，另一只手屈肘扶在头侧', 'standing with the legs apart, one arm raised straight up and the other bent with the hand resting beside the head')
add(254, '侧卧 · 屈腿抬脚', '侧身卧地，一腿向上屈起抬高手臂撑起上身，另一腿伸直', 'lying on the side with one leg bent and lifted high, propped on one arm, the other leg extended straight')
add(255, '平衡 · 单腿侧开', '单腿支撑，另一条腿向侧方伸直打开，一只手竖直举过头顶', 'balancing on one leg while extending the other straight out to the side, one arm raised vertically overhead')
add(256, '弓步 · 单臂上引', '大幅弓步双腿分开，一只手向上斜举引展，另一只手向下按落', 'in a wide lunge with one arm reaching diagonally up and the other pressing down toward the floor')
add(257, '弓步 · 反弓展臂', '前腿深屈弓步，一手绕过头顶向后展开，头部向后上方仰起', 'in a deep lunge with one arm curved back over the head and the chin lifted to look up behind')
add(258, '平衡 · 抬膝开臂', '单腿支撑，另一条腿屈膝抬起，一手向上举高，一手向侧方张开', 'balancing on one leg with the other knee lifted, one arm raised high and the other opened out to the side')
add(259, '后弯 · 提腿翻仰', '上半身向后翻转，一条腿向上抬起，手臂向上牵引身体', 'flipping the torso backward with one leg lifted upward and an arm reaching up to pull the body through')
add(260, '平衡 · 抬腿开臂', '单腿支撑，另一条腿屈膝压在支撑腿内侧，一只手举高一手侧平', 'balancing on one leg with the other knee bent against the inside of the standing leg, one arm raised and the other level')
add(261, '平衡 · 交叉腿举臂', '单腿站立，另一条腿的脚背贴在支撑腿小腿上，一只手举过头顶', 'standing on one leg with the other foot resting against the calf, one arm raised above the head')
add(262, '平衡 · 双臂过头', '单腿支撑，另一条腿向后屈起，双臂在头顶弯成弧线', 'balancing on one leg with the other bent behind, both arms curved overhead into an arc')
add(263, '站立 · 环臂绕头', '双腿前后错步站立，双臂在头部上方交环绕成圆环', 'standing with the legs staggered, both arms circling and crossing above the head to form a ring')
add(264, '弓步 · 双手交叠头上', '大弓步前腿屈膝，双臂抬起在头顶交叠，肘部向两侧打开', 'in a wide lunge with the front knee bent, both arms lifted and crossed above the head with the elbows flared out')
add(265, '平衡 · 抬膝举手', '单腿支撑，另一条腿屈膝抬起，双臂在头顶交叠成菱形', 'balancing on one leg with the other knee raised, both arms crossed overhead forming a diamond shape')
add(266, '侧弯腰 · 单臂上展', '双腿分开站立，上身向一侧弯倾，一只手向斜上方伸展，另一只手下滑到腿侧', 'standing with legs apart and the torso bent sideways, one arm reaching diagonally up and the other sliding down the leg')
add(267, '平衡 · 展体后伸', '单腿支撑，另一条腿向后伸直抬起，双臂向两侧展开', 'balancing on one leg with the other extended straight back, both arms spread out to the sides')
add(268, '平衡 · 侧展抱头', '单腿站立，另一条腿屈膝在身前交叠，一手抱头一手向侧伸展', 'standing on one leg with the other knee bent and crossed in front, one hand on the head and the other extended sideways')
add(269, '前屈 · 单手够踝', '上身前屈，一手向下伸到脚踝，另一只手绕过头顶向后打开', 'folded forward with one hand reaching down to the ankle and the other arm curving back over the head')
add(270, '站立 · 双臂开肩', '双腿大幅分开站立，双臂向两侧水平打开，头部转向一侧', 'standing in a wide straddle with both arms opened horizontally to the sides and the head turned to one side')
add(271, '跳跃 · 跨步飞身', '腾空跨步，一手向上举起，另一手向侧方伸展，双腿前后分开', 'leaping through the air with one arm raised and the other stretched sideways, the legs split front and back')
add(272, '半跪 · 托腮侧身', '后腿跪地，一手抬到下巴处，另一手叉在腰上，上身侧转', 'kneeling on the rear knee with one hand raised to the chin and the other on the hip, torso turned sideways')
add(273, '跪姿 · 双手上举', '跪姿屈膝，双臂在头顶交叠上举，一侧脚跟抬起', 'kneeling with the knees bent and both arms crossed and raised overhead, one heel lifted')
add(274, '平衡 · 提膝摆手', '单腿支撑，另一条腿屈膝抬起，一手向前伸出，另一手向后摆', 'balancing on one leg with the other knee lifted, one arm reaching forward and the other swinging back')
add(275, '蹲姿 · 前伸手臂', '低蹲屈膝，双臂向正前方伸出，手掌相对靠拢', 'in a low squat with both arms extended forward, the palms facing each other and held close')
add(276, '蹲姿 · 单手撑地', '蹲成低姿，一手撑地，另一条腿向侧后抬起，手臂向外打开', 'in a low crouch with one hand braced on the ground and the opposite leg lifted out to the back and the arm opened wide')
add(277, '蹲姿 · 双手下探', '深蹲屈膝，双臂向前下方伸直探出，头部抬起看向前方', 'in a deep squat with both arms reaching straight forward and down while the head lifts to look ahead')
add(278, '平衡 · 前举后平臂', '单腿支撑，另一条腿在身后屈起，一手高举过头，另一手向侧后平伸', 'balancing on one leg with the other bent up behind, one arm raised overhead and the other extended level behind')
add(279, '舞蹈 · 单臂划弧', '单腿站立，另一条腿屈膝抬起，一只手向斜上方划出弧线', 'standing on one leg with the other knee raised, one arm sweeping an arc diagonally upward')
add(280, '弓步 · 单臂上举', '前腿屈膝弓步，一只手直臂举过头顶，另一只手向侧方伸出', 'in a lunge with the front knee bent, one arm stretched straight overhead and the other extended out to the side')
add(281, '站立 · 叉腰举拳', '双腿分开站立，一手叉腰，另一只手握拳举到肩侧', 'standing with the legs apart, one hand on the hip and the other fist raised beside the shoulder')
add(282, '平衡 · 抬膝平举', '单腿支撑，另一条腿屈膝抬起，一手水平伸向前方，另一手扶在腰间', 'balancing on one leg with the other knee lifted, one arm extended level in front and the other hand at the waist')
add(283, '蹲姿 · 顶髋下撑', '屈膝深蹲，一手绕过头顶，另一手向下撑地，一条腿向外抬起', 'in a deep crouch with one arm curved over the head and the other pressing down to the ground, one leg lifted out to the side')
add(284, '站立 · 双腿开立举臂', '双腿大幅分开站立，一只手向上高举，另一只手垂在身侧', 'standing with the legs spread wide, one arm raised high overhead and the other hanging at the side')
add(285, '半蹲 · 屈臂展肩', '半蹲屈膝重心下沉，一只手屈肘举过头顶，另一只手向侧方抬起', 'in a half squat with the weight lowered, one arm flexed above the head and the other lifted out to the side')
add(286, '宽蹲 · 单臂平举', '双腿大幅分开屈膝下蹲，一只手水平平举，另一只手屈肘弯举', 'in a very wide squat with one arm extended horizontally and the other flexed upward beside the shoulder')
add(287, '半跪 · 单手上撑', '后腿跪地前腿屈起，一手向上举起，另一手扶在前膝上', 'kneeling on the rear knee with the front leg bent, one arm raised upward and the other hand resting on the front knee')
add(288, '平衡 · 抬腿举臂', '单腿支撑，另一条腿向前抬起伸直，一只手举过头顶', 'balancing on one leg with the other lifted and extended straight forward, one arm raised overhead')
add(289, '半跪 · 侧举长弓', '后腿跪地后腿向后伸直，一只手向斜上方举起，躯干侧转打开', 'kneeling on one knee with the back leg extended straight behind, one arm raised diagonally upward and the torso rotated open')
add(290, '站立 · 举臂侧倾', '侧身站立，一只手向斜上方举起，上身向另一侧倾', 'standing in profile with one arm raised diagonally upward and the torso leaning to the opposite side')
add(291, '站立 · 举臂交叉腿', '双腿交叉站立，一手高举过头，另一只手扶在腰侧', 'standing with the legs crossed, one arm raised overhead and the other hand resting at the waist')
add(292, '跪姿 · 侧臂后仰', '跪坐后仰，一手向侧方伸出，另一手在胸前屈起，头部后仰', 'kneeling and leaning back with one arm extended to the side and the other flexed at the chest, head tipped behind')
add(293, '坐地 · 横叉开臂', '坐地双腿横向打开成横叉，一只手向上举起，另一只手向侧方伸出', 'seated on the floor in a wide side split with one arm raised and the other extended to the side')
add(294, '站立 · 双手扶髋', '正面站立，双腿分开，双手同时扶在两侧腰髋上', 'standing facing forward with the legs apart and both hands resting on the hips')
add(295, '平衡 · 深抬膝冠臂', '单腿支撑，脚尖踩稳，另一条腿屈膝抬到髋部，一手在头顶弯成半圆', 'balancing on one leg with the toes grounded, the other knee lifted to hip height and one arm arched into a half circle over the head')
add(296, '平衡 · 屈膝举臂', '单腿支撑，另一条腿在身后屈起，一手向上举起，一手向前伸出', 'balancing on one leg with the other bent up behind, one arm raised upward and the other extended forward')
add(297, '平衡 · 冠臂提膝', '单腿支撑，另一条腿屈膝抬起，一手在头顶弯成环形', 'balancing on one leg with the other knee raised, one arm curved into an arch over the head')
add(298, '站立 · 抱臂含胸', '双腿交叉站立，双臂环抱在胸前，肩部微微内含', 'standing with the legs crossed and both arms wrapped around the chest, shoulders drawn in slightly')
add(299, '站立 · 交叉腿叉腰', '正面站立，双腿交叉，一手叉腰，另一只手垂在体侧', 'standing facing forward with the legs crossed, one hand on the hip and the other arm down at the side')
add(300, '站立 · 屈臂摆动', '双腿分开站立，一只手屈肘弯在胸前，另一只手向侧下方摆出', 'standing with the legs apart, one arm flexed across the chest and the other swung out down and to the side')
add(301, '站立 · 掩面叉腰', '正面站立，一手抬到脸旁，另一手叉在腰上', 'standing facing forward with one hand raised beside the face and the other hand on the hip')
add(302, '前屈 · 双手背后', '上身前屈，双臂背到身后交握，双腿交叉站立', 'folded forward at the hips with both arms clasped behind the back and the legs crossed')
add(303, '平衡 · 抬腿弯臂', '单腿支撑，另一条腿屈膝抬起，一手弯过头顶，另一手垂在体侧', 'balancing on one leg with the other knee lifted, one arm curved over the head and the other hanging at the side')
add(304, '平衡 · 双臂展平', '单腿支撑，另一条腿在身后屈起，双臂向两侧水平展开', 'balancing on one leg with the other bent up behind, both arms extended horizontally to the sides')
add(305, '站立 · 扶头叉腰', '双腿分开站立，一手扶住后脑，另一只手叉在腰上', 'standing with the legs apart, one hand on the back of the head and the other on the hip')
add(306, '平衡 · 后踢屈臂', '单腿支撑，另一条腿向后伸直踢起，一只手屈肘举在肩前', 'balancing on one leg while kicking the other straight out behind, one arm flexed up in front of the shoulder')
add(307, '蹲姿 · 单臂绕头', '屈膝深蹲，一手弯过头顶向后，另一手向下伸出', 'in a deep squat with one arm curved back over the head and the other reaching down')
add(308, '站立 · 单臂后屈', '双腿分开站立，一只手臂屈肘向后弯到腰后，另一手垂在身侧', 'standing with the legs apart, one arm bent back behind the waist and the other hanging at the side')
add(309, '站立 · 侧展抱头', '侧身站立，一手抱头，另一只手向侧方平伸，一腿交叉', 'standing in profile with one hand on the head and the other extended level to the side, one leg crossed')
add(310, '蹲姿 · 侧伸抬腿', '屈膝半蹲，一手向侧方平伸，另一手向下撑地，一条腿外展抬起', 'in a half squat with one arm extended to the side and the other braced down, the opposite leg lifted out to the side')
add(311, '手撑倒立 · 单腿上冲', '单手撑地，一条腿竖直向上，另一条腿屈膝收拢在体侧', 'in a one-handed handstand with one leg punched straight up and the other bent and tucked close to the body')
add(312, '平衡 · 上举侧平臂', '单腿支撑，另一条腿在身后屈起，上身侧倾，一手向上举高，另一手向侧方展开', 'balancing on one leg with the other bent behind and the torso tilted sideways, one arm reaching up and the other opened out to the side')
add(313, '平衡 · 抬腿展臂', '单腿支撑，另一条腿向前抬起，双臂向两侧张开保持平衡', 'balancing on one leg with the other lifted forward, both arms opened out to the sides for balance')
add(314, '侧撑 · 前臂支撑', '侧身以前臂撑地，身体斜向撑起，一条腿向外伸直', 'propped on one forearm with the body held diagonally up and one leg extended straight out')
add(315, '深蹲 · 双手撑地', '深蹲成蹲踞，双臂伸到两腿之间双手撑地，头部低垂', 'in a deep squat with both arms reaching between the legs to the floor, head bowed down')
add(316, '前屈 · 单臂下探', '上身前屈几乎与地面平行，一只手向下伸向脚踝，另一只手向后打开', 'folded forward with the torso nearly parallel to the floor, one hand reaching down to the ankle and the other opened back')
add(317, '站立 · 侧倾伸臂', '双腿分开站立，上身向一侧弯倾，一只手向斜上方伸展', 'standing with the legs apart and the torso bent sideways, one arm reaching out diagonally upward')
add(318, '行走 · 双臂侧展', '双腿前后交错迈步，双臂向两侧微微展开保持平衡', 'stepping with the legs staggered and both arms opened slightly out to the sides for balance')
add(319, '站立 · 单手侧指', '侧身站立，一手向侧前方伸出指，另一只手垂在体侧，一腿交叉', 'standing in profile with one hand pointing out forward to the side and the other at the hip, one leg crossed')
