# sheet 16-23: idx 320-479
add(320, '平衡 · 侧倾双腿腾空', '身体向侧方倾倒失去平衡，双臂向两侧甩开，双腿一前一后离地蜷起', 'tipping sideways off balance with both arms flung out and both legs lifted and curled off the ground')
add(321, '行走 · 交叉步侧身', '侧身向前行走，双腿前后交叉迈步，双臂沿身侧自然摆动', 'walking in profile with the legs crossing mid-stride and the arms swinging loose at the sides')
add(322, '站立 · 单臂高举挥动', '站直身体，一只手高举过头顶做出挥手动作，另一只手在胸前平举', 'standing upright with one arm raised high overhead in a wave and the other hand held flat in front of the chest')
add(323, '站立 · 双手抱头交踝', '双脚脚踝交叉站立，双手交叠抱在头顶上方', 'standing with the ankles crossed and both hands clasped together on top of the head')
add(324, '站立 · 单臂斜举握拳', '一腿微屈支撑，另一腿向侧后方点地，一臂斜向上举成拳', 'standing on one slightly bent leg with the other foot pointed to the side, one arm raised diagonally upward in a clenched fist')
add(325, '站立 · 双手掩面低头', '双脚并拢站直，低头的同时用双手遮住面部', 'standing with the feet together and the head bowed while both hands cover the face')
add(326, '深蹲 · 单臂上勾', '深蹲压低重心，一只手向上勾肘抬起，另一只手向地面下探', 'in a deep squat with the weight lowered, one arm hooked upward at the elbow and the other reaching down toward the floor')
add(327, '站立 · 单手抱头侧倚', '一手绕到脑后扶着颈后，另一手叉在腰间，躯干微微侧倾', 'standing with one hand behind the head and the other on the hip, the torso leaning slightly to the side')
add(328, '跪姿 · 双臂上举开胸', '单膝跪地成弓步，胸口打开，双臂向斜上方大幅张开', 'kneeling in a lunge with the front knee bent, the chest open and both arms raised wide overhead')
add(329, '深蹲 · 双臂前推', '蹲到最低点，双脚分开踩实，双臂同时向前上方推出，手掌朝外', 'squatting low with the feet planted apart and both arms pushed forward and upward, palms facing out')
add(330, '深蹲 · 抱腿团身', '低低蹲下蜷成一团，双臂环抱住小腿，额头靠近膝盖', 'curled into a compact low squat with both arms wrapped around the shins and the forehead close to the knees')
add(331, '地面 · 俯卧抬腿', '俯卧在地面上，双前臂撑地，一条腿向后高高抬起', 'lying prone on the ground, propped on both forearms, with one leg lifted high behind')
add(332, '站立 · 叉腰勾脚', '一手叉腰，另一条腿屈膝向后勾起脚跟，上身微微后仰', 'standing with one hand on the hip and the other leg bent so the heel lifts back toward the glutes, the torso tipped slightly back')
add(333, '站立 · 单臂前指', '一脚交叉到身前站稳，一手叉腰，另一只手向前平伸指出', 'standing with one foot crossed in front of the other, one hand on the hip and the other arm reaching straight out forward')
add(334, '站立 · 交臂点脚', '双臂在胸前交叠，上身直立，一只脚在身后轻轻点地', 'standing tall with both arms folded across the chest and one foot lightly pointed up behind')
add(335, '站立 · 抬膝侧展', '单腿站立，另一条腿屈膝向侧外打开，双手扶在髋部', 'balancing on one leg with the other knee opened out to the side and both hands resting on the hips')
add(336, '站立 · 叉腰伸腿仰头', '双手叉腰，一腿向前伸直绷脚，头部后仰看向斜上方', 'standing with both hands on the hips, one leg extended forward with a pointed foot and the head tipped back to look upward')
add(337, '站立 · 双手叉腰正面', '正面对镜头站直，双脚微分外展，双手同时撑在腰胯两侧', 'standing squarely facing the viewer with the feet slightly apart and both hands planted on the hips')
add(338, '站立 · 抚臂侧头', '身体略侧，一手扶髋，另一只手搭在对侧肩上，头向一侧偏转', 'standing slightly turned to the side with one hand on the hip and the other hand resting on the opposite shoulder, head tilted away')
add(339, '站立 · 双指上指', '双脚分开站定，双肘弯曲抬起，双手食指同时朝上指出', 'standing with the feet apart, both elbows bent and raised, and both index fingers pointing straight up')
add(340, '行走 · 交叉步垂臂', '正面迈步行走，双腿交替交叉，双臂垂在身侧微微后摆', 'walking toward the viewer with the legs crossing in front of each other and the arms hanging back at the sides')
add(341, '弓步 · 屈膝侧身', '一腿向前屈膝成弓步，另一腿蹬地伸直，躯干侧转，双臂自然摆动', 'in a lunge with the front knee bent and the back leg extended straight, the torso turned to the side and the arms loose')
add(342, '站立 · 屈臂后仰', '双脚平行站立，双臂屈肘抬到腰侧，胸部向后挺起', 'standing with the feet parallel, both elbows bent at the waist and the chest pushed back')
add(343, '站立 · 双腕交于颌前', '侧身站立，双腕在身体前方交叠抬起至下巴位置', 'standing in profile with both wrists crossed and lifted up in front of the body to chin height')
add(344, '站立 · 双臂屈肘上扬', '双脚微分站立，双臂向上弯曲抬起，两手在头顶上方张开', 'standing with the feet slightly apart, both arms raised and bent so the hands open above the head')
add(345, '舞蹈 · 提膝摆臂', '一腿提起屈膝，另一腿支撑，双臂一前一后摆动，身体上下起伏', 'dancing with one knee lifted and the other leg supporting, the arms swinging one in front of the other')
add(346, '站立 · 前倾迈步', '躯干前倾，重心落在前移的腿上，双臂自然下垂随步伐摆动', 'leaning the torso forward over the advancing leg with both arms hanging down and swinging with the step')
add(347, '站立 · 抚额侧身', '侧身站立，一手抬起按在额头前，另一手叉腰，双腿前后分开', 'standing in profile with one hand pressed to the forehead and the other on the hip, the feet staggered apart')
add(348, '站立 · 勾脚叉腰', '一腿支撑，另一条腿屈膝勾起脚尖，一手叉腰，另一手随身前摆', 'standing on one leg with the other knee bent and the toe pointed up, one hand on the hip while the other arm swings forward')
add(349, '行走 · 侧步回望', '侧身横向迈出一步，头扭向后方回望，双臂一前一后自然摆动', 'stepping sideways while the head twists back to look behind, the arms swinging front and back')
add(350, '奔跑 · 后撤步回身', '身体向后撤步扭转，一手向后甩臂，头部回转向后', 'twisting the body in a backward retreating step with one arm flung behind and the head turned back')
add(351, '弓步 · 大步侧压', '大步分开成宽弓步，前腿屈膝后腿绷直，一手叉腰并向侧面推出', 'in a wide striding lunge with the front knee bent and the back leg straight, one hand on the hip pressing out to the side')
add(352, '舞蹈 · 侧踢腿', '单腿支撑，另一条腿向斜侧高高踢出，支撑臂上举、踢腿臂下摆', 'balancing on one leg while the other leg kicks high out to the side, the supporting arm raised and the kicking arm lowered')
add(353, '舞蹈 · 腾空后仰', '双腿腾空离地，身体向后仰起，双臂一前一后大幅展开', 'airborne with both feet off the ground, the torso arched backward and both arms spread wide')
add(354, '舞蹈 · 抬膝勾手', '一腿屈膝抬起，支撑腿微蹲，双臂弯肘在胸前勾手上抬', 'dancing with one knee lifted and the supporting leg in a slight squat, both arms bent at the elbows and hooked upward in front of the chest')
add(355, '舞蹈 · 单腿展臂', '单腿站立，另一腿屈膝向外打开，双臂一高一低向两侧展开', 'balancing on one leg with the other knee opened out, both arms extended to the sides at different heights')
add(356, '站立 · 侧身合掌前伸', '侧身站立，双掌在胸前合拢并向前推出，颈部后仰', 'standing in profile with both palms pressed together and pushed out in front of the chest, the neck tilted back')
add(357, '站立 · 屈臂举拳', '正面站定，双臂屈肘举到肩侧，两手握拳，肘部向外撑开', 'facing forward with both arms bent up beside the shoulders, hands clenched into fists and elbows flared outward')
add(358, '站立 · 拄杖侧倚', '一只手拄着直立的杆杖辅助支撑，身体重心侧压在同侧腿上', 'leaning sideways with one hand resting on a tall upright pole for support, the weight on the same-side leg')
add(359, '武术 · 持剑侧举', '双手握住长剑横举在胸前，身体侧向站立，双腿前后分立', 'holding a longsword with both hands across the front of the chest, the body in profile with the feet staggered')
add(360, '武术 · 持枪弓步刺', '双手握长枪向前下方刺出，前腿屈膝成弓步，后腿蹬直', 'thrusting a long spear forward and downward with both hands, the front leg bent in a lunge and the back leg straight')
add(361, '武术 · 双手握棍下压', '双手握长棍斜向下压，双腿左右分开微蹲，躯干侧对前方', 'pressing a long staff downward at an angle with both hands, the feet apart in a slight squat and the body turned sideways')
add(362, '行走 · 屈臂含胸', '低头含胸向前行走，双臂屈肘收在躯干两侧', 'walking forward with the head down and the chest rounded, both arms bent and held close to the sides')
add(363, '武术 · 仰身举棍', '上身后仰，一手将长棍高举过头顶，双腿前后大开', 'arching the torso back with one arm lifting a long staff overhead and the feet spread wide front to back')
add(364, '跳跃 · 单手举棍腾空', '身体腾空跃起，一只手把长棍高高举过头顶，双腿收离地面', 'leaping into the air with one arm holding a long staff high overhead and both feet clear of the ground')
add(365, '武术 · 斜举长刀', '双手握长刀斜举向斜上方，双腿宽分开成站立架势', 'raising a long sword diagonally overhead with both hands while standing with the feet spread wide')
add(366, '武术 · 双手持棍斜劈', '双手持棍从斜上方劈向斜下方，前腿屈膝弓步，重心下沉', 'chopping a long staff down diagonally from above with both hands, the front knee bent in a lunge and the weight lowered')
add(367, '武术 · 弓步持棍平推', '一腿在前屈膝成弓步，双手持长棍水平向前推出', 'in a lunge with the front knee bent, pushing a long staff straight forward horizontally with both hands')
add(368, '武术 · 立姿持棍上举', '双脚并立站直，双手把长棍竖直举在面前，棍身贴向脸侧', 'standing straight with the feet together, both hands holding a long staff upright in front of the face')
add(369, '弓步 · 单手前伸后拉', '一腿向后伸直，前腿弓步下沉，一只手向前伸，另一只手向后拉', 'in a lunge with the back leg straight, one arm reaching forward and the other pulling backward')
add(370, '倒立 · 单臂撑地', '单手撑地倒立，身体侧向绷直，双腿并拢向上伸直', 'balancing upside down on one straight arm with the body held rigid and both legs extended upward together')
add(371, '蹲姿 · 持棍横撑', '低蹲屈膝，握着一根长杆横在身前，肩部靠住杆身', 'crouched low with a long pole held horizontally across the front and one shoulder braced against it')
add(372, '倒立 · 攀柱屈腿', '双手攀住竖直柱子倒挂身体，双腿弯曲收向腹部', 'hanging upside down from a vertical pole with both hands, the legs bent and tucked toward the abdomen')
add(373, '倒立 · 头手撑柱倒挂', '头与双手一起撑在竖直柱上倒挂，双腿向上分开伸直', 'inverting with the head and both hands braced on a vertical pole, the legs split and extended upward')
add(374, '悬挂 · 单臂悬垂', '单臂抓住横杆高悬，身体侧向舒展，双腿并拢微弯', 'hanging from a horizontal bar on one arm, the body extended sideways with both legs together and slightly bent')
add(375, '舞蹈 · 半蹲双臂外展', '半蹲压低身体，双臂向两侧外展成一条横线', 'in a half squat with the body lowered and both arms spread out to the sides in a wide horizontal line')
add(376, '拉伸 · 双臂上举合掌', '双脚分开站立，双臂上举过头顶，双手合十相扣向上拉伸', 'standing with the feet apart, both arms raised overhead and the palms pressed together as if stretching upward')
add(377, '站立 · 单臂上举屈膝', '一腿屈膝抬起，另一腿支撑站立，一只手高举向上', 'standing on one leg with the other knee bent and lifted while one arm reaches straight up')
add(378, '舞蹈 · 俯身双臂后展', '上身大幅前俯贴近水平，双臂向身后两侧展平', 'bending the torso forward almost horizontal with both arms stretched out and back to the sides')
add(379, '舞蹈 · 单臂高举抬膝', '一腿屈膝抬起，支撑腿微屈，一只手高举过头，颈部后仰', 'dancing with one knee lifted, the supporting leg slightly bent and one arm raised high with the neck extended back')
add(380, '站立 · 抱腿抬膝', '单腿站立，双手抱住另一条腿屈膝提起贴近胸前', 'standing on one leg while using both hands to hug the other bent leg up toward the chest')
add(381, '弓步 · 屈臂顶髋', '宽弓步站立，前腿屈膝，一只手屈肘顶在髋部，另一手叉腰', 'in a wide lunge with the front knee bent, one hand flexed at the elbow pressing against the hip and the other on the waist')
add(382, '行走 · 抱臂前倾', '边走边把双臂抱在胸前，上身微微前倾', 'walking with both arms folded across the chest and the upper body leaning slightly forward')
add(383, '站立 · 侧身扬臂', '侧身站立，一臂向后上方扬起，另一臂垂在身前', 'standing in profile with one arm raised up and behind and the other hanging down in front')
add(384, '蹲坐 · 抱膝托腮', '蹲坐在脚跟上，双膝并拢抱起，一只手托住下巴', 'squatting on the heels with both knees drawn up and one hand propping the chin')
add(385, '弓步 · 前臂横挡', '前腿屈膝弓步，两条前臂在胸前交叉横挡在身前', 'in a forward lunge with both forearms crossed horizontally in front of the chest as a guard')
add(386, '拉伸 · 双臂上举踮脚', '双脚踮起脚尖，双臂伸直高举过头顶并交叠手指', 'rising onto the toes with both arms stretched straight overhead and the hands overlapping')
add(387, '舞蹈 · 侧倾单臂上扬', '身体向侧方倾斜成弧线，一只手向上扬起，另一只手向外伸出', 'dancing with the body curved in a side lean, one arm swept up and the other reaching outward')
add(388, '地面 · 仰卧剪刀腿', '仰卧在地面上，双腿高举在空中交叉张开成剪刀状', 'lying on the back with both legs lifted high and crossed apart in a scissor shape')
add(389, '站立 · 侧身垂臂后望', '侧身站立，双臂垂落身侧，头扭向斜后方', 'standing in profile with both arms hanging at the sides and the head turned to look back over the shoulder')
add(390, '蹲坐 · 环抱小腿', '低低蹲坐，双臂环抱住小腿两侧，肩膀收拢', 'crouching very low with both arms wrapped around the outsides of the shins and the shoulders drawn in')
add(391, '弓步 · 展臂后仰', '弓步分开双腿，双臂上举过头，躯干向后仰起', 'in a lunge with both arms raised overhead and the torso leaning backward')
add(392, '弓步 · 屈臂下压', '前腿屈膝弓步，双臂屈肘向下压向身体前侧', 'in a lunge with the front knee bent, both arms flexed at the elbows and pressed down in front of the body')
add(393, '弓步 · 单臂高举', '宽弓步站立，一只手高举过头顶，另一只手向斜下方伸出', 'in a wide lunge with one arm reaching straight up and the other extended diagonally downward')
add(394, '站立 · 双臂交叉上举', '双脚并拢站立，双臂在头顶交叉后向两侧打开', 'standing with the feet together and both arms crossed overhead before opening out to the sides')
add(395, '地面 · 俯卧屈膝抬脚', '俯卧在地面上，双腿屈膝向上抬起交叠在小腿后方', 'lying prone with both knees bent so the feet lift up and cross behind the calves')
add(396, '站立 · 抱头后仰', '站直身体，双手抱住后脑，肘部向两侧撑开，头部后仰', 'standing with both hands behind the head, elbows flared out and the head tilted back')
add(397, '站立 · 持棍俯身', '握着长杆垂在身侧，上身向前俯下贴近水平', 'holding a long staff down at the side while the torso bends forward to almost horizontal')
add(398, '舞蹈 · 侧步扬臂', '向侧方跨出一步，一只手向斜上方扬起，身体随步伐扭转', 'stepping to the side while one arm sweeps up diagonally and the torso twists with the movement')
add(399, '弓步 · 屈臂上举', '前腿屈膝弓步，双手屈肘上举到头侧，前臂向上发力', 'in a forward lunge with both arms flexed and raised beside the head, forearms driving upward')
add(400, '行走 · 抱臂侧步', '侧向迈步移动，双臂交抱在胸前，头部转向行走方向', 'walking sideways with both arms folded across the chest and the head turned toward the direction of travel')
add(401, '弓步 · 侧举长棍', '一腿向侧方伸直点地，一只手把长棍竖直举在头侧', 'extending one leg straight out to the side on the toes while holding a long staff upright beside the head')
add(402, '行走 · 垂臂迈步', '向前行走时双腿交替迈出，双臂垂直向下贴着身体', 'walking forward with the legs alternating in long steps and both arms hanging straight down against the body')
add(403, '跳跃 · 展臂腾空', '双腿腾空离地，双臂向两侧水平展开', 'airborne with both feet off the ground and both arms stretched out horizontally to the sides')
add(404, '站立 · 双臂外展分腿', '双脚大幅分开站立，双臂斜向两侧张开，与地面形成三角形', 'standing with the feet spread wide and both arms opened diagonally to the sides in a triangular shape')
add(405, '弓步 · 屈肘后撤', '一腿向后撤步屈膝，重心落在后腿，前臂向后拉', 'stepping back with the rear knee bent so the weight sits over the back leg, the forearms pulled behind')
add(406, '半跪 · 单臂上举', '单膝跪地，一只手高举过头顶，另一只手撑在大腿上', 'kneeling on one knee with one arm raised overhead and the other hand braced on the thigh')
add(407, '弓步 · 双手扶膝', '双腿宽分开成站立弓步，双手同时按在膝盖上，上身略前倾', 'in a wide standing lunge with both hands pressing on the knees and the upper body leaning slightly forward')
add(408, '弓步 · 侧身拉弓', '双腿分开侧身站立，一只手向后拉弓臂，另一只手在身前控弦', 'standing side-on with the legs apart, one arm pulling a bow back while the other hand holds the string in front')
add(409, '弓步 · 双手拉弓', '前腿屈膝半蹲，双手在胸前横向拉开一张弓', 'in a half squat with the front knee bent, drawing a bowstring back across the chest with both hands')
add(410, '弓步 · 举棍过头', '弓步分开双腿，双手把长棍举过头顶，棍身斜在身后', 'in a lunge with both hands lifting a long staff overhead so the pole rests diagonally behind')
add(411, '站立 · 横持长棍', '双脚分开站立，双手握着一根长棍横在腰腹前', 'standing with the feet apart, holding a long staff horizontally across the waist with both hands')
add(412, '弓步 · 双手持棍上举', '前后弓步站立，双手把长棍斜举到头顶上方', 'in a front-back lunge with both hands raising a long staff diagonally above the head')
add(413, '弓步 · 抬膝单臂后展', '前腿屈膝抬起，后腿蹬地支撑，一只手向侧后方展平', 'lifting the front knee while balancing on the rear leg and extending one arm out and back to the side')
add(414, '弓步 · 双臂前推', '半蹲弓步，双臂同时向前伸出推直，两手张开', 'in a half squat lunge with both arms pushed out straight in front and the hands open')
add(415, '站立 · 单臂侧前伸', '身体侧向站立，一只手向斜前方伸出，颈部随之外转', 'standing with the body turned sideways and one arm extended diagonally forward, the neck turning to follow')
add(416, '站立 · 叉腰并腿', '正面站直，双腿并拢交叉，双手同时撑在腰胯上', 'standing straight facing forward with the legs together and crossed and both hands on the hips')
add(417, '站立 · 双臂上举开掌', '双脚并拢站立，双臂高举向两侧斜上方打开，双掌朝外', 'standing with the feet together and both arms raised diagonally up and out, palms open')
add(418, '弓步 · 持棍前刺', '前腿弓步下压，双手握长棍水平向斜下方刺出', 'in a forward lunge, thrusting a long staff forward and downward while gripping it with both hands')
add(419, '站立 · 双臂上举交叠', '双脚分开站立，双臂高举过头并在头顶交叉交叠', 'standing with the feet apart and both arms raised overhead, crossing over each other at the top')
add(420, '弯腰 · 双手撑膝', '双脚分开站定，上身弯腰前俯，双手撑在两个膝盖上', 'standing with the feet apart, bending forward and resting both hands on the knees')
add(421, '弓步 · 单臂后摆', '一腿弓步前屈，另一只手向后大幅摆出，肩部后旋', 'in a lunge with the front knee bent while one arm swings far behind with the shoulder rotating back')
add(422, '平衡 · 抬膝展臂', '单腿站立，另一条腿屈膝抬起，双臂向两侧平平展开', 'balancing on one leg with the other knee raised and both arms stretched out flat to the sides')
add(423, '舞蹈 · 后仰双臂上扬', '躯干后仰弓起，双臂从身侧向斜上方扬起', 'arching the torso backward while sweeping both arms up and out from the sides')
add(424, '站立 · 叉腰侧倚', '一手叉腰，身体重心压向一侧，髋部侧移，双腿微分', 'standing with one hand on the hip, the weight shifted to one side so the hip juts out and the feet stay slightly apart')
add(425, '弓步 · 单手举棍后拉', '宽弓步站立，一只手把长棍高高举起向后拉，另一手扶在髋部', 'in a wide lunge with one arm lifting a long staff high and back while the other hand rests on the hip')
add(426, '弓步 · 单手侧举长棍', '一腿支撑抬起，另一只手把长棍水平举在体侧，另一臂向上张开', 'balancing on one leg with the other foot raised, holding a long staff horizontally at the side while the other arm opens upward')
add(427, '跳跃 · 双手举棍', '双腿前后分立成跳跃姿态，双手把长棍举到肩后蓄力', 'in a leaping stance with the legs split front and back, both hands drawing a long staff back behind the shoulder')
add(428, '弓步 · 双手举棍斜举', '弓步沉胯，双手把长棍斜举过头顶上方', 'in a lunge with the hips lowered, both hands raising a long staff diagonally above the head')
add(429, '弓步 · 持棍架肩', '弓步站立，一只手把长棍横搭在肩上，棍身斜向身后', 'in a lunge with one hand resting a long staff across the shoulder, the pole angled behind the back')
add(430, '弓步 · 低头持棍下压', '低头弓步，双手把长棍斜压到身前最低处', 'head lowered in a lunge while both hands press a long staff down toward the ground in front')
add(431, '弓步 · 举棍仰首', '弓步站定，双手把长棍举过面门，头部随棍抬起', 'in a lunge with both hands lifting a long staff up past the face and the head tilting up to follow it')
add(432, '倒立 · 单手撑地弓背', '单手撑地倒立，背部弓成弧形，双腿并拢向上弯曲', 'inverting on one arm with the back arched into a curve and both legs extended upward and slightly bent')
add(433, '行走 · 屈臂迈臂', '向前行走，双臂屈肘在胸前交替摆动', 'walking forward with both arms bent at the elbows and swinging alternately in front of the chest')
add(434, '站立 · 双臂上举张掌', '双脚分开站立，双臂屈肘上举到头侧，两手张开掌心朝前', 'standing with the feet apart, both arms raised and bent beside the head with the palms spread forward')
add(435, '站立 · 抱臂后仰', '双脚分开站直，双臂抱在胸前，上身向后挺起', 'standing straight with the feet apart, both arms folded across the chest and the upper body leaning back')
add(436, '站立 · 交臂侧身', '身体侧转，双臂在身前交抱，颈部转向镜头', 'the body turned sideways with both arms crossed in front and the neck rotated toward the viewer')
add(437, '半跪 · 双臂上举', '一腿跪地一腿弓起，双臂同时上举向两侧张开', 'half kneeling with one leg down and the other bent, both arms raised and opened to the sides')
add(438, '站立 · 双臂交叠腹前', '正面站直，双臂在腹部前方交叠，双肩微微内收', 'standing straight facing forward with both arms crossed low over the abdomen and the shoulders drawn in slightly')
add(439, '站立 · 扶颈后弓', '一手绕到颈后扶着后颈，头部后仰，胸口挺起', 'standing with one hand resting on the back of the neck, the head tilted back and the chest lifted')
add(440, '弓步 · 双手叉腰侧倾', '双腿宽分站定，双手叉腰，躯干向一侧倾斜', 'standing with the legs wide apart, both hands on the hips and the torso tilted to one side')
add(441, '站立 · 垂臂交叉腿', '正面站立，双腿在脚踝处交叉，双臂垂在身侧', 'standing facing forward with the ankles crossed and both arms hanging at the sides')
add(442, '站立 · 单臂高举开腿', '双脚分开站立，一只手笔直举过头顶，另一只手随身后摆', 'standing with the feet apart, one arm reaching straight overhead and the other swinging behind')
add(443, '站立 · 双手抱头后仰', '双手交叠托在脑后，肘部撑开，头部后仰', 'both hands clasped behind the head with the elbows flared out and the head tilted back')
add(444, '弓步 · 单臂上举侧看', '前腿弓步屈膝，一只手向上高举，头部看向手的方向', 'in a lunge with the front knee bent, one arm raised high and the head turned to look toward it')
add(445, '行走 · 交叉腿侧身', '侧身站立时一条腿交叉到另一条腿前方，双臂自然垂落', 'standing in profile with one leg crossed in front of the other and both arms resting naturally')
add(446, '站立 · 双臂环抱肘前', '正面站直，双臂环抱，两只手分别托住对侧手肘', 'standing straight facing forward with the arms wrapped around the torso, each hand holding the opposite elbow')
add(447, '行走 · 单手抬臂', '向前迈步行走，一只手抬到腰侧向斜上方摆动', 'stepping forward while raising one hand to the side of the waist and swinging it diagonally upward')
add(448, '行走 · 双手叉腰迈步', '一边行走一边双手叉腰，双腿交替跨步', 'walking forward with both hands on the hips and the legs alternating in long strides')
add(449, '平衡 · 抬膝前伸', '单腿站立，另一条腿屈膝抬起，同时一只手向前伸出', 'balancing on one leg with the other knee raised while one arm reaches straight out in front')
add(450, '站立 · 单手抚颊', '站定身体，一手抬起轻贴脸颊，另一只手垂在身侧', 'standing still with one hand lifted against the cheek and the other arm hanging at the side')
add(451, '弓步 · 反臂后摆', '弓步下蹲，一只手反手向斜后方甩出，身体随之扭转', 'in a deep lunge with one arm thrown back and out behind as the torso twists away')
add(452, '平衡 · 抬膝抱头', '单腿站立，另一腿屈膝抬起，双手抱在头顶', 'balancing on one leg with the other knee raised and both hands clasped on top of the head')
add(453, '平衡 · 抬膝抱胸', '单腿站立，另一条腿屈膝横在身前，双臂抱住膝盖', 'balancing on one leg with the other knee drawn across the body and both arms hugging the raised knee')
add(454, '站立 · 屈肘举指', '双腿交叉站立，一手叉腰，另一只手屈肘举起手指向上', 'standing with the legs crossed, one hand on the hip and the other hand flexed at the elbow with fingers raised')
add(455, '弓步 · 单手叉腰', '一腿向前伸出点地，另一只手叉在腰间，上身微微后倾', 'with one leg extended forward on the toes, the other hand planted on the hip and the torso leaning slightly back')
add(456, '深蹲 · 广脚蹲俯身', '双脚大幅分开深蹲成蛤式，躯干前俯，双臂垂在两腿之间', 'squatting very wide into a frog stance with the torso pitched forward and both arms hanging between the legs')
add(457, '站立 · 垂臂正面', '正面对镜头站直，双脚分开，双臂自然垂在身体两侧', 'standing straight and facing the viewer with the feet apart and both arms hanging at the sides')
add(458, '弓步 · 双臂侧展', '双腿分开成站立弓步，双臂向两侧水平展开', 'in a wide standing lunge with both arms extended horizontally out to the sides')
add(459, '站立 · 双臂微展', '正面站立，双腿微分，双臂在身体两侧微微离开躯干', 'standing facing forward with the feet slightly apart and both arms held a little away from the body')
add(460, '站立 · 单手抚胸', '站定身体，一手按在胸前，另一只手垂在身侧', 'standing still with one hand pressed to the chest and the other arm hanging at the side')
add(461, '弓步 · 屈肘举拳', '前腿弓步屈膝，一只手屈肘举到肩侧并握拳', 'in a forward lunge with one hand flexed at the elbow and raised beside the shoulder in a fist')
add(462, '弓步 · 屈肘撑腿', '宽弓步站立，一手撑在大腿上，另一只手屈肘抬在胸前', 'in a wide lunge with one hand braced on the thigh and the other flexed at the elbow in front of the chest')
add(463, '弓步 · 抱胸侧立', '双腿分开侧身站立，双臂抱在胸前，颈部转向镜头', 'standing side-on with the legs apart and both arms folded across the chest, the head turned to the camera')
add(464, '弓步 · 跪姿持棍', '一腿跪地一腿屈膝，单手把长棍竖直插在身侧地面', 'kneeling on one knee with the other leg bent, holding a long staff vertically planted on the ground beside the body')
add(465, '弓步 · 持棍斜扛', '弓步分开双腿，一只手把长棍斜扛在肩上，棍身指向斜上方', 'in a wide lunge with one hand shouldering a long staff at an angle pointing up')
add(466, '弓步 · 持棍后拉', '前腿屈膝弓步，一只手握长棍在身体后方低位拉出', 'in a forward lunge with one hand drawing a long staff back low behind the body')
add(467, '弓步 · 双臂平展持棍', '弓步下蹲，两臂向两侧平展，一手握长棍横在身前', 'in a lowered lunge with both arms extended out to the sides and one hand holding a long staff horizontally in front')
add(468, '行走 · 垂臂正面', '正面对镜头行走，双臂垂直下垂，双腿交替迈步', 'walking toward the viewer with both arms hanging straight down and the legs alternating in steps')
add(469, '平衡 · 抬膝后仰', '单腿站立，另一条腿屈膝抬起，上身向后仰起', 'balancing on one leg with the other knee raised and the torso leaning backward')
add(470, '行走 · 侧身背手', '侧身行走时双手背在身后，双脚交替迈步', 'walking in profile with both hands clasped behind the back and the feet alternating in steps')
add(471, '平衡 · 单腿后折举臂', '单腿站立，另一条腿向后折起，手臂高举过头', 'standing on one leg with the other leg folded back and the arms lifted overhead')
add(472, '行走 · 双臂平展', '向前行走时双臂向两侧水平伸直展开', 'walking forward with both arms extended straight out horizontally to the sides')
add(473, '平衡 · 抬膝竖拇指', '单腿站立，另一腿屈膝抬起，一只手朝前竖起大拇指', 'balancing on one leg with the other knee raised and one hand held in front with the thumb up')
add(474, '站立 · 单手扶头侧倾', '一手扶在头顶上侧，躯干向同侧倾斜，双腿微分站立', 'standing with one hand resting on top of the head and the body leaning to that side, the feet slightly apart')
add(475, '弓步 · 抬膝勾脚', '支撑腿屈膝下压，另一条腿屈膝勾脚抬起，手臂向外侧张开', 'lowering onto one bent leg while lifting the other with the knee bent and toe pointed up, the arms opening outward')
add(476, '舞蹈 · 侧踢腿展臂', '单腿支撑，另一条腿向斜上方踢起，双臂向两侧张开保持平衡', 'balancing on one leg while kicking the other leg up and out to the side with both arms spread for balance')
add(477, '弓步 · 抱臂立正', '双腿分开站直，双臂交抱在胸前，肩部向后打开', 'standing straight with the legs apart and both arms folded across the chest, the shoulders opened back')
add(478, '舞蹈 · 跃起张臂', '身体腾空跃起，双臂向前上方张开，双腿一前一后蹬离地面', 'leaping into the air with both arms opening forward and upward and the legs pushing off one behind the other')
add(479, '平衡 · 抬膝双臂上举', '单腿站立，另一条腿屈膝抬起，双臂在头顶上方交叠成环', 'balancing on one leg with the other knee raised and both arms crossed into an arch above the head')
